import type { VSLSlide } from '@/components/sales-page/VSLSlideshow';

// Storyboard slides for the beginner-audience VSL.
// Classic VSL cadence: one short line per slide, the full narration kept in
// notes. Mirrors MILLIONAIRE_MINDSHIFT_VSL_STARTER.md (chapters + shots).
export const VSL_STARTER_SLIDES: VSLSlide[] = [
  {
    layout: 'cover',
    label: 'INTRO',
    title: 'Millionaire Mindshift',
    kicker: 'Millionaire Mindshift',
    text: 'Why money keeps slipping away.',
    sub: 'And the one small reset that changes it.',
    scene: 'Warm title card on black, soft gold light, slow drifting dust.',
    shot: 'Title',
  },

  // CH1 - Warm hook
  {
    label: 'CH1',
    timecode: '0:00',
    title: 'Hook',
    text: 'You work hard.',
    sub: "But money's always tight.",
    vo: 'If you work hard but money is always tight, this is for you.',
    scene: 'Tired person at a kitchen table at night, bills stacked, phone showing a low balance. Slow push in on the face.',
    why: 'Mirror hook. Open on the exact felt problem so they lean in.',
    shot: 'Shot 1',
  },
  {
    label: 'CH1',
    title: 'Hook',
    text: "It's not your fault.",
    vo: 'You are not bad with money. You are not lazy. You are not broken.',
    scene: 'Same kitchen table, hold on the eyes. Tiny breath of relief.',
    why: 'Removes shame in the first breath. Big dopamine through being seen.',
    shot: 'Shot 1',
  },
  {
    label: 'CH1',
    title: 'Hook',
    text: 'A hidden setting runs the show.',
    sub: 'And it keeps pulling you back to broke.',
    vo: 'There is a hidden setting in the back of your mind that keeps pulling you back to broke. It was put there when you were a kid.',
    scene: 'Slow push past the person toward a dim glow in the background.',
    why: 'Names the new enemy. Curiosity: what setting? Opens the loop.',
    shot: 'Shot 1',
  },

  // CH2 - Open loop + proof
  {
    layout: 'proof',
    label: 'CH2',
    timecode: '0:20',
    title: 'Proof',
    stat: '$1,000',
    statSub: 'Saved in one month',
    text: 'Same paycheck.',
    sub: 'She changed one thing on the inside.',
    vo: 'A woman who was broke her whole life saved her first one thousand dollars in a single month. No new job. She changed one small thing on the inside.',
    scene: 'Close on a hand dropping folded cash into a glass jar that fills. A hopeful smile in the reflection. Slow tilt up.',
    why: 'Smoking gun at a believable number. Proof you can copy.',
    shot: 'Shot 2',
  },

  // CH3 - Deeper core
  {
    label: 'CH3',
    timecode: '0:42',
    title: 'Core',
    text: 'It started when you were a kid.',
    vo: 'When you were little, you learned how money works by watching.',
    scene: 'Dreamlike warm memory: a child on the stairs watching worried parents at a bill-covered table. Soft haze. Slow drift forward.',
    why: 'Deeper core. Walks them back to the root, gently.',
    shot: 'Shot 3',
  },
  {
    label: 'CH3',
    title: 'Core',
    text: '"We can\'t afford that."',
    sub: 'You heard it. You felt it.',
    vo: 'Maybe you heard, we can\u2019t afford that. Maybe you saw a worried face when a bill came in. Maybe money felt scary in your house.',
    scene: 'Child\u2019s eyes flick to a parent\u2019s tight face. Warm, nostalgic, soft focus.',
    why: 'Specific childhood lines make the wound real and shared.',
    shot: 'Shot 3',
  },
  {
    label: 'CH3',
    title: 'Core',
    text: 'Your mind wrote a rule:',
    sub: 'Money is hard.',
    vo: 'You did not choose any of that. But your mind wrote it down as a rule. Money is hard. And it has been running quietly ever since.',
    scene: 'The words feel etched in warm light, then fade into shadow.',
    why: 'Names the exact limiting belief in four plain words.',
    shot: 'Shot 3',
  },

  // CH4 - New cause
  {
    label: 'CH4',
    timecode: '1:08',
    title: 'New Cause',
    text: 'So you try to fix it.',
    sub: 'Budget. Extra hours. Affirmations.',
    vo: 'So you try to fix it the normal way. Work more hours. Make a budget. Read a money book. Say nice things in the mirror.',
    scene: 'A table of budget notebook, calculator, and a money book under warm light.',
    why: 'Lists what they have already tried, so they feel understood.',
    shot: 'Shot 4',
  },
  {
    label: 'CH4',
    title: 'New Cause',
    text: 'It works... for a week.',
    vo: 'And it helps. For about a week. Then you are right back where you started.',
    scene: 'Close on coins and fine sand slipping through tightly closed fingers.',
    why: 'Names the relapse they know too well. Builds tension.',
    shot: 'Shot 4',
  },
  {
    label: 'CH4',
    title: 'New Cause',
    text: "You can't budget your way out of a setting.",
    vo: 'The problem was never how hard you try. It is that hidden setting. You have to change the setting itself.',
    scene: 'The sand stops mid-fall, held in warm light. A beat of stillness.',
    why: 'The reframe. Past failure was the wrong tool, not a broken you.',
    shot: 'Shot 4',
  },

  // CH5 - Mechanism
  {
    label: 'CH5',
    timecode: '1:36',
    title: 'Mechanism',
    text: "We're Christian and Amber.",
    sub: 'More money never fixed the stress.',
    vo: 'We are Christian and Amber. We used to think more money would finally fix the stress. It never did.',
    scene: 'Christian and Amber on camera (real footage), warm room, calm and kind.',
    why: 'Authority through sameness, not status. They are us.',
    shot: 'Shot 5',
  },
  {
    label: 'CH5',
    title: 'Mechanism',
    text: 'Find. Test. Clear. Replace.',
    sub: 'The Subconscious Reset.',
    vo: 'So we built a simple reset. Four steps. Find the rule. Test it. Clear it. Put in a new one.',
    scene: 'Four short words light up one at a time in warm gold on black.',
    why: 'The mechanism, named and numbered. Easy to remember and repeat.',
    shot: 'Shot 6',
  },
  {
    label: 'CH5',
    title: 'Mechanism',
    text: 'Your own body shows you the rule.',
    sub: 'A simple check. No more guessing.',
    vo: 'The part that surprises everyone is the test. A simple body check. Your own arm shows you the hidden rule.',
    scene: 'A gentle muscle-test press on a forearm: the arm holds strong, then drops.',
    why: 'The disbelief-killer. Makes the invisible feel physical and real.',
    shot: 'Shot 7',
  },
  {
    label: 'CH5',
    title: 'Mechanism',
    text: 'Then set the dial higher.',
    sub: 'So money can finally stay.',
    vo: 'Then we clear the old rule, and we set the dial higher, so money can finally stay.',
    scene: 'A round wall thermostat dial turns slowly from low to high, glowing warm gold.',
    why: 'The thermostat symbol: a beginner can feel "raise the setting".',
    shot: 'Shot 6',
  },

  // CH6 - Proof stack
  {
    label: 'CH6',
    timecode: '2:14',
    title: 'Proof Stack',
    text: 'A mom paid off her credit card.',
    vo: 'A mom paid off a credit card she had carried for years.',
    scene: 'Warm shot of scissors cutting a credit card in half.',
    why: 'Small, believable win. Stacks proof for an everyday viewer.',
    shot: 'Shot 8',
  },
  {
    label: 'CH6',
    title: 'Proof Stack',
    text: 'A guy finally asked for the raise.',
    sub: 'Got it the same week.',
    vo: 'A guy who was too scared to ask for a raise finally asked, and got it the same week.',
    scene: 'A friendly handshake over a desk, warm light.',
    why: 'Second believable win. Builds momentum and belief.',
    shot: 'Shot 8',
  },
  {
    label: 'CH6',
    title: 'Proof Stack',
    text: 'Same paycheck. New setting.',
    vo: 'Same people. Same paycheck. The only thing that changed was the setting.',
    scene: 'Coins and bills filling a jar a little higher. Soft gold bloom.',
    why: 'Drives the through-line home. The setting is the lever.',
    shot: 'Shot 8',
  },

  // CH7 - Offer
  {
    layout: 'offer',
    label: 'CH7',
    timecode: '2:36',
    title: 'Offer',
    text: 'The whole method.',
    price: '$27',
    originalPrice: '$197',
    priceNote: 'Less than one dinner out',
    sub: 'Plus short audios for the car or bedtime.',
    vo: 'We put the whole thing into one simple program. Find your rule, the body check, the clearing, the new rule, plus short audios to keep it going. The whole thing is twenty seven dollars.',
    scene: 'A friendly program mockup on a warm wooden table: a phone showing lessons, headphones beside it. Price stamp lands: $27 over a struck-through $197.',
    why: 'Offer anchored against a dinner out. Easy yes.',
    shot: 'Shot 9',
  },

  // CH8 - Two roads
  {
    layout: 'tworoads',
    label: 'CH8',
    timecode: '2:56',
    title: 'Two Roads',
    text: 'Two roads. One choice.',
    roadLeft: {
      title: 'Stay the same',
      body: 'Keep working hard and watching money slip away, year after year.',
    },
    roadRight: {
      title: 'Change the setting',
      body: 'Take one hour, change the setting, and let money finally stay.',
    },
    vo: 'Keep working hard and watching money slip away. Or take one hour, change the setting, and let money finally start to stay.',
    scene: 'A fork in a warm-lit path. Left loops back like a treadmill, right opens to a bright calm horizon. Camera drifts right.',
    why: 'Tale of two futures. Real consequence, not fake scarcity.',
    shot: 'Shot 10',
  },

  // CH9 - Close
  {
    label: 'CH9',
    timecode: '3:10',
    title: 'Close',
    text: 'Did a part of you just go...',
    sub: '"That\'s me"?',
    vo: 'If a part of you just went, that is me, listen to that part. It has been waiting a long time for someone to say this is not your fault.',
    scene: 'Back to the person from Shot 1, calmer now, a full money jar beside them, a small steady smile.',
    why: 'Call to identity. Speaks to the part that already raised its hand.',
    shot: 'Shot 11',
  },
  {
    layout: 'close',
    label: 'CH9',
    title: 'Close',
    text: 'Start the reset.',
    sub: "Let's change the setting, and let money stay.",
    vo: 'Click the button. Start the reset. Let\u2019s change the setting, and let money stay.',
    scene: 'The same person reaches gently toward the camera. Warm gold light bloom.',
    why: 'Hands them the choice on a warm, hopeful note.',
    shot: 'Shot 11',
  },

  // Optional paid-traffic pre-roll
  {
    label: 'AD',
    title: 'Optional Pre-Roll',
    text: 'Yeah, this is an ad.',
    sub: 'Watch it anyway.',
    vo: 'Yeah, this is an ad. Watch it anyway, because it explains the real reason money keeps feeling so hard.',
    scene: '5-second cold open. Direct-to-camera or the kitchen-table hero shot with the line as a quick on-screen card.',
    why: '4th wall break + pattern interrupt for paid traffic.',
    shot: 'Shot 1 (alt)',
  },
];
