import { html, introBox, media, step, callout, table, chip, type SeedArticle } from './helpers';

/** Buyer-facing help docs. These are the customer-facing articles shown
 *  publicly at /mothermode/help, so they are written for the person who BOUGHT
 *  the product, not the person running it. Every one sets audience: 'buyer'. */
export const buyerHelp: SeedArticle[] = [
  {
    slug: 'access-your-purchase',
    title: 'How to access everything you just bought',
    category: 'Your Purchase',
    excerpt: 'Where your resources live, how to get back in, and what to do if the email never arrived.',
    sortOrder: 1,
    published: true,
    audience: 'buyer',
    body: html(
      `<p>Welcome. Everything you bought is delivered inside MotherMode, and getting back to it is simple. This guide walks you through finding your resources the first time and getting back in any time after.</p>`,
      introBox([
        ['Who this is for', 'You, right after checkout'],
        ['What you need', 'The email address you used at checkout'],
        ['Time', 'About two minutes'],
      ]),
      `<h2>Get in for the first time</h2>`,
      step(1, 'Check your inbox for the access email',
        `<p>Right after checkout, an access email lands at the address you used to buy. It has your sign-in link. Open it on the device you want to use.</p>`),
      step(2, 'Open your resource library',
        `<p>The link takes you straight to your resources. Everything you bought is listed there, ready to open. There is nothing to install and nothing else to download first.</p>`),
      step(3, 'Bookmark your library page',
        `<p>Save the page to your bookmarks or home screen. That is your permanent way back in, no hunting for the email required.</p>`),
      `<h2>Come back later</h2>`,
      step(1, 'Return to your bookmarked library page',
        `<p>Your resources stay put. Anything you filled in, like a worksheet or planner, is saved to your email and is waiting exactly as you left it.</p>`),
      step(2, 'Use the same email you bought with',
        `<p>Your access is tied to the email you used at checkout. Always sign in with that same address so your purchases and your saved work appear.</p>`),
      media('access-your-purchase', 'image', 'A screenshot of the resource library a buyer sees right after purchase belongs here.'),
      callout('tip', 'One email, everything',
        `<p>Buy something else later with the same email and it appears in the same library automatically. Keep using one email for every purchase and your resources never split across accounts.</p>`),
    ),
  },
  {
    slug: 'find-and-use-deliverables',
    title: 'Find and use your deliverables and worksheets',
    category: 'Your Purchase',
    excerpt: 'How to open each resource, fill in the interactive worksheets, and pick up where you left off.',
    sortOrder: 2,
    published: true,
    audience: 'buyer',
    body: html(
      `<p>Your purchase includes resources you read and resources you use. This guide shows you how to open each one and how the interactive worksheets save your work.</p>`,
      introBox([
        ['What this covers', 'Opening resources and using worksheets'],
        ['Your work is saved', 'Automatically, to your email'],
        ['Works on', 'Phone, tablet, and computer'],
      ]),
      `<h2>Open a resource</h2>`,
      step(1, 'Go to your library',
        `<p>Open your bookmarked resource library. Each purchase appears as its own card or section.</p>`),
      step(2, 'Click the resource you want',
        `<p>Guides, ebooks, and checklists open to read right away. Some are styled documents you can also print from your browser if you like a paper copy.</p>`),
      `<h2>Use an interactive worksheet or planner</h2>`,
      step(1, 'Open the worksheet',
        `<p>Worksheets and planners open with fields you can type into directly. No download, no special app.</p>`),
      step(2, 'Fill it in at your own pace',
        `<p>Your answers save automatically as you go, tied to your email. You do not have to finish in one sitting.</p>`),
      step(3, 'Come back and it is all still there',
        `<p>Sign back in with the same email and your previous answers are waiting. You can review, change, or add to them any time.</p>`),
      media('find-and-use-deliverables', 'video', 'A short screen recording of opening a worksheet, typing an answer, and coming back to find it saved belongs here.'),
      callout('info', 'Your answers are private',
        `<p>What you write in a worksheet is saved to your email address only. No one else who buys the same product can see your answers.</p>`),
    ),
  },
  {
    slug: 'missing-access-email',
    title: 'The access email never arrived',
    category: 'Help & Support',
    excerpt: 'What to check first, and how to get back in fast when the sign-in email does not show up.',
    sortOrder: 1,
    published: true,
    audience: 'buyer',
    body: html(
      `<p>Nine times out of ten a "missing" access email is sitting in a folder you have not checked yet, or it went to a slightly different address. Run through these steps in order and you will almost always find it in a minute.</p>`,
      introBox([
        ['First, do not worry', 'Your purchase is recorded'],
        ['Most common cause', 'Spam folder or a typo in the email'],
        ['Time to fix', 'Usually under two minutes'],
      ]),
      `<h2>Find it, step by step</h2>`,
      step(1, 'Search your inbox, do not just scroll',
        `<p>Search for the product name and for "access". Search finds it even when it is buried under newer mail.</p>`),
      step(2, 'Check Spam, Promotions, and Updates folders',
        `<p>Automated access emails get filed away by Gmail and others constantly. Look in Spam, Promotions, and Updates before assuming it never sent.</p>`),
      step(3, 'Confirm which email you used at checkout',
        `<p>If you have more than one address, check the others. The access email goes to the exact address typed at checkout, and a single-letter typo sends it elsewhere.</p>`),
      step(4, 'Give it a few minutes, then resend',
        `<p>Email can lag a few minutes. If it is still missing after ten, request a fresh access link from the sign-in page using the same email.</p>`),
      `<h2>Still nothing</h2>`,
      `<p>If you have checked everywhere and the resend does not arrive, reach out to support with the email you used and roughly when you bought. Your purchase is on record, so access can always be restored. You will not lose what you paid for.</p>`,
      callout('warn', 'A typo at checkout is the usual culprit',
        `<p>If you think you mistyped your email when buying, contact support with your correct address and any order detail you have. They can move the purchase to the right email.</p>`),
    ),
  },
  {
    slug: 'devices-and-printing',
    title: 'Use your resources on any device and print them',
    category: 'Your Purchase',
    excerpt: 'Read on phone, tablet, or computer, and how to print a clean copy of any document.',
    sortOrder: 3,
    published: true,
    audience: 'buyer',
    body: html(
      `<p>Your resources work wherever you are, on whatever screen is in front of you. This guide covers switching between devices and printing a clean paper copy.</p>`,
      introBox([
        ['Works on', 'Phone, tablet, and computer'],
        ['Syncs through', 'Your email address'],
        ['Printing', 'Straight from your browser'],
      ]),
      `<h2>Use any device</h2>`,
      step(1, 'Sign in with the same email everywhere',
        `<p>Open your library and sign in with the email you bought with on whatever device you are holding. Your resources and your saved worksheet answers follow that email.</p>`),
      step(2, 'Pick up on one device where you left off on another',
        `<p>Start a worksheet on your computer and finish it on your phone. Because your work saves to your email, it is the same answers on every screen.</p>`),
      `<h2>Print a document</h2>`,
      step(1, 'Open the resource you want on paper',
        `<p>Guides, ebooks, and checklists are styled documents that print cleanly.</p>`),
      step(2, 'Use your browser print',
        `<p>On a computer, press ${chip('Ctrl')} + ${chip('P')} (or ${chip('Cmd')} + ${chip('P')} on a Mac). Choose your printer and print. The document is already formatted to look good on the page.</p>`),
      step(3, 'Save a PDF instead if you prefer',
        `<p>In the same print dialog, choose "Save as PDF" as the destination. You get a copy you can keep, share with a partner, or print later.</p>`),
      media('devices-and-printing', 'image', 'A screenshot of the browser print dialog with "Save as PDF" selected belongs here.'),
      callout('tip', 'Print the worksheets too',
        `<p>Prefer pen and paper for a worksheet? Print a blank copy from the same print dialog and fill it in by hand. Your typed answers stay saved online either way.</p>`),
    ),
  },
  {
    slug: 'billing-and-receipts',
    title: 'Receipts, billing questions, and refunds',
    category: 'Help & Support',
    excerpt: 'Where your receipt is, what shows on your statement, and how a refund works if you need one.',
    sortOrder: 2,
    published: true,
    audience: 'buyer',
    body: html(
      `<p>Everything about the money side of your purchase lives here: your receipt, what appears on your bank statement, and what to do if you need a refund.</p>`,
      introBox([
        ['Your receipt', 'Emailed right after checkout'],
        ['Secure payment', 'Handled by Stripe'],
        ['Refunds', 'Reach out, we sort it out'],
      ]),
      `<h2>Your receipt</h2>`,
      step(1, 'Check your inbox after checkout',
        `<p>A receipt is emailed to the address you used at checkout right after payment. Keep it for your records. If it is not in your inbox, check Spam and Promotions, same as the access email.</p>`),
      step(2, 'Recognize the charge on your statement',
        `<p>Your payment is processed securely by Stripe. The line on your bank or card statement will reference the product or the business name, depending on your bank.</p>`),
      `<h2>If you need a refund</h2>`,
      step(1, 'Reach out to support',
        `<p>Contact support with the email you bought with and the order or receipt details. You do not need to dispute the charge with your bank first.</p>`),
      step(2, 'We review and process it',
        `<p>Refunds go back to the original payment method through Stripe. Depending on your bank, the credit can take a few business days to appear.</p>`),
      callout('info', 'Contact us before a chargeback',
        `<p>If something looks wrong, message support first. It is almost always faster to fix directly than through a bank dispute, and it keeps your access intact while we sort it.</p>`),
    ),
  },
];
