import type { SeedChangelog } from './helpers';

function cl(parts: string[]): string {
  return parts.join('\n').trim();
}

export const HELP_CENTER_SEED_CHANGELOG: SeedChangelog[] = [
  {
    version: '0.1.0',
    releasedOn: '2026-06-28',
    entryType: 'added',
    title: 'AI content library and per-piece review state',
    body: cl([
      '<p>The generated content library landed. AI drafts and their review state (generated images, picked hooks, YouTube kits) now persist in Supabase instead of living only in the browser.</p>',
      '<p><strong>Why it matters:</strong> you can close the tab mid-review and come back to every draft exactly as you left it, on any device.</p>',
    ]),
    published: true,
  },
  {
    version: '0.2.0',
    releasedOn: '2026-07-01',
    entryType: 'added',
    title: 'Admin-editable deliverables',
    body: cl([
      '<p>Buyer deliverables are now editable in the admin with the drafts-and-publishing model. Overrides layer on top of built-in defaults, so the product is never broken by an empty admin state.</p>',
      '<p><strong>Why it matters:</strong> improving what a buyer receives no longer needs a deploy. Edit a section, save, and it is live.</p>',
    ]),
    published: true,
  },
  {
    version: '0.2.1',
    releasedOn: '2026-07-05',
    entryType: 'added',
    title: 'Buyer resource workspaces',
    body: cl([
      '<p>Interactive resources (worksheets, planners) now store buyer entries scoped by email, so a returning buyer finds their previous work and one buyer never sees another\'s entries.</p>',
    ]),
    published: true,
  },
  {
    version: '0.3.0',
    releasedOn: '2026-07-10',
    entryType: 'added',
    title: 'Help Center: knowledge base and changelog',
    body: cl([
      '<p>This system. Knowledge base articles and a release changelog, authored in /admin/help and published without a deploy. Drafts are admin-only; published rows are readable by the public viewer.</p>',
    ]),
    published: true,
  },
  {
    version: '0.4.0',
    releasedOn: '2026-07-15',
    entryType: 'added',
    title: 'Community Kit',
    body: cl([
      '<p>One intake generates a complete community launch kit: name, description, three qualifying questions for paid and free, a DM script, a sales-call script, an ad content style, a lead form, and the first pinned post.</p>',
      '<p><strong>Where to start:</strong> Kits / Community Kit, in this Help Center.</p>',
    ]),
    published: true,
  },
  {
    version: '0.5.0',
    releasedOn: '2026-07-25',
    entryType: 'added',
    title: 'Lead Gen Kit',
    body: cl([
      '<p>An AI lead-magnet builder with ten formats, length-driven multi-pass generation for coherent ultra-long documents, and one-click publish of a self-contained styled document to Deliverables.</p>',
    ]),
    published: true,
  },
  {
    version: '0.6.0',
    releasedOn: '2026-07-30',
    entryType: 'added',
    title: 'Email Marketing Kit',
    body: cl([
      '<p>Campaign sequences from eight deterministic blueprints and nine per-email frameworks, with timing styles and plain-text-source-of-truth export to styled HTML or CSV. The model writes only copy; the arc is always sound.</p>',
    ]),
    published: true,
  },
  {
    version: '0.6.1',
    releasedOn: '2026-07-31',
    entryType: 'improved',
    title: 'Two-way context for kits and content',
    body: cl([
      '<p>The Context Bridge now flows both directions: a saved email sequence can be attached to the content Generate drawer, and kits carry their own context selectors, so context flows from kits into content and back.</p>',
    ]),
    published: true,
  },
  {
    version: '0.7.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Email images in body and funnel asset library',
    body: cl([
      '<p>Images insert into email bodies from the Studio, gallery images round-trip as edit seeds, and a polymorphic asset library attaches any kit to a funnel, resolved through the Context Bridge.</p>',
    ]),
    published: true,
  },
  {
    version: '0.8.0',
    releasedOn: '2026-08-12',
    entryType: 'added',
    title: 'Sales funnel AI builder and editor refactor',
    body: cl([
      '<p>The sales funnel editor gained the AI autofill (every page drafted from the offer), per-page regenerate bars, chrome and media editing, and a layout refactor for the master/detail workspace.</p>',
      '<p><strong>Where to start:</strong> Offers and Funnels / Sales Funnels, in this Help Center.</p>',
    ]),
    published: true,
  },
  {
    version: '0.8.1',
    releasedOn: '2026-08-18',
    entryType: 'fixed',
    title: 'Clear error when the AI key is invalid',
    body: cl([
      '<p>The funnel AI builder now surfaces a clear banner when the OpenAI key is missing or invalid, instead of failing silently. If the builder refuses to run, check Admin / Integrations first.</p>',
    ]),
    published: true,
  },
  {
    version: '0.9.0',
    releasedOn: '2026-08-25',
    entryType: 'added',
    title: 'Email flow canvas, testing, and analytics',
    body: cl([
      '<p>The transactional email layer gained the visual flow canvas, funnel event assignment, a testing inbox preview with real tokens, and send, open, and click analytics dashboards.</p>',
    ]),
    published: true,
  },
  {
    version: '0.10.0',
    releasedOn: '2026-09-02',
    entryType: 'added',
    title: 'Seedance video pipeline and storyboard lab',
    body: cl([
      '<p>Script to storyboard to render: second-by-second scene scripts, per-beat storyboard approval, and the Seedance render step with a model selector and per-clip progress.</p>',
      '<p><strong>Where to start:</strong> Content Hub / Video, in this Help Center.</p>',
    ]),
    published: true,
  },
  {
    version: '0.11.0',
    releasedOn: '2026-09-10',
    entryType: 'added',
    title: 'Brand Bible, Asset Hub, and admin palette alignment',
    body: cl([
      '<p>The Brand Bible centralizes the voice and visual rules every generator follows, the Asset Hub adds the offer-systems view that checks an offer is complete, and every admin surface was aligned to one palette.</p>',
    ]),
    published: true,
  },
  {
    version: '0.12.0',
    releasedOn: '2026-09-20',
    entryType: 'added',
    title: 'Opt-in funnels with steps and destinations',
    body: cl([
      '<p>Standalone lead-capture funnels with per-step URLs, post-capture destinations, and UTM-preserving lead capture, so a no-sale still becomes a lead you can follow up with.</p>',
    ]),
    published: true,
  },
  {
    version: '0.13.0',
    releasedOn: '2026-10-05',
    entryType: 'added',
    title: 'Tracked links and UTM everywhere',
    body: cl([
      '<p>Every post link is now a minted /go/code link with UTM parameters. Planner cards, funnel links, and opt-in destinations all mint and carry tracked links, so clicks, leads, and sales join back to the exact post.</p>',
      '<p><strong>One rule:</strong> always mint links from the piece, never by hand. See Offers and Funnels / Tracked Links.</p>',
    ]),
    published: true,
  },
  {
    version: '0.13.1',
    releasedOn: '2026-10-06',
    entryType: 'improved',
    title: 'Loopback guard and click rollups',
    body: cl([
      '<p>Tracked links minted against local or loopback destinations are repaired automatically, and per-card click rollups now keep pace with the raw click rows.</p>',
    ]),
    published: true,
  },
  {
    version: '0.13.2',
    releasedOn: '2026-10-06',
    entryType: 'fixed',
    title: 'Clicks written but not counted',
    body: cl([
      '<p>Fixed a class of bug where raw click rows were written but the link counter did not reflect them, so cards showed zero clicks on links with real traffic.</p>',
      '<p><strong>If numbers still look wrong:</strong> run scripts/inspect-tracked-link-clicks.cjs to separate write, counter, and join problems.</p>',
    ]),
    published: true,
  },
  {
    version: '0.13.3',
    releasedOn: '2026-10-07',
    entryType: 'fixed',
    title: 'Organic thread tagged as paid',
    body: cl([
      '<p>Fixed the medium derivation that could tag an organic thread as paid when its format resolved to a paid medium, which produced phantom paid metrics on cards.</p>',
    ]),
    published: true,
  },
  {
    version: '0.14.0',
    releasedOn: '2026-10-07',
    entryType: 'added',
    title: 'Publish state system for planner cards',
    body: cl([
      '<p>Every planner card now carries an explicit draft, scheduled, or published state with badges and board filters, so the board shows what is actually live at a glance.</p>',
    ]),
    published: true,
  },
  {
    version: '0.14.1',
    releasedOn: '2026-10-08',
    entryType: 'fixed',
    title: 'Planner card missing offer slug',
    body: cl([
      '<p>Fixed cards that could be created without their offer slug, which broke the link from a card back to its offer.</p>',
    ]),
    published: true,
  },
  {
    version: '1.0.0',
    releasedOn: '2026-10-26',
    entryType: 'added',
    title: 'Knowledge base rewritten as step-by-step guides',
    body: cl([
      '<p>The Help Center knowledge base now ships with a full step-by-step guide per feature across every area of the app, with numbered walkthroughs, tables, and callouts, plus reserved media slots for walkthrough videos and screenshots.</p>',
    ]),
    published: true,
  },
  {
    version: '1.1.0',
    releasedOn: '2026-10-26',
    entryType: 'added',
    title: 'Facebook color-block posts and TikTok photo-mode slideshows',
    body: cl([
      '<p>Two new native formats. Facebook color-block posts render a short hook as big bold text on a brand background, with a palette composer and a one-click render to a shareable image. TikTok photo-mode slideshows are swipeable multi-image posts where every slide carries its own styled, editable text that you can burn onto the image.</p>',
      '<p>Both work end to end: catalog pieces, AI generation, platform-accurate previews, export, and compliance.</p>',
      '<p><strong>Where to start:</strong> Content Hub / Color blocks and photo slideshows, in this Help Center.</p>',
    ]),
    published: true,
  },
  {
    version: '1.2.0',
    releasedOn: '2026-11-13',
    entryType: 'added',
    title: 'Agent Recipes: 16 plays, the expert crew, and the in-chat Plays rail',
    body: cl([
      '<p>The Research Lab became a crew. Eight experts (research, strategy, copy, lead magnets, email, design, compliance, analyst) run declarative plays end to end: Low-Ticket Launch and Full System, the builder fleet (Bulk Content Engine, Full Funnel Build, Paid Launch System, Email Sequence Build, Repurpose Engine, Launch Week), and the deep research set — Influencer Panel, Comment Mining Sweep, Cross-Channel Sweep, Reddit Rabbit Hole, Video Deep Dive, and The Audience Mosaic.</p>',
      '<p>Deep plays dive multiple influencers, rank posts by real engagement, and mine the comments under the winners across X, TikTok, Instagram, Reddit, and YouTube, with cited web passes on LinkedIn and Facebook. Gates pause for your approval before anything builds downstream. Runs work in the background with live step progress in /admin/recipes or the Plays rail inside the research chat, and the Watch weekly toggle re-runs a play every week.</p>',
      '<p><strong>Where to start:</strong> Planning / Agent Recipes, in this Help Center.</p>',
    ]),
    published: true,
  },
  {
    version: '1.3.0',
    releasedOn: '2026-11-18',
    entryType: 'added',
    title: 'Agent Skills, run sharing, and Mission Control',
    body: cl([
      '<p>The crew learned new tricks and got a home screen. Agent Skills (/admin/skills) are declarative HTTP tools — an allowlisted URL template with declared inputs and secrets that only ever resolve in headers — that any expert or play can call. Drafts save imperfect; activation requires a clean validation, and a 5-failure breaker auto-pauses a dead endpoint before it burns the daily call budget.</p>',
      '<p>Recipe runs can now be shared as read-only public links (/share/run/<token>), the chat live-follows a running play step by step with the crew labeled on every turn, and per-call cost + citation tracking lands fleet-wide.</p>',
      '<p>Mission Control moved onto /admin: gates waiting on you, today\'s fleet spend, the job lane, active watches, and who is working on what, refreshed live. /admin/gates is the phone-first approve-or-cancel screen, and the new Command Palette jumps anywhere from the keyboard.</p>',
    ]),
    published: true,
  },
  {
    version: '1.7.0',
    releasedOn: '2026-11-22',
    entryType: 'added',
    title: 'Reel Studio v2: the Director, the Cutdown Agent, and the loop',
    body: cl([
      '<p>The cutting room got its crew. The Director tab is a chat that EDITS: "tighten the middle scenes" actually trims your timeline in front of you, with every action listed. The Cutdown Agent turns one long video into self-contained reels — transcribe, pick the segments that stand alone, true-cut them with the ffmpeg worker, one named reel per segment in your list.</p>',
      '<p>And the loop: batch-compose every reel (unchanged timelines reuse the cache and never re-render), record impressions and clicks per variant, and the system names the winner. Run the loop and last week\'s winner becomes three descendant drafts for this week. The system learns your audience.</p>',
      '<p><strong>Where to start:</strong> Director tab → "Tighten the middle scenes". Loop tab → Compose batch.</p>',
    ]),
    published: true,
  },
  {
    version: '1.6.0',
    releasedOn: '2026-11-21',
    entryType: 'added',
    title: 'Reel Studio v2: true split, karaoke captions, the timeline grows up',

    body: cl([
      '<p>The cutting room became an editor. Press S at the playhead and a scene splits into TWO — the second half is a real in-point cut done by our own ffmpeg worker (the thing the compose backend could never do), hosted back in storage in seconds.</p>',
      '<p>And captions: hit CC on any scene and Whisper transcribes it into word-timed karaoke that plays live on the stage, current word lit in brass. Word timings save with the reel — transcribe once, captioned forever.</p>',
      '<p>Plus the invisible upgrades: timeline zoom (up to 8x for sub-second cutting), clip-boundary notches on the ruler, arrow-key seeking, a draggable audio bed track, automatic audio syncing in the preview, and stage settings that survive reloads.</p>',
      '<p><strong>Where to start:</strong> open a reel, press S in the middle of a scene, then hit CC.</p>',
    ]),
    published: true,
  },
  {
    version: '1.5.0',
    releasedOn: '2026-11-20',
    entryType: 'added',
    title: 'Reel Studio: the editable last mile for video',

    body: cl([
      '<p>The video pipeline got its cutting room. Reel Studio (/admin/reel-studio) stitches any clips into a final MP4: pull in Seedance renders by URL or upload your own footage (talking head included), reorder shots, trim tails, lay a voiceover over the cut exactly where it should start, and compose.</p>',
      '<p>The crew rides along: the Story Agent and Shot Director suggest b-roll for the reel you are cutting, with each shot one click away from a Seedance prompt you can render upstream and drop back onto the timeline.</p>',
      '<p><strong>Where to start:</strong> Content Hub area / Reel Studio. Create a reel, add two clips, and compose.</p>',
    ]),
    published: true,
  },
  {
    version: '1.8.0',
    releasedOn: '2026-12-02',
    entryType: 'added',
    title: 'Media Library and the Thumbnail Lab',
    body: cl([
      '<p>Every asset the app touches now lives in one searchable place. The Media Library (/admin/media-library) collects uploads, Content Hub renders, reel composites, and Thumbnail Lab exports with provenance and tags — folder tree, search, tag filters, and a detail panel to tag, file, copy, or delete anything. AI prompts can finally use prior media as context.</p>',
      '<p>The Thumbnail Lab builds per-variant thumbnails with the same text overlay system as the Content Hub image studio: pick a video frame or a library image, stamp the hook with any of seven text style templates, and drag the block anywhere. AI can generate a fresh background or edit one from the library with style references, in 16:9 for feed or 9:16 for video.</p>',
      '<p>The Scoreboard got tighter too: every variant row now opens the Thumbnail Lab in one click, and the schedule sheet shows the exact platform mock the Publish view renders while you edit the post.</p>',
      '<p><strong>Where to start:</strong> open a variant on the Scoreboard and hit <strong>thumb</strong> — or browse /admin/media-library.</p>',
    ]),
    published: true,
  },
  {
    version: '1.4.0',
    releasedOn: '2026-11-19',
    entryType: 'added',
    title: '1:1 Personalization: every lead gets their own page',

    body: cl([
      '<p>One funnel now serves a different page to every lead. A signed link from your email (?pp=) tells the funnel who is visiting, and the page renders copy written for them — headline, benefits, problem scene, CTA, checkout — merged server-side before render, so there is no flicker and nothing sensitive in the URL. Price, Stripe ids, and links can never be touched by the AI: the merge is copy-only by construction.</p>',
      '<p>Per funnel in /admin/personalization: overlay mode personalizes signed-link visitors while everyone else sees the generic page; gated mode hides the offer from everyone without a valid key (competitors get a polite decoy). Payloads generate automatically at opt-in and can be regenerated or reviewed per lead, with the AI\'s intent read on each one.</p>',
      '<p>Bonus: per-recipient email images. Embed one signed image URL in your ESP and every opener sees their own first name rendered in the creative, generated at open time and cached at the edge.</p>',
      '<p><strong>Where to start:</strong> set a funnel to overlay in /admin/personalization, generate, mint a link, and put it in your next send.</p>',
    ]),
    published: true,
  },
  {
    version: '1.9.0',
    releasedOn: '2026-08-04',
    entryType: 'added',
    title: 'Remotion caption rendering: preview IS the export',

    body: cl([
      '<p>Captions now render EXACTLY as they preview — same words, same timings, same animations, same styles. The editor\'s Remotion Player and the Railway render worker use the SAME ReelComposition + CaptionLayer + buildRenderPlan, so what you see IS what exports. No more "the captions look different in the MP4."</p>',
      '<p>The old path had two caption renderers that never matched: a browser preview with CSS karaoke (word-timed highlight, scale pops, blur-in, elastic squash, glitch, box-grow highlights, gradient fills, power words) and an ffmpeg burn that could only draw flat text. Now ONE composition serves both — the preview component and the render component are literally the same component.</p>',
      '<p>Every caption feature renders identically: word-timed karaoke, per-word scale pops, blur-in, elastic squash, glitch, box-grow highlights, gradient fills, power words, emoji, custom fonts, stroke + shadow, drag-to-move position, multi-row captions, and Ken-Burns/pan/zoom motion per clip.</p>',
      '<p>The render worker is a persistent Docker container on Railway (Node + Chromium + ffmpeg + Remotion). The Next.js app POSTs a RenderPlan to it; the worker renders the MP4 and uploads it to Supabase storage. No IAM, no S3 serve URLs, no Lambda function names.</p>',
      '<p><strong>Where to start:</strong> open /admin/reel-studio, pick a reel with clips + captions, and the stage shows the Remotion Player (the "Remotion" toggle is active by default). Hit Render video in the Post tab — the MP4 matches the preview exactly.</p>',
    ]),
    published: true,
  },
  {
    version: '2.0.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Caption transform box: drag to move, corners to resize',
    body: cl([
      '<p>Captions on the Reel Studio stage now have a real transform box. Drag anywhere inside it to move the captions (it travels with your pointer, snaps to centre and thirds, arrow keys nudge), and pull any of the four corner handles to grow or shrink the text. It works identically on the true Remotion preview and the Edit canvas, and it writes the same xPct / positionPct / sizePx the render plan reads — so what you drag IS what burns into the MP4.</p>',
      '<p>The box also hugs the caption text at any size: it derives its width and height from the caption block itself (86% of the frame, one line per caption row, font scaled the same way the renderer scales it) instead of sitting at a fixed padding, and it saves once when you release — no network chatter mid-drag.</p>',
      '<p>Also in this round: the Captions tab\'s subtitle word list keeps a comfortable minimum height and takes the largest share of the panel, so editing words no longer means scrolling a two-line sliver.</p>',
      '<p><strong>Where to start:</strong> open a reel with captions in /admin/reel-studio and drag the dashed box on the stage. Full guide: Help Center / Reel Studio / Move and resize captions with the transform box.</p>',
    ]),
    published: true,
  },
  {
    version: '2.1.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Ghost fade, karaoke fill, per-word styling, and image fly-ins',
    body: cl([
      '<p>The caption engine grew up. Five new presets — Ghost (each page of captions dissolves in and out smoothly), Floater (the block bobs gently), Fill Sweep (the spoken word fills with color left to right, glued to the audio), Sign On (neon sign flicker), and Cascade (letters type in one at a time) — and every one of the 17 word animations now renders frame-exact in the MP4, not just in the preview.</p>',
      '<p>Words can now be styled individually: mark any spoken word with its own animation, color, scale, or per-letter cascade — the rest of the line keeps the preset. And image fly-ins: cue an image from the Media Library to fly in the moment a specific word is said — click cue word, click the word, pick the image, or hit auto and let the strong words match your library.</p>',
      '<p><strong>Where to start:</strong> Captions tab in /admin/reel-studio — pick Fill Sweep from the gallery, then cue word → click a word.</p>',
    ]),
    published: true,
  },
  {
    version: '2.2.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Fly-in images: upload or AI-generate, style and keyframe every cue, plus the Cue Autopilot play',
    body: cl([
      '<p>Image fly-ins grew their full toolchain. The cue picker now takes an upload straight from your machine or an AI prompt — either way the picture lands in the Media Library AND attaches to the word in one step, so it is reusable the next time a beat calls for it.</p>',
      '<p>Every attached cue carries its own look and move: size, position, corner rounding, shadow, border — plus the same keyframed motion tracks scenes have (zoom, pan, rotate, sampled over the cue\'s own window). Leave everything unset and you get the house card: rise, scale, fade.</p>',
      '<p>And the Cue Autopilot: one click packages the reel\'s transcript into the Reel Cue Autopilot play. The agent proposes cue beats (word + image prompt + style hint), you approve or edit the list at the gate, and only then does it attach — matching your Media Library first (free before paid) and generating just the missing images. The run shows in the Plays rail with full cost tracking, like every other play.</p>',
      '<p><strong>Where to start:</strong> Captions tab in /admin/reel-studio — cue word → click a word → upload, type a prompt, or hit autopilot.</p>',
    ]),
    published: true,
  },
  {
    version: '2.3.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Fly-ins you can grab: drag to place, set the time on screen, and let them float',
    body: cl([
      '<p>Open a fly-in\'s style editor (the ⚙ on its chip) and a dashed box appears on the preview — drag it anywhere (arrow keys nudge), pull the right edge to scale, and the number it writes is the number the MP4 burns. One-click chips snap the card above or below the caption block, and it works identically on the true Remotion preview and the Edit canvas.</p>',
      '<p>Two new dials in the same editor: <strong>on screen</strong> — how long the image holds after its word ends (0.3–6s, with the total shown) — and <strong>feel</strong>: float (a gentle bob) or wiggle (a soft sway), an ambient motion that rides on top of the entrance and any keyframed track, easing in and out with the cue so it never pops. The window still keys off the spoken word, so a trim or split re-times everything honestly.</p>',
      '<p><strong>Where to start:</strong> Captions tab in /admin/reel-studio — attach a fly-in, hit ⚙, and drag the violet box on the stage.</p>',
    ]),
    published: true,
  },
  {
    version: '2.4.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Word FX, caption feel, and sounds: glow, shine, underline, marker — and SFX on words and fly-ins',
    body: cl([
      '<p>Captions can now move as a block and shine by the word. <strong>Block feel</strong> (still / float / wiggle) sets the whole caption block\'s ambient motion. <strong>Word FX</strong> picks words in the subtitle list and applies an effect to every one of them: glow (a pulsing halo), gradient, shine (a light sweep), pulse (a breathing beat), underline (a rule that draws itself), or marker (a highlighter swipe) — each with its own color, plus a per-word bob or sway. Everything is frame math, so the preview and the MP4 agree.</p>',
      '<p>And sound: attach a one-shot sound to a fly-in (a whoosh as it lands) or to any word (a hit as it is spoken). Pick from your Media Library\'s audio or upload one — it lands in the library tagged sfx, ready for the next beat. Sounds render as real audio at the exact frame, preview included.</p>',
      '<p>The above/below snap chips also got honest math: they now seat the image\'s edge against the caption block\'s edge, computed from the block\'s real height (rows × size) and the image\'s real shape — no more landing on top of the text.</p>',
      '<p><strong>Where to start:</strong> Captions tab in /admin/reel-studio — the Word FX panel under the fly-ins panel. fx word → click words → apply.</p>',
    ]),
    published: true,
  },
  {
    version: '2.5.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Word FX settings: per-word fonts, an intensity dial, and five more effects',
    body: cl([
      '<p>The Word FX panel got its own settings, the same way the image fly-ins have theirs (the fly-in settings are still exactly where they were — the ⚙ on an attached cue\'s chip opens size, position, corner, border, shadow, on-screen time, feel, sfx, and motion). With words picked in fx mode, an <strong>amount</strong> slider (0.2–3×) tunes every effect at once: glow radius, pulse amplitude, marker opacity, underline and strike thickness, the shine band, the jelly squash.</p>',
      '<p>And the headline: a <strong>font</strong> per word. Pick words, pick a family (Anton, Bebas, Poppins, Georgia, Courier Prime…) and those words render in it — in the preview AND the MP4, because the render plan now ships every marked family in its font list for the worker to load.</p>',
      '<p>Five new effects join the six: tilt (a static lean), outline (a colored stroke), strike (a line that wipes through), blink (a steady flash), and jelly (a continuous squash-and-stretch). All frame math, so preview and export agree by construction.</p>',
      '<p><strong>Where to start:</strong> Captions tab — fx word → click words → amount, font, or one of the eleven effects.</p>',
    ]),
    published: true,
  },
  {
    version: '2.6.0',
    releasedOn: '2026-08-05',
    entryType: 'added',
    title: 'Word FX per word: individual scope, hover readouts, density and a second color — and fly-in settings that stay on screen',
    body: cl([
      '<p>The Word FX panel now has a <strong>scope</strong> toggle. <em>All picked</em> is the bulk editor you know: settings write to every word you picked. <em>One word</em> isolates a single word — the controls load THAT word\'s current effects and edit only it. And hovering any word in the subtitle list now reads out exactly what it carries ("glow · fx #ffd400 → #ff6b6b · ×2 · Anton · sfx ✓"), picked or not.</p>',
      '<p>Two new settings dials, per the ask: <strong>density</strong> (0.2–3×) — extra glow halo layers, more shine sweeps, faster pulse/blink/jelly — and a <strong>second color</strong>: the gradient\'s end and the shine band\'s light. Amount owns SIZE, density owns HOW MUCH of it happens.</p>',
      '<p>And the fly-in settings stopped hiding: the style editor is now always on screen when a cue exists — the ⚙ on a cue chip just picks WHICH cue it edits. Size, position, corner, border, shadow, on-screen time, feel, sfx, motion — permanently visible, no toggle to lose.</p>',
      '<p><strong>Where to start:</strong> Captions tab — fx word → pick the scope, click a word, and its settings are already showing.</p>',
    ]),
    published: true,
  },
  {
    version: '2.7.0',
    releasedOn: '2026-08-06',
    entryType: 'fixed',
    title: 'Over/under text layers, the always-visible drag box, and a real render fix',
    body: cl([
      '<p>Above/below is now a true LAYER, not a position: <strong>↑ over text</strong> paints the fly-in image ON TOP of the caption text, <strong>↓ under text</strong> paints it under (the house default) — frame-exact in the preview and the MP4. The chips still snap the box to the right spot as a convenience.</p>',
      '<p>And the drag box on the preview canvas is always visible now, same rule as the style editor — grab it to place the fly-in, pull the right edge to scale, no ⚙ hunting.</p>',
      '<p><strong>Also fixed:</strong> renders that reported "the render worker restarted and lost this job" on every single attempt. The worker never restarted — the job-poller endpoint was dropped by an earlier file repair, so every render ran fine and its progress poll 404\'d. The endpoint is restored (with a "do not remove" note in the code), verified live against the worker.</p>',
      '<p><strong>Where to start:</strong> Captions tab — attach a fly-in and try ↑ over text / ↓ under text on a reel with captions on screen.</p>',
    ]),
    published: true,
  },
  {
    version: '2.8.0',
    releasedOn: '2026-08-07',
    entryType: 'added',
    title: 'AI Clone, step 1: the Clone tab and the character-sheet foundry',
    body: cl([
      '<p>The Clipping Studio gains a <strong>Clone</strong> tab — step 1 of the AI Clone video wizard. A clone is a saved cast member: a name, reference photos, an ElevenLabs voice (pick from your account or paste a clone id), and a locked <strong>look bible</strong> — wardrobe, backdrop, lighting, lens — one string every downstream prompt quotes verbatim, so the character never drifts.</p>',
      '<p>No photos? The <strong>character-sheet foundry</strong> forges one with GPT Image 2: a 2×2 turnaround grid (front / three-quarter / profile / close-up) plus an expression strip (neutral, excited, serious), with an optional full-body cell for walking b-roll. One image call, <em>once per character — not per video</em> (~$0.08, the cheapest consistency lever in the stack). The sheet lands in the Media Library tagged <code>character-sheet</code>, reusable across reels.</p>',
      '<p>The clone saves into the reel itself as the plan manifest (beats, storyboard gate, and cost readouts build on it in the next steps), and the full 6-step wizard shows on the tab so you always know where this is going.</p>',
      '<p><strong>Where to start:</strong> Clipping Studio → Clone tab → describe your person, forge the sheet, save the clone.</p>',
    ]),
    published: true,
  },
  {
    version: '2.9.0',
    releasedOn: '2026-08-07',
    entryType: 'added',
    title: 'AI Clone, step 2: the script writer with per-line voice programming',
    body: cl([
      '<p>The Clone tab\'s step 2 is live. Pick the <strong>video type</strong> — Hook ad, UGC testimonial, VSL, tutorial, or announcement — and it carries its proven <strong>framework</strong> with it (PAS, AIDA, hook-story-offer, or the Mindshift VSL structure). Type the topic and the script writer produces the beats: one spoken line per beat on the honest 5/10/15-second grid (never more words than the seconds can hold), with optional b-roll cutaway beats that name your character so they show up INSIDE the footage.</p>',
      '<p>Every line carries its <strong>voice programming</strong> — the director\'s notes for the read: pace (slow / natural / fast), energy (low / medium / high), the emphasis words that get the stress, and where the pause lands. You can see it on each beat\'s chip, edit any line in place, or drop a beat — and a re-write regenerates the whole pass while your clone stays locked.</p>',
      '<p><strong>Where to start:</strong> Clipping Studio → Clone tab → save a clone, then step 2 → pick a type, write the topic, hit "write the script".</p>',
    ]),
    published: true,
  },
  {
    version: '2.10.0',
    releasedOn: '2026-08-07',
    entryType: 'added',
    title: 'AI Clone, step 3: the storyboard gate with the full cost readout',
    body: cl([
      '<p>The Clone tab\'s <strong>storyboard</strong> is live — the approval gate before a dollar moves. Every beat shows its shot: flip a beat between talking-head and b-roll, re-frame the angle (close / medium / wide), rewrite the b-roll visual, and nudge its seconds on the honest 5/10/15 grid — options shorter than the word count allows are disabled, so the grid never lies. Each beat carries the two <strong>@reference slots</strong>: @1 is always the locked character sheet, @2 is your optional variant (wardrobe change, location still, product-in-hand) picked from the clone\'s refs or any URL.</p>',
      '<p>And the money stays on screen: every beat wears its price chip (voice + video), the <strong>Seedance 2.0 ↔ 2.5 hero</strong> toggle shows the plan delta live (pin a single b-roll beat to 2.5 and only that beat moves), and the totals box lines out voice, video, runtime, and the character sheet — charged <em>once per character, never per video</em>. Nothing spends without a number on screen: the approve button carries the total, approval stamps the gate, and any edit re-opens it. Generation (step 5) reads this gate.</p>',
      '<p><strong>Where to start:</strong> Clipping Studio → Clone tab → write a script, then scroll to the storyboard — set the shots, check the total, approve the gate.</p>',
    ]),
    published: true,
  },
  {
    version: '2.11.0',
    releasedOn: '2026-08-07',
    entryType: 'added',
    title: 'AI Clone, steps 5–6: per-beat generation and one-click assemble',
    body: cl([
      '<p>The Clone wizard generates now. With the storyboard gate stamped, step 5 renders each beat: <strong>voice first</strong> — ElevenLabs reads every line with THAT beat\'s voice programming (one call per beat = per-beat emotion) — then the video: talking-head beats go to the muapi OmniHuman-class avatar model fed @1 (the locked character sheet) plus the beat\'s audio, and b-roll beats go to Seedance with the @reference images riding so the same character shows up INSIDE the footage. Every clip re-hosts to our storage before it lands on the manifest (provider URLs expire), and every beat carries a watch link the second it\'s done.</p>',
      '<p>Run it per beat or hit <strong>generate all</strong> — the pass works the manifest in order, a failed beat stamps itself and waits for a retry (it re-enters at the step that failed, never re-buying the voice). And step 6: <strong>assemble</strong> drops every generated beat onto the timeline as scenes, in order — captions, fly-ins, SFX, keyframes, and the Remotion render all work on clone videos for free.</p>',
      '<p><strong>Where to start:</strong> Clipping Studio → Clone tab → approve the storyboard, then step 5 → generate all.</p>',
    ]),
    published: true,
  },
  {
    version: '2.12.0',
    releasedOn: '2026-08-07',
    entryType: 'added',
    title: 'AI Clone, the finale: extend + re-roll + the Content Hub cast',
    body: cl([
      '<p>The Clone wizard is complete. <strong>Extend</strong> appends a beat to the chain — talking head or b-roll — and when the previous beat is rendered, the new one continues from its LAST FRAME (the generate route grabs it server-side and Seedance starts from it), so long chains and VSLs hold visual continuity instead of hard-cutting between beats. Appending re-opens the gate, because the storyboard changed. <strong>Re-roll</strong> clears one beat\'s outputs back to planned and re-renders just that beat — the plan is untouched, so the gate stays stamped and you never re-buy the voice of the beats you kept.</p>',
      '<p>And the cast goes everywhere: every forged character sheet now appears in the Content Hub\'s storyboard panel as <strong>the cast</strong> — one click adds it as the board\'s @reference, and the Reel Director\'s Seedance renders carry it as an omni-reference automatically. One sheet, both surfaces: the same character shows up inside the footage, not just between cuts.</p>',
      '<p><strong>Where to start:</strong> Clone tab → the dashed extend box under the script; Content Hub → a post\'s Storyboard panel → the cast row.</p>',
    ]),
    published: true,
  },
  {
    version: '2.13.0',
    releasedOn: '2026-08-07',
    entryType: 'improved',
    title: 'AI Clone: the clone library + AI fill, and a stepper that knows where you are',
    body: cl([
      '<p>Step 1 of the Clone wizard got its helpers. <strong>The clone library</strong>: every clone you\'ve built — on any reel — is now pickable from a dropdown at the top of the clone card. Pick one and the whole form fills (name, look bible, voice, refs, sheet); save casts an independent copy on this reel. No more rebuilding the same character per reel.</p>',
      '<p><strong>AI fill</strong>: type one loose sentence about the person ("woman in her 30s, athletic, confident, gym energy") and hit the ✨ button — the name, the foundry-ready description, and all four look-bible fields fill in, ready to tweak and forge. And the wizard stepper now shows the stage you\'re actually ON — finished stages check off, the current one glows — instead of sitting on step 1 forever.</p>',
      '<p><strong>Where to start:</strong> Clipping Studio → Clone tab → the library dropdown and the ✨ AI fill button live at the top of the clone card.</p>',
    ]),
    published: true,
  },
  {
    version: '2.14.0',
    releasedOn: '2026-08-07',
    entryType: 'added',
    title: 'AI Twins: the roster page — your cast is a library now',
    body: cl([
      '<p>The Clone wizard got its home. <strong>/admin/ai-twins</strong> is the roster: every twin as a card — face, voice, how many videos it stars in — library-first, no forms in sight. <strong>New twin</strong> opens the creation modal (the only place that form lives: the description + AI fill, the look bible, the voice picker, and the character-sheet foundry). Click a card to edit it; <strong>New video</strong> casts the twin into a fresh reel and drops you into the Clipping Studio with the wizard already open on it.</p>',
      '<p>And the studio\'s Clone tab slimmed down to match: once a reel has its twin, the form collapses behind an "edit twin" toggle — the tab is the twin card, the script, the storyboard, and generation, not a wall of inputs. Twins built inside a working reel show up on the roster too.</p>',
      '<p><strong>Where to start:</strong> Admin sidebar → AI Twins → New twin.</p>',
    ]),
    published: true,
  },
  {
    version: '2.14.1',
    releasedOn: '2026-08-07',
    entryType: 'fixed',
    title: 'Reference-photo uploads, and the burgundy card pass',
    body: cl([
      '<p>Reference photos upload now — no more link-only. Both the AI Twins creation modal and the Clipping Studio\'s clone editor take a photo straight from your machine (it lands in the Media Library, tagged and reusable) alongside the paste-a-URL path.</p>',
      '<p>And the stragglers joined the house style: the Personalization, Experts, Recipes, Skills, and Media Library pages now wear the same burgundy cards as the rest of /admin — the light-card leftovers are swept.</p>',
    ]),
    published: true,
  },
  {
    version: '2.15.0',
    releasedOn: '2026-08-07',
    entryType: 'added',
    title: 'Sheet styles per video type, a sharper script writer, burgundy cards',
    body: cl([
      '<p>The foundry speaks the video\'s language now. Four sheet styles on the character-sheet foundry (both the AI Twins modal and the studio\'s clone editor): <strong>Cinematic board</strong> — the Netflix production contact sheet: film-grade motivated light, real environments, every panel a distinct frame, black matte spacing — <strong>UGC / organic</strong> — a real person\'s camera roll, never a production — <strong>VSL / authority</strong> — the polished expert press kit — and <strong>Editorial / clean</strong>. Same locked turnaround cells, different art direction.</p>',
      '<p>The script writer leveled up too: hooks must open a loop or name a felt moment, one idea per line, concrete over abstract, written for the ear — and every framework role executes as a JOB (agitate twists a specific cost, proof is a scene or a number, never a claim). And the /admin cards are the proper burgundy tint everywhere, roster included.</p>',
      '<p><strong>Where to start:</strong> AI Twins → New twin → pick a sheet style above the forge button.</p>',
    ]),
    published: true,
  },
];



