import { html, introBox, media, step, callout, table, chip, type SeedArticle } from './helpers';

export const contentHub: SeedArticle[] = [
  {
    slug: 'content-hub-overview',
    title: 'Content Hub basics: catalogs, pieces, and previews',
    category: 'Content Hub',
    excerpt: 'What a content piece is, how the per-platform catalogs are organized, and how to read a live preview before you trust it.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>The Content Hub is where every social post is drafted, reviewed, and exported. It ships with a built-in catalog per platform, and every item in every catalog is a piece: a typed, structured draft that holds its copy, its media plan, and its review state. Learn the piece model once and the rest of the Hub makes sense.</p>`,
      introBox([
        ['What this is', 'The drafting table for all social content'],
        ['Where it lives', 'Admin / Content'],
        ['Core object', 'The piece'],
        ['Platforms', 'Facebook, Instagram, X, TikTok, YouTube, LinkedIn, Pinterest, blog, AEO, email, ads'],
      ]),
      `<h2>Platforms and formats</h2>`,
      `<p>Each platform has its own catalog and its own format set, and each format carries the platform's hard limits: aspect ratios, character caps, and where the hook has to land. The Hub enforces these at preview time, so a draft never looks right here and wrong on the platform.</p>`,
      table(['Platform', 'Formats you will use most'], [
        ['Instagram / Facebook', 'Feed, reel, carousel, story'],
        ['TikTok / YouTube Shorts', 'Vertical reel, hook in the first two seconds'],
        ['YouTube', 'Long (16:9, chaptered) and reel (9:16 Shorts)'],
        ['LinkedIn', 'Feed, carousel (document), article, video'],
        ['Pinterest / blog / AEO / email / ads', 'Their own format sets and limits'],
      ]),
      `<h2>The piece model</h2>`,
      `<p>A piece is the unit everything acts on. It holds:</p>`,
      `<ul>`,
      `<li><strong>The hook and body copy.</strong> The words of the post.</li>`,
      `<li><strong>The media prompt.</strong> The image direction the generators render from.</li>`,
      `<li><strong>Optional slides.</strong> One per frame, for carousels and stories.</li>`,
      `<li><strong>The review state.</strong> Generated images, the picked frame, and the YouTube kit, all per piece.</li>`,
      `</ul>`,
      `<p>Because a piece is structured, the same piece can be previewed, edited by AI, exported, and scheduled without being re-formatted for each step.</p>`,
      `<h2>Read a live preview before you trust it</h2>`,
      step(1, 'Open the piece',
        `<p>Select it in the Hub. The preview renders the piece the way the platform would, not a generic card.</p>`),
      step(2, 'Let multi-frame previews autoplay',
        `<p>Stories, reels, and carousels autoplay: frames advance on a timer with a progress sweep and loop. Watch the whole sequence once. This is how you catch a weak middle frame.</p>`),
      step(3, 'Hover or tap to pause on a frame',
        `<p>Autoplay pauses on hover or focus so you can study one frame. Picking a frame by hand persists that choice for the piece.</p>`),
      step(4, 'Check it against the platform limits',
        `<p>The preview respects the format's character caps and aspect ratios. If something looks cramped or cut off here, it will look worse on the platform. Fix it before scheduling.</p>`),
      media('content-hub-overview', 'video', 'A tour of the Hub: picking a platform, opening a piece, and watching a story preview autoplay belongs here.'),
      callout('info', 'Autoplay is preview-only',
        `<p>The autoplay position is never written to the piece. It exists only to help you review. The frame that ships is the one you explicitly pick.</p>`),
    ),
  },
  {
    slug: 'content-generate-drawer',
    title: 'The Generate drawer: produce a whole batch at once',
    category: 'Content Hub',
    excerpt: 'Step by step: compose a batch, attach context, generate copy and imagery, review each draft, and save winners to the library.',
    sortOrder: 2,
    published: true,
    body: html(
      `<p>The Generate drawer is the volume workflow. Instead of writing one post at a time, you compose a batch, the AI writes the copy for all of it, and each draft can render image variants in one click before anything is saved. This is how you fill a week of the Planner in one sitting.</p>`,
      introBox([
        ['What this is', 'The bulk AI drafting tool'],
        ['Where it lives', 'Content Hub / Generate drawer'],
        ['Output', 'A batch of reviewed drafts, saved to the library'],
        ['Prerequisite', 'The Offer Kit filled in'],
      ]),
      `<h2>Run a batch, step by step</h2>`,
      step(1, 'Compose the batch',
        `<p>Pick the platforms and formats you want, and set the count. Mix formats deliberately: a reel, a carousel, and a few feed posts give you a week that does not feel repetitive.</p>`),
      step(2, 'Attach context sources',
        `<p>Attach the offer first. Add a kit when the batch should push a specific asset (the lead magnet, the community). Add a saved email sequence when posts should echo what the list is reading. Context is re-resolved at generation time, so drafts always reflect the live source.</p>`),
      step(3, 'Generate the copy',
        `<p>The server writes hook-anchored copy per piece, on voice, and inside each platform's hard limits. You get a full batch of drafts in one pass.</p>`),
      step(4, 'Review each draft against its preview',
        `<p>Open a draft, read the hook out loud, and check the preview. Reject the weak ones here. Review is far cheaper than editing a scheduled post.</p>`),
      step(5, 'Render image variants on the keepers',
        `<p>Each kept draft renders one to four image variants from its media prompt in one click, or opens in Image Studio for edits and overlays. Pick the variant that fits before saving.</p>`),
      step(6, 'Save to the library',
        `<p>Draft galleries live locally until you save. On save, the picked images attach to the piece, so they show in the Hub and can be scheduled or exported.</p>`),
      media('content-generate-drawer', 'video', 'A full batch run: compose, attach context, generate, render variants on three drafts, and save belongs here.'),
      `<h2>Get a better batch next time</h2>`,
      `<ul>`,
      `<li><strong>Sharpen the offer promise.</strong> It is the single biggest lever on copy quality.</li>`,
      `<li><strong>Attach one specific context, not five.</strong> A batch with one clear job beats a batch pulling in every direction.</li>`,
      `<li><strong>Feed the winner back.</strong> When a post converts, generate the next batch around its angle.</li>`,
      `</ul>`,
      callout('tip', 'Generate for the week, not the day',
        `<p>One batch of fifteen to twenty drafts, reviewed down to the best seven, is a calmer and higher-quality way to fill the Planner than scrambling for a post each morning.</p>`),
    ),
  },
  {
    slug: 'image-studio-and-edits',
    title: 'Image Studio: generate, edit against references, and place logos',
    category: 'Content Hub',
    excerpt: 'Step by step: generate a base image, edit it toward reference images, and add a logo the controlled way.',
    sortOrder: 3,
    published: true,
    body: html(
      `<p>Image Studio is the image workbench: generate from a prompt, then edit the result against reference images until it is right. It opens from any piece, funnel media slot, or kit image field, and everything it produces is hosted and reusable.</p>`,
      introBox([
        ['What this is', 'The image generation and editing workbench'],
        ['Opens from', 'Any piece, funnel media slot, or kit image field'],
        ['Two moves', 'Generate a base, then edit against references'],
        ['Reference limit', 'Up to four reference images per edit'],
      ]),
      `<h2>The two moves</h2>`,
      table(['Move', 'What it does', 'When you use it'], [
        ['Base generation', 'Creates a clean image from a prompt in the suite style: no baked-in logos, no text, on palette.', 'Starting a brand-new visual'],
        ['Reference edit', 'Edits a seed image toward up to four reference images plus an instruction.', 'Matching a character, product, environment, or logo'],
      ]),
      `<h2>Generate and refine, step by step</h2>`,
      step(1, 'Generate the base clean',
        `<p>Start from the piece's media prompt or write a fresh one. The base style deliberately excludes text and logos so overlays and logo placement stay controllable later. Do not fight this; it is what keeps your brand mark accurate.</p>`),
      step(2, 'Attach references for anything that must be exact',
        `<p>Attach a reference for the things a model cannot guess: your face or character, the actual product, a specific room, the logo. Up to four per edit. The seed is edited toward these.</p>`),
      step(3, 'Use an edit preset for common jobs',
        `<p>Presets are one-tap instructions. The <em>Add logo</em> preset tells the model to incorporate the mark from the attached logo reference tastefully, keep edges clean, and never invent a different logo.</p>`),
      step(4, 'Re-run with a clean reference when an edit drifts',
        `<p>If a logo or product edit drifts, do not write a longer instruction. Re-attach the clean reference and re-run the preset. A clean reference beats a clever prompt every time.</p>`),
      `<h2>Logos, specifically</h2>`,
      `<p>Logos only ever appear through the edit preset with a logo reference attached. Base prompts forbid them, so you never get a hallucinated mark in a scene, and you never ship a post missing the mark because the model felt like it. This two-rule system is deliberate: total control, zero surprises.</p>`,
      media('image-studio-and-edits', 'image', 'A before-and-after of a reference edit with the logo preset belongs here.'),
      callout('warn', 'Never ask the base model to invent your logo',
        `<p>A generated logo is always slightly wrong, and a slightly wrong logo is worse than none. Generate the scene clean, then place the real mark with the edit preset.</p>`),
    ),
  },
  {
    slug: 'text-overlay-editor',
    title: 'Text overlays: put words on an image the exact way',
    category: 'Content Hub',
    excerpt: 'Step by step: add a text block, edit it on the canvas, drag and resize it, and burn the finished overlay onto the image.',
    sortOrder: 4,
    published: true,
    body: html(
      `<p>The overlay system puts text on images without opening a design tool. An overlay is a set of text blocks with position, size, anchor, and style, edited directly on the canvas and burned onto the hosted image when you save. This is how hooks and headlines actually land on your visuals.</p>`,
      introBox([
        ['What this is', 'The on-canvas text editor for images'],
        ['Opens from', 'Image Studio, on any image'],
        ['The result', 'A hosted burn: the image with the text baked in'],
        ['The rule', 'Words go on with overlays, never in the image prompt'],
      ]),
      `<h2>Add and place text, step by step</h2>`,
      step(1, 'Add a text block',
        `<p>Start with the image you generated clean. Add a block for each distinct piece of text: the hook line, a subline, a small tag.</p>`),
      step(2, 'Edit the text in place',
        `<p>Click a block on the canvas to edit it right there, not in a side field. You see the words exactly as they will land.</p>`),
      step(3, 'Drag it and resize it on the canvas',
        `<p>Move blocks freely and resize with the on-canvas handles. The sticky preview is exact: what you see while dragging is what the burn produces. Position is anchor-based, so the same overlay lands correctly across aspect ratios.</p>`),
      step(4, 'Save to burn it onto the image',
        `<p>Saving burns the overlay onto a hosted copy of the image. The original stays in the piece's gallery alongside the burn, so nothing is clobbered. The burn is hosted, so its URL can post to any platform or slot.</p>`),
      `<h2>When to overlay versus when to prompt</h2>`,
      table(['Need', 'Use', 'Why'], [
        ['Words on the image', 'Overlay editor', 'The model is bad at spelling; the overlay is exact'],
        ['A scene, product, or background', 'Image prompt', 'That is what the image model is for'],
        ['A logo', 'The logo edit preset, not text', 'A logo is an image, not text'],
      ]),
      media('text-overlay-editor', 'video', 'Adding a two-line hook to a generated image, repositioning it, and saving the burn belongs here.'),
      callout('warn', 'Never bake text in through the image prompt',
        `<p>Asking the image model to render words gives you misspelled, warped text. Generate the scene clean, then overlay the words. This is the single most important habit in the image workflow.</p>`),
    ),
  },
  {
    slug: 'frame-packs-and-carousels',
    title: 'Frame packs: build a coherent carousel or story',
    category: 'Content Hub',
    excerpt: 'Step by step: write the slides, generate the pack as one unit, overlay per frame, and check the read with autoplay.',
    sortOrder: 5,
    published: true,
    body: html(
      `<p>A frame pack is a set of images generated as one unit for a multi-frame format: a carousel, a story sequence, or a reel's key frames. The point is coherence: one style, one palette, one character carried across every frame, so the sequence reads as a single designed thing instead of five unrelated images.</p>`,
      introBox([
        ['What this is', 'Multi-frame image generation as one unit'],
        ['Use it for', 'Carousels, story sequences, reel key frames'],
        ['The goal', 'One coherent style across every frame'],
        ['Words go on', 'With the overlay editor, per frame'],
      ]),
      `<h2>Build a pack, step by step</h2>`,
      step(1, 'Write or generate the slides so each earns its frame',
        `<p>The pack generates one frame per slide, so weak slides make weak frames. Each slide should say one thing and set up the next. Five to seven slides is the sweet spot for a carousel.</p>`),
      step(2, 'Generate the pack',
        `<p>The pack model takes the slides and generates a frame per slide under a shared style directive. Every frame arrives in the piece's review gallery, in order. Frame prompts forbid baked-in text and logos, same as base generation, so the scenes come out clean.</p>`),
      step(3, 'Reject and regenerate the frames that break the set',
        `<p>Scan the contact sheet for the one frame that does not match the others. Regenerate just that frame rather than the whole pack.</p>`),
      step(4, 'Overlay the words per frame',
        `<p>Where a slide needs its words on the image, use the overlay editor on that frame. This is what keeps the text crisp and the spelling perfect across the whole sequence.</p>`),
      step(5, 'Check the read with autoplay',
        `<p>Preview the piece and let it autoplay. Watch it as a sequence, not as individual frames. The middle frame that reads fine on its own but stalls the sequence is the one to fix.</p>`),
      media('frame-packs-and-carousels', 'image', 'A contact sheet of one five-frame pack showing the shared style belongs here.'),
      callout('tip', 'Design the first and last frame hardest',
        `<p>The first frame wins the swipe. The last frame carries the call to action. If you only polish two frames, make them those two.</p>`),
    ),
  },
  {
    slug: 'storyboard-variation-lab',
    title: 'Variation Lab: one image, every aspect ratio',
    category: 'Content Hub',
    excerpt: 'Step by step: take one approved image and smart-resize it into every size you need without amputating the subject.',
    sortOrder: 6,
    published: true,
    body: html(
      `<p>The Variation Lab takes one approved image and produces the same image at every aspect ratio the suite needs (16:9, 9:16, 1:1, 4:5) using smart resize, so the subject survives the change instead of being amputated by a center crop. It is also where storyboard frames for video are prepared.</p>`,
      introBox([
        ['What this is', 'Smart-resize and variation generation'],
        ['Solves', 'One image needed at many aspect ratios'],
        ['Also produces', 'Storyboard frames for the video pipeline'],
        ['Input', 'One approved image'],
      ]),
      `<h2>Why smart resize instead of crop</h2>`,
      `<p>A center crop of a 16:9 scene down to 9:16 deletes the subject's head or the product. Smart resize recomposes the image for the new frame, keeping the subject intact. The Variation Lab is where you generate those recompositions, compare them side by side, and keep the ones that work.</p>`,
      `<h2>Use it, step by step</h2>`,
      step(1, 'Start from an approved image',
        `<p>Pick the image that already works. The Lab's job is to adapt it, not to fix a weak source. Garbage in, garbage resized.</p>`),
      step(2, 'Generate the ratios you need',
        `<p>Produce the versions for the placements you are actually using: 9:16 for stories and reels, 1:1 or 4:5 for feed, 16:9 for YouTube or wide slots.</p>`),
      step(3, 'Compare and keep the good recompositions',
        `<p>Lay the versions side by side and keep the ones where the subject reads clearly. Discard the rest. A bad recomposition is worse than not posting that ratio.</p>`),
      step(4, 'For video, approve storyboard frames here first',
        `<p>Storyboard frames come from the same machinery. Approve the frames in the Lab before sending anything to render. Approving a frame is far cheaper than re-rendering a clip.</p>`),
      media('storyboard-variation-lab', 'image', 'One source image shown at four aspect ratios with the subject intact belongs here.'),
      callout('tip', 'Resize once, reuse everywhere',
        `<p>One strong image, smart-resized into four ratios, fills four placements from a single generation. This is the cheapest way to look consistent across platforms.</p>`),
    ),
  },
  {
    slug: 'video-scripts-and-seedance',
    title: 'Video: script, storyboard, then render with Seedance',
    category: 'Content Hub',
    excerpt: 'Step by step through the three-stage video pipeline: write the scene script, approve storyboard frames, then render the clip.',
    sortOrder: 7,
    published: true,
    body: html(
      `<p>The video pipeline has three stages, each its own tool: the script, the storyboard, and the render. Do them in order. Skipping ahead is how you burn render credits on a video whose middle beat was never going to work.</p>`,
      introBox([
        ['What this is', 'The end-to-end video pipeline'],
        ['The stages', '1. Script, 2. Storyboard, 3. Render'],
        ['Render engine', 'Seedance'],
        ['Golden rule', 'Never render before approving frames'],
      ]),
      `<h2>Stage 1: write the script</h2>`,
      step(1, 'Generate the scene script from a piece',
        `<p>The script generator turns a piece into a second-by-second scene plan: timestamp, on-screen text, voiceover, and visual direction. For YouTube long-form it produces chaptered beats. For Shorts and reels it front-loads the hook into the first two seconds.</p>`),
      step(2, 'Edit the beats, not just the words',
        `<p>The script is structured data, one row per beat. Read it as a plan: does each beat earn its seconds, and does the hook land before the viewer can swipe? Fix the plan here, in text, where it is free.</p>`),
      `<h2>Stage 2: approve the storyboard</h2>`,
      step(3, 'Generate one frame per beat',
        `<p>The storyboard stage reads the script and produces one image per beat, using the frame pack machinery so the style stays coherent across the sequence.</p>`),
      step(4, 'Reject and regenerate frames, not clips',
        `<p>This is the cheapest place to fix a video. Scan the frames, reject the ones that miss, and regenerate them here. A bad frame approved now becomes a bad clip you paid to render.</p>`),
      `<h2>Stage 3: render with Seedance</h2>`,
      step(5, 'Pick a model for quality versus speed',
        `<p>The render step has a model selector. Use the fast model while you are iterating and the quality model for the final take.</p>`),
      step(6, 'Render the hook beat first',
        `<p>Render the first beat and watch it before rendering the rest. If the hook does not move well, no later beat will save the clip. Once the hook reads right, render the full sequence with per-clip progress.</p>`),
      media('video-scripts-and-seedance', 'video', 'Script to storyboard to one rendered clip, end to end, belongs here.'),
      callout('warn', 'The expensive mistake',
        `<p>Rendering a full sequence before approving the storyboard. The pipeline is designed so every problem is caught in text or in a still frame, both of which are free to redo. Render last.</p>`),
    ),
  },
  {
    slug: 'compliance-agent',
    title: 'The compliance agent: clear a draft before you ship it',
    category: 'Content Hub',
    excerpt: 'What the voice and platform checks catch, and how to run and clear a compliance pass on any batch.',
    sortOrder: 8,
    published: true,
    body: html(
      `<p>The compliance agent is the automated reviewer that runs over generated copy before you ship it. It checks two different things and reports them separately: whether the copy is on brand voice, and whether it fits the platform's hard limits. A green compliance state is the definition of "ready to schedule".</p>`,
      introBox([
        ['What this is', 'The automated reviewer for generated copy'],
        ['Two checks', 'Brand voice and platform hard limits'],
        ['Runs in', 'The Generate drawer review, or on demand'],
        ['Green means', 'Ready to export or schedule'],
      ]),
      `<h2>What each check catches</h2>`,
      table(['Check', 'What it enforces', 'Pass or fail'], [
        ['Brand voice', 'No em dashes, no en dashes, no NO-list words, periods over exclamation points, the soft $7 call to action.', 'Stylistic; fixable in one pass'],
        ['Platform limits', 'Character caps, hashtag counts, aspect ratios, hook timing for vertical video.', 'Hard pass/fail; must pass to ship'],
      ]),
      `<h2>Run and clear a pass, step by step</h2>`,
      step(1, 'Generate or open the batch in review',
        `<p>The Generate drawer runs compliance as part of review. You can also run it on demand over a catalog. Either way, each piece comes back with a per-piece report.</p>`),
      step(2, 'Read the report per piece, not as a score',
        `<p>Each violation is listed per piece with the offending line. You are looking for the specific lines to fix, not a number.</p>`),
      step(3, 'Apply the one-pass fix for voice violations',
        `<p>Voice violations come with a one-pass fix that rewrites only the offending lines and leaves the rest of the piece alone. Use it, then re-read the fixed lines to be sure they still say what you meant.</p>`),
      step(4, 'Edit platform-limit failures by hand',
        `<p>Platform failures are hard limits, so there is no auto-fix. Trim the caption, drop a hashtag, or change the aspect until the piece passes. Do not schedule a failing piece.</p>`),
      step(5, 'Re-run until the batch is green',
        `<p>A green batch is the signal to move pieces to the Planner or export them. Anything less means something will look wrong or off-brand in public.</p>`),
      media('compliance-agent', 'image', 'The compliance panel showing a voice violation and its one-pass fix belongs here.'),
      callout('warn', 'Do not schedule a red piece',
        `<p>Voice violations make you sound off-brand. Platform violations get cut off or rejected by the platform. Both are caught here for free. There is no reason to ship either.</p>`),
    ),
  },
  {
    slug: 'youtube-and-linkedin',
    title: 'YouTube and LinkedIn: native catalogs and the Studio kit',
    category: 'Content Hub',
    excerpt: 'Step by step: use the native YouTube and LinkedIn surfaces, and turn a video into a publish-ready kit in one click.',
    sortOrder: 9,
    published: true,
    body: html(
      `<p>YouTube and LinkedIn are first-class platforms in the Hub, with their own catalogs, formats, sizes, and previews, not afterthoughts bolted onto the feed platforms. YouTube also ships a one-click Studio kit that packages a video for publishing.</p>`,
      introBox([
        ['What this is', 'The native YouTube and LinkedIn surfaces'],
        ['YouTube formats', 'Long (16:9) and reel (9:16 Shorts)'],
        ['LinkedIn formats', 'Feed, carousel, article, video'],
        ['Bonus', 'The one-click YouTube Studio kit'],
      ]),
      `<h2>YouTube</h2>`,
      `<p>Two surfaces: <strong>long</strong> (16:9 watch page, chaptered script, timestamped description) and <strong>reel</strong> (9:16 Shorts, hook in the first two seconds). The previews render each the way YouTube would.</p>`,
      `<h2>Package a video with the Studio kit, step by step</h2>`,
      step(1, 'Open the video piece and run the Studio kit',
        `<p>The kit turns the piece into a publish-ready package in one click.</p>`),
      step(2, 'Review the A/B titles and description',
        `<p>You get two title options to test, an SEO description, and search tags. Pick a title and trim the description to front-load the first line, which is all most viewers read.</p>`),
      step(3, 'Check the chapters',
        `<p>Chapters are generated valid: normalized to start at zero and strictly increase. Skim them against the script so the labels match what is actually on screen.</p>`),
      step(4, 'Render the thumbnail',
        `<p>The kit gives a thumbnail concept: an image prompt plus a big overlay-text idea. Render it through Image Studio, add the words with the overlay editor, and the URL stitches back into the kit.</p>`),
      `<h2>LinkedIn</h2>`,
      `<p>Four native formats, each with its own preview: feed, carousel (a document), article, and video. The catalog is written in the founder's first-person voice and frames the topic as an operations problem, aimed at career and business readers, so the tone differs from the consumer platforms on purpose.</p>`,
      media('youtube-and-linkedin', 'image', 'The YouTube Studio kit panel filled out for one video belongs here.'),
      callout('tip', 'One video, three placements',
        `<p>A long YouTube video, a Short cut from its hook, and a LinkedIn video post are three placements from one production. Generate them as a set in the same batch.</p>`),
    ),
  },
  {
    slug: 'content-export',
    title: 'Export: get finished pieces into your scheduler',
    category: 'Content Hub',
    excerpt: 'Step by step: choose a target, export the batch, and confirm the file imports cleanly, with per-target formatting done for you.',
    sortOrder: 10,
    published: true,
    body: html(
      `<p>Export turns saved pieces into the files your scheduler or ad manager expects. Each target has its own formatter, so you never hand-edit a CSV. Export is the last step after a piece is drafted, reviewed, compliant, and scheduled on the Planner.</p>`,
      introBox([
        ['What this is', 'The bridge from the Hub to your scheduler'],
        ['Where it lives', 'Content Hub / Export'],
        ['Prerequisite', 'Saved, compliant pieces'],
        ['You never', 'Hand-edit the output file'],
      ]),
      `<h2>The targets</h2>`,
      table(['Target', 'What it produces', 'Use it when'], [
        ['CSV', 'The generic scheduler import: caption, media URL, platform, scheduled time.', 'Your scheduler accepts a CSV import'],
        ['GoHighLevel', 'Posts in GHL social planner format, tracked links included.', 'You schedule inside GoHighLevel'],
        ['Metricool', 'The Metricool bulk-import layout.', 'You schedule inside Metricool'],
        ['Google Sheets', 'Writes the batch to a shared sheet via the service account.', 'A team schedules from a shared sheet'],
        ['Schedule export', 'Pieces export with their Planner dates attached.', 'You want the scheduler calendar to match the board'],
      ]),
      `<h2>Export a batch, step by step</h2>`,
      step(1, 'Finish and save the pieces',
        `<p>Only saved pieces export. Review them first: exported junk is still junk, just delivered on time.</p>`),
      step(2, 'Place them on the Planner if timing matters',
        `<p>If you want the scheduled date to travel with the piece, place it on the Planner before exporting. Untimed pieces export without a slot.</p>`),
      step(3, 'Choose the target and export',
        `<p>Pick the target that matches your scheduler and run the export. The formatter handles the column layout and the per-platform quirks for that target.</p>`),
      step(4, 'Confirm the first import once',
        `<p>Open the exported file and import it into your scheduler once to confirm the columns land correctly. After that first confirmation, the same target is routine every week.</p>`),
      `<h2>What travels with a piece</h2>`,
      `<p>Copy, hosted media URLs (overlay burns included), the tracked /go link, and the scheduled slot. Because the tracked link travels with the piece, the clicks, leads, and sales from the scheduled post still roll back up to the card.</p>`,
      media('content-export', 'image', 'The export panel with a target selected and the file summary belongs here.'),
      callout('info', 'Export does not replace attribution',
        `<p>Even when a post goes out through an external scheduler, its tracked link still measures it. Keep the tracked link in the caption; do not swap it for the raw destination when you import.</p>`),
    ),
  },
  {
    slug: 'colorblock-and-slideshow',
    title: 'Color blocks and photo slideshows: two text-forward formats',
    category: 'Content Hub',
    excerpt: 'Step by step: post a Facebook color block with the palette composer, and build a TikTok photo-mode slideshow with per-slide text you can style and burn.',
    sortOrder: 11,
    published: true,
    body: html(
      `<p>Two formats put words first instead of imagery. The Facebook color block renders a short hook as big bold text on a brand background, no image needed. The TikTok photo-mode slideshow is a swipeable set of images where each slide carries its own styled, editable text. Both are built for the moments when the line is the whole post.</p>`,
      introBox([
        ['What these are', 'Two native, text-forward formats'],
        ['Color block', 'Facebook: big bold text on a brand color, no image'],
        ['Photo slideshow', 'TikTok: swipeable images, per-slide styled text'],
        ['Where they live', 'Content Hub, in the Facebook and TikTok catalogs'],
      ]),
      `<h2>Facebook color-block posts</h2>`,
      `<p>A color block is a Facebook post that is only a line: Facebook renders it large and bold on a solid background when the text is short enough. It stops the scroll precisely because there is no image competing for attention. The catch is the ceiling: past about 130 characters, Facebook collapses it back into an ordinary text post, so brevity is the whole craft.</p>`,
      step(1, 'Write a hook under the ceiling',
        `<p>One felt moment, one line, under 130 characters. The composer and the compliance check both warn you the moment you cross it. Shorter is bigger: the text scales down as it lengthens, so a tight line renders largest.</p>`),
      step(2, 'Pick the background',
        `<p>Open the piece to the Edit tab and use the color-block composer. Choose a swatch from the brand palette, or a gradient. The preview updates live and shows the text scaled the way Facebook scales it natively.</p>`),
      step(3, 'Post it natively, or render it as an image',
        `<p>On Facebook itself you post the text-only block and Facebook paints the background. For a scheduler or another platform, use <em>Render as image</em> to bake the block into a square PNG that lands in the piece's gallery.</p>`),
      `<h2>TikTok photo-mode slideshows</h2>`,
      `<p>Photo-mode is TikTok's swipeable image post: a set of stills the viewer swipes through, with a caption and a sound, instead of a video. Each slide is an image with its own text laid on top, and TikTok lets you restyle that text per slide. The slideshow editor here mirrors that exactly.</p>`,
      step(1, 'Build the slide set',
        `<p>Cover slide first, one point per slide after, call to action last. The preview autoplays through the slides with swipe dots so you can watch the read the way a viewer would.</p>`),
      step(2, 'Style the text on a slide',
        `<p>In the Edit tab, the slide text editor edits one slide at a time. Set the words, then the font, weight, color, size, and case, and drag it to position. Every slide keeps its own recipe, so each can read differently.</p>`),
      step(3, 'Burn the text onto the slide',
        `<p><em>Burn text onto slide</em> bakes the styled text into that slide's image and saves it back to the gallery. Burned slides post with the text baked in, exactly like text placed in TikTok's own editor.</p>`),
      step(4, 'Repeat per slide, then export',
        `<p>Move through the slides with the arrows and style each. The slideshow exports and schedules like any other multi-frame piece.</p>`),
      table(['Format', 'Platform', 'The one rule'], [
        ['Color block', 'Facebook', 'Stay under 130 characters or it stops being a color block'],
        ['Photo slideshow', 'TikTok', 'One point per slide; style and burn the text per slide'],
      ]),
      media('colorblock-and-slideshow', 'video', 'Picking a color-block swatch, then styling and burning text on a slideshow slide belongs here.'),
      callout('tip', 'Use these for the line that does not need a picture',
        `<p>Some hooks are strong enough to stand alone. A color block or a text-first slideshow slide often outperforms a busy image for those, because nothing dilutes the words.</p>`),
    ),
  },
  {
    slug: 'media-library-and-thumbnail-lab',
    title: 'The Media Library and the Thumbnail Lab',
    category: 'Content Hub',
    excerpt: 'One searchable home for every asset the app makes, plus per-variant thumbnails built with AI and the same text overlay system as the image studio.',
    sortOrder: 12,
    published: true,
    body: html(
      `<p>Every asset the app touches now lives in one place. The Media Library collects uploads, Content Hub renders, reel composites, and Thumbnail Lab exports with provenance and tags, so you can find anything again and the AI can use prior media as context. The Thumbnail Lab builds per-variant video thumbnails on top of it.</p>`,
      introBox([
        ['Media Library', 'Admin / Media Library — every asset, folders, tags, search'],
        ['Thumbnail Lab', 'Reel Studio Scoreboard → thumb on a variant row'],
        ['Context', 'Library assets seed AI image generation and editing'],
      ]),
      `<h2>The Media Library</h2>`,
      `<p>One table, many views. Uploads, AI-generated images, reel composites, and thumbnails all land in the same library with a source and tags, so the Vault, the Content Hub, and the Thumbnail Lab are all looking at the same assets. Folders nest, tags are freeform, and everything is searchable by name or tag.</p>`,
      step(1, 'Browse or search',
        `<p>The grid shows every asset with its source badge and tags. The left rail filters by folder, kind (image / video / audio), or tag. The search box matches name and tags.</p>`),
      step(2, 'Organize',
        `<p>Create folders inline, then move any asset into one from its detail panel. Tags are added per asset; the rail rolls up your most-used tags as one-click filters.</p>`),
      step(3, 'Upload',
        `<p>The Upload button adds any image, video, or audio file and ingests it with provenance, so it is searchable immediately and available to AI prompts.</p>`),
      `<h2>The Thumbnail Lab</h2>`,
      `<p>YouTube feed and watch posts live or die by the thumbnail, and every variant deserves its own. The Thumbnail Lab builds them with the SAME text overlay system as the Content Hub image studio: the same fonts, styles, colors, weights, and drag-to-move placement.</p>`,
      step(1, 'Open it from the Scoreboard',
        `<p>Every variant row on the Reel Studio Scoreboard has a <strong>thumb</strong> button. It opens the Lab with that variant's hook already on the canvas and its composed MP4 as the background.</p>`),
      step(2, 'Pick a text style template',
        `<p>Seven one-click presets fill the whole recipe — Bold hook, Center stat, Question, Episode, Neon pop, Minimal, Brass rule. Or set the font, style, size, weight, color, tracking, leading, and position yourself.</p>`),
      step(3, 'Get the background with AI',
        `<p>The AI background section <em>creates</em> a fresh image from a prompt, or <em>edits</em> one from the library — pick the edit seed (which library image the AI edits) and up to four reference images for style or character. Renders land back in the library.</p>`),
      step(4, 'Choose the frame size and export',
        `<p>16:9 for feed posts or 9:16 for video. Export burns the thumbnail to JPEG, saves it to the library tagged thumbnail + variant, and attaches it to the Scoreboard row.</p>`),
      media('media-library-thumbnail-lab', 'video', 'Opening the Thumbnail Lab from a Scoreboard variant, picking a template, and exporting belongs here.'),
      callout('tip', 'The loop matters more than the one-off',
        `<p>Because every export lands in the library tagged to its variant, the next thumbnail can start from a previous one as an edit seed. Good thumbnails compound.</p>`),
    ),
  },
];
