import { html, introBox, media, step, callout, table, chip, type SeedArticle } from './helpers';

export const gettingStarted: SeedArticle[] = [
  {
    slug: 'what-is-mothermode',
    title: 'Start here: what MotherMode is and how the pieces fit',
    category: 'Getting Started',
    excerpt: 'The big picture, the moving parts, and the exact order to set them up so nothing breaks downstream.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>MotherMode runs one low-ticket offer end to end. A stranger sees a social post, taps a tracked link, lands on an opt-in or sales page, buys the $7 offer, ascends through upsells, and every one of those events rolls back up to the exact post that caused it. This article is the map. Read it once before you touch anything else.</p>`,
      introBox([
        ['What this is', 'The orientation guide for the whole app'],
        ['Admin side', '/admin (you)'],
        ['Buyer side', '/mothermode/... (your customers)'],
        ['Read this', 'First, before generating or scheduling anything'],
      ]),
      `<h2>The loop, in one table</h2>`,
      `<p>Everything in the admin exists to feed this loop. Each stage has its own detailed guide.</p>`,
      table(['Stage', 'What it does', 'Where you build it'], [
        ['1. Offer', 'Holds the promise, mechanism, price, and bonuses. It is the context source for every AI generator.', 'Offer Kit'],
        ['2. Funnels', 'Opt-in pages capture the email. Sales pages present the VSL, checkout, and upsells.', 'Funnels, Sales Funnels'],
        ['3. Content', 'Generates the posts, images, and videos that send people to the funnels.', 'Content Hub'],
        ['4. Planner', 'Decides when each post goes out and carries its tracked link and metrics.', 'Planner'],
        ['5. Links + metrics', 'Every post link is a tracked /go/code link, so clicks, leads, and sales join back to the exact post.', 'Built into every share'],
        ['6. Kits', 'Turn one intake into launch assets: community, high-ticket, lead magnet, and email sequences.', 'The kit editors'],
      ]),
      media('what-is-mothermode', 'video', 'A five-minute screen tour of the whole loop, offer to metrics, belongs here.'),
      `<h2>Where things live</h2>`,
      `<ul>`,
      `<li>${chip('/admin')} is your side. Every build tool, editor, and dashboard lives under it. Nothing here is visible to buyers.</li>`,
      `<li>${chip('/mothermode/...')} is the buyer side: checkout, upsells, deliverables, this help center, and the changelog.</li>`,
      `<li>${chip('/go/code')} is the tracked-link redirector. You never paste a raw destination URL into a post; you mint a tracked link and share that.</li>`,
      `</ul>`,
      `<h2>The order to set things up</h2>`,
      `<p>Work in this order and nothing downstream breaks. Each step points to its detailed guide.</p>`,
      step(1, 'Fill in the Offer Kit',
        `<p>Everything reads the offer as context, so a thin offer produces generic copy everywhere downstream. Fill in the promise, mechanism, price, bonuses, and positioning before you generate a single thing.</p>`,
        `<p>Guide: <strong>Offers and Funnels / Offer Kit</strong>.</p>`),
      step(2, 'Set the Brand Bible',
        `<p>Voice rules, palette, and imagery direction. Every generator follows it, so set it once and deliberately.</p>`,
        `<p>Guide: <strong>Deliverables and Brand / Brand Bible and the Asset Hub</strong>.</p>`),
      step(3, 'Build the sales funnel',
        `<p>Generate the VSL page, checkout, and upsells from the offer, then regenerate the sections that miss.</p>`,
        `<p>Guide: <strong>Offers and Funnels / Sales Funnels</strong>.</p>`),
      step(4, 'Add an opt-in funnel to capture the email first',
        `<p>A standalone lead-capture page that feeds the sales funnel, so a no-sale still becomes a lead you can follow up with.</p>`,
        `<p>Guide: <strong>Offers and Funnels / Opt-in Funnels</strong>.</p>`),
      step(5, 'Generate content and schedule it',
        `<p>Use the Generate drawer for a batch, review each draft against its live preview, then place the winners on the Planner.</p>`,
        `<p>Guides: <strong>Content Hub</strong> and <strong>Planner and Publishing</strong>.</p>`),
      step(6, 'Watch the numbers and iterate',
        `<p>Funnel Stats and the per-card metrics tell you which funnel converts and which post did the work. Improve the offer and the next batch picks the improvement up automatically.</p>`,
        `<p>Guides: <strong>Offers and Funnels / Leads and Funnel Stats</strong> and <strong>Planner / Click Rollups</strong>.</p>`),
      callout('tip', 'When in doubt, improve the offer',
        `<p>Because context re-resolves at generation time, the single highest-leverage edit in the whole app is improving the offer record. The next funnel page, post, or kit you generate reflects it with no re-attaching.</p>`),
    ),
  },
  {
    slug: 'admin-areas-guide',
    title: 'Find anything: the admin sidebar, area by area',
    category: 'Getting Started',
    excerpt: 'What every entry in the admin sidebar is for, and exactly when you reach for it.',
    sortOrder: 2,
    published: true,
    body: html(
      `<p>The admin sidebar is grouped by the job you are doing, not by feature name. This guide is the quick reference: find the job, then open the area. Each entry points to the detailed guide when you are ready to go deeper.</p>`,
      introBox([
        ['What this is', 'A reference for the whole admin sidebar'],
        ['Use it when', 'You know what you want to do but not where it lives'],
        ['Organized by', 'The job: build, feed, kit up, watch, maintain'],
      ]),
      `<h2>Build the offer and funnels</h2>`,
      table(['Area', 'What it is for', 'When you use it'], [
        ['Asset Hub', 'One row per offer showing whether the system is finished and what is missing.', 'Checking a launch is complete before you push traffic'],
        ['Sales Funnels', 'The VSL page, checkout, and upsells, with the AI autofill.', 'Building or editing the selling path'],
        ['Funnels', 'Opt-in funnels that capture the email before the pitch.', 'Lead magnets, waitlists, any email-first page'],
        ['Brand Bible', 'Voice, palette, and imagery rules every generator follows.', 'Setting or tuning the brand once, up front'],
        ['Assets', 'The media library funnels and kits pull from.', 'Reusing an image, logo, or burn across surfaces'],
      ]),
      `<h2>Feed the funnels</h2>`,
      table(['Area', 'What it is for', 'When you use it'], [
        ['Content', 'The Content Hub: catalogs, the Generate drawer, Image Studio, export.', 'Drafting, reviewing, and exporting posts'],
        ['Planner', 'The board that schedules pieces and carries their tracked links and metrics.', 'Deciding what posts when, and reading per-post numbers'],
      ]),
      `<h2>Kits and deliverables</h2>`,
      table(['Area', 'What it is for', 'When you use it'], [
        ['Community', 'Community launch kit from one intake.', 'Naming and launching a free or paid community'],
        ['High-Ticket', 'The back-end offer stack, triage and closing scripts.', 'Building the ascension offer behind the $7'],
        ['Lead Gen', 'The lead magnet itself, in ten formats.', 'Creating the resource an opt-in funnel gives away'],
        ['Email Marketing', 'Send-ready email sequences from blueprints.', 'Writing a launch, nurture, or flash-sale sequence'],
        ['Deliverables', 'The buyer-facing resources, editable in the app.', 'Improving what a buyer receives after purchase'],
      ]),
      `<h2>Watch the numbers</h2>`,
      table(['Area', 'What it is for', 'When you use it'], [
        ['Funnel Stats', 'Opt-ins, sales, and conversion by funnel.', 'Deciding which funnel or post to double down on'],
        ['Customers / Purchases / Subscriptions', 'The money side: who bought what and their status.', 'Support, refunds, and revenue checks'],
        ['Receipt Log / Licenses / Stripe', 'Transaction-level records and license keys.', 'Deep-diving a single order'],
        ['CTA Analytics / Email Templates / Email Marketing', 'The email side: templates, triggers, and click analytics.', 'Tuning the emails buyers and leads receive'],
      ]),
      `<h2>Keep the system healthy</h2>`,
      table(['Area', 'What it is for', 'When you use it'], [
        ['Integrations', 'API keys and runtime model overrides.', 'A generator stops working, or you switch models'],
        ['Courses / Course Access', 'The legacy course area.', 'Managing the older course content'],
        ['Help Center', 'These articles and the changelog.', 'Any time you need a refresher or ship a change'],
      ]),
      media('admin-areas-guide', 'image', 'An annotated screenshot of the sidebar with the five groups marked belongs here.'),
      callout('info', 'A rule of thumb',
        `<p>If you are making something, it is in the top three groups. If you are measuring something, it is in "Watch the numbers". If something broke, start in Integrations.</p>`),
    ),
  },
  {
    slug: 'publishing-and-drafts',
    title: 'Drafts, publishing, and how updates go live',
    category: 'Getting Started',
    excerpt: 'One publish model runs the whole app. Learn it once and every editor behaves the same way.',
    sortOrder: 3,
    published: true,
    body: html(
      `<p>Every admin-editable surface in MotherMode uses the same publish model. Learn it once here and the Help Center, Deliverables, kit content, and funnel pages all behave identically. There is no deploy and no separate "republish" step anywhere.</p>`,
      introBox([
        ['What this is', 'The one publish model used across the app'],
        ['Applies to', 'Help Center, Deliverables, kits, funnel pages'],
        ['Key idea', 'Drafts are admin-only; publishing goes live instantly'],
      ]),
      `<h2>The model</h2>`,
      step(1, 'Everything starts as a draft',
        `<p>A new article, deliverable override, or kit section starts unpublished. Only admins can see it, listed in the editor with a Draft badge. The public side never shows a draft.</p>`),
      step(2, 'Flip the published toggle and save',
        `<p>The moment you save with ${chip('Published')} on, the row becomes readable by the public side. There is nothing else to click and nothing to wait for.</p>`),
      step(3, 'Edits to a published row go live on save',
        `<p>Change the copy and save. The public page updates on its next visit. There is no separate republish step and no stale version lurking.</p>`),
      step(4, 'Unpublish to hide without deleting',
        `<p>Flip the toggle off and save. The row disappears from the public side but stays in your editor list, so you can bring it back later.</p>`),
      `<h2>Why there is no deploy</h2>`,
      `<p>Content lives in Supabase, not in the codebase. When you save, the app revalidates the affected public paths, so the cached public page is rebuilt with the new content on the next visit. Nothing is compiled, built, or shipped. This is why you can fix a typo on a live page in ten seconds.</p>`,
      media('publishing-and-drafts', 'image', 'A screenshot of the publish toggle and the Draft badge in an editor belongs here.'),
      `<h2>Where this applies, and the two exceptions</h2>`,
      table(['Surface', 'Publish model'], [
        ['Help articles and changelog entries', 'Draft / Published toggle (this system)'],
        ['Deliverable overrides and buyer resources', 'Draft / Published toggle'],
        ['Kit content published to Deliverables', 'Published when you publish the kit to Deliverables'],
        ['Funnel pages', 'Their own per-page publish state; see the Sales Funnels guide'],
        ['Planner cards', 'A separate per-card draft / scheduled / published state; see the Publish State guide'],
      ]),
      callout('warn', 'Do not confuse the three "publish" ideas',
        `<p>Publishing a help article, publishing a funnel page, and marking a planner card published are three different switches for three different things. The first two put content on the public site. The third only records that a social post actually went live.</p>`),
    ),
  },
];
