import { html, introBox, media, step, callout, table, chip, type SeedArticle } from './helpers';

export const kits: SeedArticle[] = [
  {
    slug: 'community-kit',
    title: 'Community Kit: launch a community from one intake',
    category: 'Kits',
    excerpt: 'Step by step: fill the intake, generate the kit, and walk out with a name, questions, scripts, ads, and the first pinned post.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>The Community Kit turns a short intake into everything a community launch needs. Fill in the audience, the topic, and the paid/free split, and the generator produces the whole kit in one pass. Every section regenerates individually and is editable afterward.</p>`,
      introBox([
        ['What this is', 'A community launch kit from one intake'],
        ['Where it lives', 'Admin / Community'],
        ['Input', 'Audience, topic, paid/free split'],
        ['Output', 'Name, questions, scripts, ads, lead form, pinned post'],
      ]),
      `<h2>What the kit contains</h2>`,
      table(['Section', 'What you get'], [
        ['Name + description', 'Name options plus a chosen name and the public description.'],
        ['Qualifying questions', 'Exactly three, with separate sets for the paid and the free community.'],
        ['DM script', 'For inviting people into the community.'],
        ['Sales-call script', 'For converting people to the paid tier.'],
        ['Ad content style', 'Angle, primary text, headline, description, and an image prompt.'],
        ['Lead form + first pinned post', 'The intake form and the post that welcomes new members.'],
      ]),
      `<h2>Generate the kit, step by step</h2>`,
      step(1, 'Fill the intake honestly',
        `<p>Audience, topic, and the paid/free split. Be specific about who the community is for; the qualifying questions and the scripts are only as sharp as this answer.</p>`),
      step(2, 'Run the generator',
        `<p>The whole kit generates in one pass. Read it top to bottom once before regenerating anything, so you know which sections are strong and which need a redo.</p>`),
      step(3, 'Regenerate the weak sections individually',
        `<p>Each section regenerates on its own. The name and the qualifying questions are the two worth the most iterations, because everything else hangs off them.</p>`),
      step(4, 'Edit the final copy by hand',
        `<p>The kit is fully editable. Put your own phrasing on the DM and sales-call scripts, because those are read by a real person in a real conversation.</p>`),
      step(5, 'Copy the pieces into place',
        `<p>Copy the description into the community, the questions into the join form, and the pinned post into the first slot. The ads section feeds the Content Hub for the promotion posts.</p>`),
      media('community-kit', 'image', 'The kit editor with the intake on the left and a generated script section open belongs here.'),
      callout('tip', 'Free and paid questions do different jobs',
        `<p>The free community questions screen for fit and spam. The paid community questions qualify for money and commitment. Do not reuse one set for both; the kit gives you separate sets for a reason.</p>`),
    ),
  },
  {
    slug: 'high-ticket-kit',
    title: 'High-Ticket Kit: build the back-end offer stack',
    category: 'Kits',
    excerpt: 'Step by step: generate the program name, full offer stack, give-away resource, and the triage and closing scripts.',
    sortOrder: 2,
    published: true,
    body: html(
      `<p>The High-Ticket Kit is the sibling of the Community Kit for the back end of the ascension path. One intake produces the complete high-ticket offer package: what the program is, what it includes, and the exact words for the two conversations that sell it.</p>`,
      introBox([
        ['What this is', 'The back-end offer builder'],
        ['Where it lives', 'Admin / High-Ticket'],
        ['Input', 'One intake about the transformation'],
        ['Output', 'Offer stack, give-away resource, triage + closing scripts'],
      ]),
      `<h2>What the kit contains</h2>`,
      table(['Section', 'What you get'], [
        ['Offer + program name', 'The name of the high-ticket program.'],
        ['The full stack', 'Promise, mechanism, includes, timeline, price and payment, guarantee, bonuses, positioning.'],
        ['Give-away value resource', 'The lead magnet that seeds high-ticket conversations.'],
        ['15-minute triage script', 'Qualify or disqualify fast without burning the lead.'],
        ['Full sales-call script', 'The structured closing conversation.'],
        ['Optional ads angle', 'For filling the calendar with calls.'],
      ]),
      `<h2>Build it, step by step</h2>`,
      step(1, 'Fill the intake around the transformation',
        `<p>High-ticket sells a transformation, not a deliverable. State the before and after plainly in the intake, and attach the $7 offer as context so the ascension story connects the front end to the back end.</p>`),
      step(2, 'Generate and read the stack first',
        `<p>The offer stack is the heart. Read the promise, mechanism, and includes before anything else. If those three are not sharp, regenerate them before touching the scripts.</p>`),
      step(3, 'Ground the price and guarantee in reality',
        `<p>The generator proposes a price and guarantee. Adjust them to numbers you will actually say out loud on a call. A price you flinch at is a price you will not close.</p>`),
      step(4, 'Rehearse the two scripts out loud',
        `<p>The triage script and the closing script are meant to be spoken. Read them aloud, cut anything you would not say, and mark the moments where you pause for the answer.</p>`),
      step(5, 'Use the give-away resource to fill the calendar',
        `<p>The give-away resource is the magnet that starts high-ticket conversations. Pair it with an opt-in funnel and the ads angle to book triage calls.</p>`),
      media('high-ticket-kit', 'image', 'The offer stack section of a generated high-ticket kit belongs here.'),
      callout('info', 'The front end and back end should rhyme',
        `<p>The $7 offer and the high-ticket program are two price points of the same promise. Attaching the front-end offer as context is what keeps the ascension story coherent from the first post to the closing call.</p>`),
    ),
  },
  {
    slug: 'lead-gen-kit',
    title: 'Lead Gen Kit: write the magnet buyers actually get',
    category: 'Kits',
    excerpt: 'Step by step: pick a format, set the length, generate the document, and publish it straight to Deliverables.',
    sortOrder: 3,
    published: true,
    body: html(
      `<p>The Lead Gen Kit builds the magnet itself, not just the plan for it. Pick one of ten formats, set the length, and the generator writes the complete, buyer-ready document, then publishes it straight into Deliverables with its own styling intact.</p>`,
      introBox([
        ['What this is', 'The lead-magnet document builder'],
        ['Where it lives', 'Admin / Lead Gen'],
        ['Formats', 'Guide, ebook, checklist, cheatsheet, worksheet, template, swipe file, SOP, course, mini-course'],
        ['Publishes to', 'Deliverables, buyer-ready'],
      ]),
      `<h2>Pick the right format and length</h2>`,
      table(['Goal', 'Best format', 'Length'], [
        ['Quick win, fast consume', 'Checklist or cheatsheet', 'Short'],
        ['Teach a method', 'Guide or ebook', 'Standard to ultra'],
        ['Done-for-you asset', 'Template or swipe file', 'Short to standard'],
        ['Train a team member', 'SOP or course', 'Standard to ultra'],
      ]),
      `<h2>Build and publish, step by step</h2>`,
      step(1, 'Choose the format and fill the intake',
        `<p>Pick the format that matches the goal, then describe the audience and the one outcome the magnet delivers. Attach the offer as context so the magnet points back to the paid path.</p>`),
      step(2, 'Set the length deliberately',
        `<p>Length drives both how many sections the document has and how deep each goes. A checklist is short. A flagship ebook is ultra. Do not generate an ultra document for a top-of-funnel freebie; match the depth to the commitment.</p>`),
      step(3, 'Review the outline before the body',
        `<p>Generation is outline-first. Read the outline and fix the section list before the body is written. It is far easier to cut a section here than to delete three written pages.</p>`),
      step(4, 'Expand any thin section on its own',
        `<p>Each section can be expanded individually. If one section reads thin, expand just that one rather than regenerating the whole document.</p>`),
      step(5, 'Preview the styled buyer view, then publish',
        `<p>Toggle the Styled preview to see the exact buyer view. The document renders to self-contained styled HTML, so it looks designed anywhere it lands. Publish it and buyers get it at the resource URL with no extra wiring.</p>`),
      media('lead-gen-kit', 'video', 'Intake to outline to a published, styled ebook in Deliverables belongs here.'),
      callout('tip', 'The magnet is the first rung of the ascension',
        `<p>End the document with a natural bridge to the $7 offer. The magnet proves the method works; the offer is the next step. Attaching the offer as context makes this bridge write itself.</p>`),
    ),
  },
  {
    slug: 'email-marketing-kit',
    title: 'Email Marketing Kit: generate a send-ready sequence',
    category: 'Kits',
    excerpt: 'Step by step: pick a blueprint, set the timing, generate the sequence, and export it to your ESP.',
    sortOrder: 4,
    published: true,
    body: html(
      `<p>The Email Marketing Kit produces a complete send-ready sequence, not a pile of one-off emails. You pick a campaign blueprint, attach context, and the generator fills a deterministic skeleton with copy, so the arc is always sound and the model only writes the words.</p>`,
      introBox([
        ['What this is', 'The email sequence builder'],
        ['Where it lives', 'Admin / Email Marketing'],
        ['Blueprints', 'Eight campaign arcs (launch, nurture, flash sale, and more)'],
        ['Frameworks', 'Nine per-email argument styles'],
      ]),
      `<h2>Blueprints and frameworks, the two ideas</h2>`,
      table(['Concept', 'What it fixes', 'Examples'], [
        ['Blueprint', 'The arc: how many emails, what each is for, when it sends.', 'Launch, nurture, flash sale'],
        ['Framework', 'How each individual email argues its point.', 'Soap opera, PAS, story-lesson, quick win, case study'],
      ]),
      `<h2>Generate a sequence, step by step</h2>`,
      step(1, 'Pick the blueprint for the job',
        `<p>The blueprint fixes the arc, so the model never decides how many emails to write or what each is for. Choose the one that matches the campaign: a launch, a nurture, a flash sale.</p>`),
      step(2, 'Set the timing style',
        `<p>The timing style (aggressive, standard, gentle) reshapes the send offsets, so the same launch arc can send in three days or two weeks. Match it to how warm the list is.</p>`),
      step(3, 'Attach context and generate',
        `<p>Attach the offer and any kit the sequence should push. The generator fills the skeleton with copy per email. Read the whole arc once before editing, because the sequence works as a sequence.</p>`),
      step(4, 'Use the advanced editor on the emails that matter',
        `<p>Rich-text bodies, per-email length controls, branching, sequence extension, per-email images, and P.S. selling frameworks are all available per email. Spend this effort on the pitch emails, not the housekeeping ones.</p>`),
      step(5, 'Export to your ESP',
        `<p>Plain text is the source of truth, and styled HTML is derived from it on every save, so the two never drift. Export the CSV for a scheduler or ESP import, or copy the styled HTML.</p>`),
      media('email-marketing-kit', 'image', 'A generated launch sequence with the arc, offsets, and one email open belongs here.'),
      callout('info', 'Text is truth',
        `<p>Because HTML is derived from the plain text on every save, you never get a beautiful HTML email whose text version says something different. Edit the text; the HTML follows.</p>`),
    ),
  },
  {
    slug: 'context-bridge',
    title: 'The Context Bridge: attach offers and kits to any generator',
    category: 'Kits',
    excerpt: 'The one rule behind every "attach context" picker, and how to use it so everything you generate stays current.',
    sortOrder: 5,
    published: true,
    body: html(
      `<p>The Context Bridge is the shared machinery behind every "attach context" picker in the app. Understand it once and a behavior you see everywhere makes sense: attach a source once, and everything you generate from then on reflects its live state.</p>`,
      introBox([
        ['What this is', 'The shared context layer for all generators'],
        ['A source is', 'A pointer to an offer or a kit'],
        ['Sources you can attach', 'Offer, Community, High-Ticket, Lead-Gen, Email'],
        ['The key rule', 'Re-resolved at generation time, never copied'],
      ]),
      `<h2>The one rule that matters</h2>`,
      `<p>Sources are stored as references and re-resolved at generation time, never copied into the prompt once and frozen. This single rule explains three behaviors you will rely on:</p>`,
      step(1, 'Improve the source, improve the next batch',
        `<p>Improve the offer today and tomorrow's generated batch reflects the improvement, with no re-attaching. The picker holds a pointer, so it always reads the current version.</p>`),
      step(2, 'Kits argue from the current version of other kits',
        `<p>A kit that cites another kit always generates from that kit's live state, not a stale snapshot. Update the lead magnet and the email sequence that promotes it picks the update up.</p>`),
      step(3, 'Removing a source does not rewrite history',
        `<p>What you pick is a pointer used at generation time. Removing a source stops it influencing future generations; it does not alter anything already generated.</p>`),
      `<h2>Use it well, step by step</h2>`,
      step(1, 'Attach the offer first, almost always',
        `<p>The offer is the right first context for nearly every generation. It keeps the words on the product you actually sell.</p>`),
      step(2, 'Add one specific kit when the job is specific',
        `<p>Pushing the lead magnet? Attach the Lead-Gen kit. Promoting the community? Attach the Community kit. One clear context beats five vague ones.</p>`),
      step(3, 'Feed email back into content with two-way context',
        `<p>Two-way context lets a saved email sequence feed the content Generate drawer, so posts echo what the list is reading. Context flows in both directions: kits into content, and content back into kits.</p>`),
      media('context-bridge', 'image', 'The context picker with an offer and two kits attached belongs here.'),
      callout('tip', 'Think of context as a live subscription, not a paste',
        `<p>Attaching context is subscribing a generator to a source. You are not copying text into a prompt; you are telling the generator where to read from, forever, at run time.</p>`),
    ),
  },
  {
    slug: 'kit-rich-text-editing',
    title: 'Rich text in kits: format freely without breaking anything',
    category: 'Kits',
    excerpt: 'Kit fields are rich text. Here is exactly what happens to your formatting before it reaches a prompt or an export.',
    sortOrder: 6,
    published: true,
    body: html(
      `<p>Kit fields across the suite are rich text: bold, lists, headings, links, and images where enabled, not plain textareas. A reasonable worry is whether that formatting leaks into prompts and exports and confuses the model. It does not, and here is exactly why.</p>`,
      introBox([
        ['What this is', 'How rich text behaves in kit fields'],
        ['The worry', 'Does formatting leak into prompts or exports'],
        ['The answer', 'No. It is sanitized at every boundary'],
        ['You can', 'Format freely for your own reading'],
      ]),
      `<h2>What happens to your formatting at each boundary</h2>`,
      table(['Boundary', 'What the formatting becomes'], [
        ['In the editor', 'Formatted HTML, exactly as you styled it.'],
        ['To a prompt', 'Clean prompt text. Tags are stripped; images become [image] markers, so the model reads words, not markup.'],
        ['To an export', 'Sanitized HTML. For the email kit, the plain-text body stays the source of truth and HTML is derived from it.'],
      ]),
      `<h2>Use it confidently, step by step</h2>`,
      step(1, 'Format for your own reading',
        `<p>Use headings, bold, and lists to make long kit fields scannable. This is for you; it costs nothing downstream.</p>`),
      step(2, 'Drop images in where the field allows it',
        `<p>Where image support is enabled, insert an image. It becomes a clean <code>[image]</code> marker in prompts, so the model knows an image is there without being handed markup.</p>`),
      step(3, 'Trust the export',
        `<p>Exports sanitize the HTML, and the email kit derives its HTML from the plain text on every save. You will not ship a broken tag or a style that leaks into a prompt.</p>`),
      media('kit-rich-text-editing', 'image', 'A rich-text field with formatting and its sanitized prompt-text equivalent belongs here.'),
      callout('info', 'Formatting is presentation-only',
        `<p>Style is for humans reading the editor. The machinery guarantees it never reaches a model as markup and never breaks an export. Format as much as helps you think.</p>`),
    ),
  },
];
