import { html, introBox, media, step, callout, table, chip, type SeedArticle } from './helpers';

export const offersFunnels: SeedArticle[] = [
  {
    slug: 'offer-kit',
    title: 'Offer Kit: fill in the one record every generator reads',
    category: 'Offers & Funnels',
    excerpt: 'The offer is the context source for all AI copy. Here is exactly what to fill in, with examples of weak versus strong entries.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>The offer record holds the promise, mechanism, price, bonuses, and positioning of the thing you sell. It is not a page buyers see. It is the structured source of truth that every AI generator in the app reads as context before it writes a word. A thin offer produces generic copy everywhere. A specific offer produces copy that sounds like you wrote it, everywhere, with no extra work.</p>`,
      introBox([
        ['What this is', 'The single most important record in the app'],
        ['Where it lives', 'Offer Kit, in the admin'],
        ['Read by', 'Funnel AI, Content Hub, all four kits'],
        ['Time to fill in', '20 focused minutes, once'],
      ]),
      `<h2>Why it matters more than any other record</h2>`,
      `<p>When the sales funnel AI drafts a page, when the Content Hub writes a post, when a kit writes a script, the server loads the offer and injects it into the prompt. The model never sees your product page or your notes. It sees only what you put in this record. So the quality of every word the app writes for you is capped by the quality of this one form.</p>`,
      `<h2>Fill in every field, with examples</h2>`,
      step(1, 'Promise: the one outcome, stated plainly',
        `<p>One sentence naming the result the buyer gets. Weak: <em>a better life</em>. Strong: <em>plan a week of dinners in 20 minutes with a system that runs itself</em>. The promise is the spine of every headline the app writes.</p>`),
      step(2, 'Mechanism: how it delivers, in your words',
        `<p>The named method or process that produces the promise. This is what makes you different, and it is what the AI reaches for when it needs a "why this works" line. Give it a name and two or three concrete parts.</p>`),
      step(3, 'Price and payment',
        `<p>The $7 anchor and any payment plan. The CTA copy across the whole app pulls from this, so keep it exact. If the price changes, change it here first.</p>`),
      step(4, 'Bonuses and guarantee',
        `<p>What sweetens the deal and what de-risks it. The funnel AI turns these into the bonus stack and the guarantee block on the sales page. List each bonus by name with a one-line benefit.</p>`),
      step(5, 'Positioning: who it is for and who it is not for',
        `<p>Two short lists. The "for" list tells the generators who to write to. The "not for" list is just as useful: it keeps the copy sharp and stops the AI from writing to everyone.</p>`),
      `<h2>Weak versus strong, side by side</h2>`,
      table(['Field', 'Weak (produces generic copy)', 'Strong (produces your voice)'], [
        ['Promise', 'Feel less overwhelmed', 'Dinner decided for the whole week in one 20-minute sit-down'],
        ['Mechanism', 'A planner', 'The Sunday Reset: a 3-step card system that plans, shops, and preps once'],
        ['Positioning', 'Busy people', 'Working mothers with school-age kids who cook at home 4+ nights a week'],
      ]),
      media('offer-kit', 'image', 'A screenshot of a fully filled offer record with each field annotated belongs here.'),
      `<h2>The Context Bridge, in one paragraph</h2>`,
      `<p>When any generator shows an "attach context" picker, the offer is almost always the right first choice. The picker stores a reference, and the server re-resolves it at generation time, so if you improve the offer today, the next batch you generate tomorrow reflects the improvement with no re-attaching. You never copy offer text into a prompt by hand.</p>`,
      callout('tip', 'Revisit the offer after your first real week of data',
        `<p>Once Funnel Stats shows you which angle actually converts, come back and sharpen the promise to match. Every generator picks the sharper version up on its next run.</p>`),
    ),
  },
  {
    slug: 'sales-funnel-builder',
    title: 'Sales Funnels: build the VSL page, checkout, and upsells',
    category: 'Offers & Funnels',
    excerpt: 'Step by step: generate the whole funnel from the offer, regenerate weak sections, style each page, and publish.',
    sortOrder: 2,
    published: true,
    body: html(
      `<p>The Sales Funnels editor is where the selling path is built: the optional opt-in handoff, the VSL page, the checkout, and the upsell chain. It is a master/detail editor with a live page preview, per-page regenerate bars, and an AI builder that drafts the whole funnel from the offer in one pass.</p>`,
      introBox([
        ['What this is', 'The builder for your entire selling path'],
        ['Where it lives', 'Admin / Sales Funnels'],
        ['The pages', 'Opt-in, Sales (VSL), Checkout, Upsells'],
        ['Prerequisite', 'A filled-in Offer Kit'],
      ]),
      `<h2>The pages, and what each is for</h2>`,
      table(['Page', 'Its job', 'Key copy on it'], [
        ['Opt-in (optional)', 'Capture the email before the pitch so a no-sale still becomes a lead.', 'A curiosity headline and the email field'],
        ['Sales (VSL)', 'Make the case and ask for the $7.', 'Headline, video, bullets, guarantee, the call to action'],
        ['Checkout', 'Take the payment.', 'The Stripe order form and trust lines'],
        ['Upsells', 'The ascension path after the first sale.', 'One page per upsell, each with its own offer copy'],
      ]),
      `<h2>Build the funnel, step by step</h2>`,
      step(1, 'Open Sales Funnels and run the AI builder',
        `<p>The autofill reads the offer (and any attached context) and writes every page in one pass. Per-page image prompts are generated alongside the copy, so the media plan travels with the funnel.</p>`,
        `<p>If the builder refuses to run or shows a key banner, the OpenAI key is missing or invalid. Go to Integrations, paste a valid key, and re-run. The banner tells you this instead of failing silently.</p>`),
      step(2, 'Read each page in the live preview',
        `<p>Select a page on the left and read it in the preview on the right as a buyer would. You are looking for the one or two sections per page that miss, not a perfect first draft.</p>`),
      step(3, 'Regenerate the weak sections, not the whole page',
        `<p>Each page has per-section regenerate bars. Use them. Regenerating a single section keeps the parts that work and only rewrites what does not. Whole-page regeneration is the last resort.</p>`),
      step(4, 'Style each page with its chrome and media',
        `<p>Each page carries its own theme and media slots in the same panel. Pull images from the Asset library or generate them in place. The VSL video slot, the hero image, and any bonus graphics are set here.</p>`),
      step(5, 'Publish page by page',
        `<p>Publish state is per page, so you can go live with the sales page while you keep rebuilding an upsell. A page is not visible to buyers until its own publish state is on.</p>`),
      media('sales-funnel-builder', 'video', 'A walkthrough of generating a full funnel from the offer and then regenerating one section belongs here.'),
      `<h2>One-click upsells: how the bump charges</h2>`,
      `<p>Every upsell page is a one-click bump. The buyer's first checkout saves their card (securely, on the Stripe customer), and each upsell after it is a confirmation checkbox and one button — the server charges the saved card directly. There is no second card form, no Stripe Link panel, no text-message code. This is true for every funnel you build, automatically — there is nothing to wire per funnel.</p>`,
      `<p>If a buyer has no card on file (they skipped the main checkout), the bump collects a card once, inline, and every bump after that is one click again. A subscription upsell works the same way: the first period charges the saved card on the spot, and the subscription renews on it.</p>`,
      `<h2>Rehearse the whole ladder with test mode</h2>`,
      `<p>Each funnel has a <strong>Test mode</strong> switch in its settings. With it on, the funnel charges your Stripe <em>test</em> keys end to end — run the checkout with the 4242 test card, then click through every upsell. You can even skip the first purchase: in test mode the bump attaches Stripe's test card for you, so the one-click path rehearses with no prior sale. Flip the switch off to go live. Test and live cards never mix — a card saved in one mode does not exist in the other.</p>`,
      callout('tip', 'If a bump ever shows an error, it names the fix',
        `<p>The classic culprit is a <strong>restricted Stripe key</strong> (starts with rk_) saved in Admin / Stripe — it can take the first payment but cannot charge the saved card on the bump. Save the standard "Secret key" (starts with sk_) from Stripe → Developers → API keys instead. The full troubleshooting table is in the Stripe setup guide.</p>`),
      `<h2>After it is live</h2>`,
      `<p>Performance is under <strong>Funnel Stats</strong>: opt-ins, sales, and conversion per page. The tracked links that feed those numbers are covered in the Tracked Links guide. When a page underperforms, the fix is usually a sharper promise in the Offer Kit followed by regenerating that page's headline section.</p>`,
      callout('warn', 'Do not hand-edit live page copy in two places',
        `<p>The funnel editor is the source of truth for page copy. If you also keep a copy in a doc, they drift. Edit in the editor, and let the AI regenerate from the offer rather than pasting between versions.</p>`),
    ),
  },
  {
    slug: 'optin-funnels',
    title: 'Opt-in funnels: capture the email before the pitch',
    category: 'Offers & Funnels',
    excerpt: 'Build a standalone lead-capture flow with steps and destinations, and wire it so every lead keeps its source.',
    sortOrder: 3,
    published: true,
    body: html(
      `<p>Opt-in funnels are standalone lead-capture flows, separate from the sales funnel's optional embedded opt-in. Use them for lead magnets, waitlists, and any page whose only job is to get the email. They have their own steps, destinations, and capture route.</p>`,
      introBox([
        ['What this is', 'Standalone email-capture pages'],
        ['Where it lives', 'Admin / Funnels'],
        ['Use it for', 'Lead magnets, waitlists, email-first pages'],
        ['Key benefit', 'Every lead keeps the UTM of the post that sent it'],
      ]),
      `<h2>How an opt-in funnel is put together</h2>`,
      table(['Part', 'What it does'], [
        ['Steps', 'An ordered set of pages, each with its own URL. Multi-step flows (a question, then the email form, then a thank-you) are first-class.'],
        ['Destinations', 'Where the lead is sent after capture: a sales page, a deliverable, or a thank-you page. Stored per funnel and picked up by the tracked-link system.'],
        ['Capture', 'Submissions post to /api/optin/capture, which writes the lead with its UTM parameters so the source post is preserved.'],
      ]),
      `<h2>Build one, step by step</h2>`,
      step(1, 'Create the funnel and name it for the magnet',
        `<p>Name it after what it gives away, not after the date. "Sunday Reset checklist" is findable six months from now. "Opt-in test 3" is not.</p>`),
      step(2, 'Add the steps and set each step URL',
        `<p>A single-step opt-in is one page with the email form. Add a second step for a qualifying question or a thank-you page. Each step gets its own URL, which is what you link to from posts and tracked links.</p>`),
      step(3, 'Write the capture copy',
        `<p>One clear benefit line about the magnet, the email field, and the button. The Lead Gen Kit can write the magnet itself; the opt-in page only has to sell the download, not the whole offer.</p>`),
      step(4, 'Set the destination',
        `<p>Choose where a new lead goes next. Sending them to the sales page keeps the ascension path moving. Sending them to the deliverable is the lower-pressure option. You can change this later without touching the capture page.</p>`),
      step(5, 'Publish and mint its tracked link from a planner piece',
        `<p>Share the opt-in through a tracked link minted from a planner piece, never the raw URL, so the lead record carries the source post. The next section explains why this matters.</p>`),
      `<h2>UTM and the lead record</h2>`,
      `<p>When a lead arrives through a tracked link, the link's <code>utm_content</code> is written onto the lead. That one field is what lets the Planner answer "which post produced this lead" later. Strip the UTM parameters and the lead still arrives, but it can never be attributed to a post again.</p>`,
      media('optin-funnels', 'image', 'A screenshot of a two-step opt-in funnel in the editor, with the destination field marked, belongs here.'),
      callout('warn', 'Never share the raw opt-in URL',
        `<p>Always share the tracked /go/code link minted from a planner piece. A raw URL works, but every lead it produces is permanently anonymous. There is no way to back-fill attribution later.</p>`),
    ),
  },
  {
    slug: 'link-tracking-and-utm',
    title: 'Tracked links, UTM, and the /go redirector',
    category: 'Offers & Funnels',
    excerpt: 'How the tracked-link system turns every post into measurable clicks, leads, and sales, and the one convention you must not break.',
    sortOrder: 4,
    published: true,
    body: html(
      `<p>MotherMode never puts a raw destination URL in a social post. It mints a short tracked link, <code>/go/code</code>, that records the click and then redirects. This is the spine of the whole metrics system: it is how a view becomes a number you can act on.</p>`,
      introBox([
        ['What this is', 'The redirect and measurement layer under every post'],
        ['The link format', '/go/code'],
        ['You interact via', 'Planner pieces mint links automatically'],
        ['The one rule', 'Always mint from the piece, never by hand'],
      ]),
      `<h2>What a tracked link carries</h2>`,
      table(['Field', 'What it is'], [
        ['short_code', 'The code in /go/code. Stable, and short enough to sit in a caption.'],
        ['UTM parameters', 'Source, medium, campaign, and utm_content, which by convention identifies the individual post or piece.'],
        ['click_count, last_clicked_at', 'Denormalized counters kept in step with the raw click rows, so the board reads fast.'],
      ]),
      `<h2>How a click becomes a metric, end to end</h2>`,
      step(1, 'You mint the link from a planner piece',
        `<p>When a piece is placed on the Planner, its tracked link is minted with <code>utm_content</code> set to the piece id. This is the join key for everything that follows.</p>`),
      step(2, 'A stranger taps it',
        `<p>The /go redirector writes a raw click row (time, referrer, device family) and increments the link's counter, then sends the person to the destination.</p>`),
      step(3, 'They opt in or buy',
        `<p>The capture route copies the link's UTM onto the lead or order. Now the lead is tied to the link, and the link is tied to the piece.</p>`),
      step(4, 'The Planner rolls it up',
        `<p>Because <code>utm_content</code> equals the piece id, the Planner joins clicks, leads, and sales back to the exact card. That is the per-post number you see on the board.</p>`),
      `<h2>The convention you must not break</h2>`,
      `<p><code>utm_content</code> is a convention, not a foreign key. When it matches a planner piece id, everything joins. When it is hand-typed (something like "fb-reel-1"), the link still mints and redirects perfectly, but it is invisible to per-post metrics forever, and nothing in the UI warns you. The failure is silent.</p>`,
      callout('warn', 'Always mint from the piece',
        `<p>Never hand-build a tracked link or type your own utm_content. Mint links from the planner piece so the join key is correct by construction. A hand-typed link cannot be repaired after the fact; its clicks stay unattributed.</p>`),
      `<h2>The loopback guard</h2>`,
      `<p>Links minted against a local or loopback destination are repaired automatically, so a dev-machine URL never ships in a live post. If a tracked link ever redirects to localhost in production, run the repair script and check the destination base URL.</p>`,
      `<h2>When numbers look wrong</h2>`,
      `<p>Run <code>scripts/inspect-tracked-link-clicks.cjs</code>. It separates three problems that look identical from the admin UI but have completely different fixes: clicks not being written at all, the counter falling behind the raw rows, and a utm_content that does not join to any piece.</p>`,
      media('link-tracking-and-utm', 'image', 'A screenshot of a minted link row showing the short code, the full UTM URL, and the click count belongs here.'),
    ),
  },
  {
    slug: 'lead-capture-and-funnel-stats',
    title: 'Leads, capture, and reading Funnel Stats',
    category: 'Offers & Funnels',
    excerpt: 'What gets recorded with every lead, and how to read Funnel Stats to find the funnel and the post doing the work.',
    sortOrder: 5,
    published: true,
    body: html(
      `<p>Every opt-in and every purchase starts as a lead record. Funnel Stats is the read side: it rolls those records up into per-funnel conversion, and per-post when attribution is intact. This guide covers what a lead carries and how to read the numbers.</p>`,
      introBox([
        ['What this is', 'The measurement read-out for your funnels'],
        ['Where it lives', 'Admin / Funnel Stats'],
        ['Two questions it answers', 'Which funnel converts, and which post did the work'],
      ]),
      `<h2>What a lead carries</h2>`,
      table(['Field', 'Why it matters'], [
        ['Email', 'The identity everything else keys on: orders, deliverable access, email sequences.'],
        ['UTM parameters', 'Inherited from the tracked link, so the source post is preserved on the lead.'],
        ['Funnel and step', 'Which funnel captured it and where in the flow, so you can compare steps.'],
        ['Created at', 'Lets Funnel Stats chart conversion over time.'],
      ]),
      `<h2>Read Funnel Stats, step by step</h2>`,
      step(1, 'Open Funnel Stats and pick the funnel',
        `<p>The per-funnel table shows opt-ins, sales, and the conversion between them. Start here to compare funnels against each other.</p>`),
      step(2, 'Read the conversion, not just the counts',
        `<p>A funnel with fewer opt-ins but a higher opt-in-to-sale conversion is usually the better asset. The conversion ratio is the number to compare.</p>`),
      step(3, 'Drill into a funnel to the post level',
        `<p>When leads carried a joinable <code>utm_content</code>, the drill-down shows the individual posts that produced them. This is where you find the one reel or thread doing most of the work.</p>`),
      step(4, 'Act on the answer',
        `<p>Double down on the winning post's angle in the next Generate batch, and consider sharpening the offer promise to match the angle that converts. Both are covered in their own guides.</p>`),
      `<h2>When numbers look wrong</h2>`,
      step(1, 'Confirm the lead rows exist',
        `<p>The capture route, not the UI, is the source of truth. If opt-ins are happening but Funnel Stats is empty, check that leads are actually being written before assuming a display bug.</p>`),
      step(2, 'Check utm_content on the lead',
        `<p>Missing or hand-typed values break the per-post roll-up, not the per-funnel totals. If totals look right but the drill-down is empty, this is the cause.</p>`),
      step(3, 'Check the click side',
        `<p>If clicks themselves look wrong, run the inspector script covered in the Tracked Links guide. Click problems and lead-attribution problems are different and have different fixes.</p>`),
      media('lead-capture-and-funnel-stats', 'image', 'A screenshot of the Funnel Stats page with the per-funnel table and one drill-down open belongs here.'),
      callout('info', 'Per-funnel totals versus per-post attribution',
        `<p>Per-funnel totals only need the lead to exist. Per-post attribution additionally needs the lead's utm_content to join a piece. The first is almost never broken; the second breaks the moment a link is hand-made.</p>`),
    ),
  },
];
