import { html, introBox, media, step, callout, table, chip, type SeedArticle } from './helpers';

export const planner: SeedArticle[] = [
  {
    slug: 'planner-board',
    title: 'The Planner: schedule a week of posts on one board',
    category: 'Planner & Publishing',
    excerpt: 'Step by step: add plan cards for pieces and lead cards for magnets, place them on the board, and preview without leaving it.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>The Planner is the calendar brain. Pieces from the Content Hub are placed on the board as plan cards, each carrying its platform, its scheduled slot, its tracked link, and its metrics. Lead cards are the other card type: a scheduled push for a lead magnet rather than a content piece. This is where a batch of drafts becomes an actual week.</p>`,
      introBox([
        ['What this is', 'The scheduling board for all posts'],
        ['Where it lives', 'Admin / Planner'],
        ['Two card types', 'Plan cards (content) and lead cards (magnets)'],
        ['Each card carries', 'Platform, slot, tracked link, metrics'],
      ]),
      `<h2>The two card types</h2>`,
      table(['Card', 'What it schedules', 'Use it for'], [
        ['Plan card', 'A content piece from the library, with its tracked link and metrics.', 'Reels, carousels, feed posts, videos'],
        ['Lead card', 'A push pointing at an opt-in funnel.', 'Promoting the lead magnet on a schedule'],
      ]),
      `<h2>Build a week, step by step</h2>`,
      step(1, 'Open the Planner and click Add Plan Card',
        `<p>The piece picker pulls from the saved library, so only reviewed, saved pieces appear. Pick the piece and it lands on the board as a card.</p>`),
      step(2, 'Place the card on a day and platform',
        `<p>Drag the card to its slot. The card shows the platform glyph so you can see the week's platform mix at a glance. Spread formats across the week so no two days feel the same.</p>`),
      step(3, 'Add lead cards for the magnet pushes',
        `<p>Click ${chip('Add Lead Card')} to schedule a push for the lead magnet. It carries the same tracked-link and metrics machinery as a plan card, so a magnet's posts are measured exactly like content posts.</p>`),
      step(4, 'Preview any card without leaving the board',
        `<p>Open the piece preview panel to see the full piece, its copy, and its media in place. You never have to leave the board to check what a card actually contains.</p>`),
      step(5, 'Confirm the schedule drafts',
        `<p>Cards start as schedule drafts until their slot is confirmed. This keeps a half-built week from looking committed. Confirm the slots once the week looks right.</p>`),
      media('planner-board', 'video', 'Building one week: three plan cards and a lead card, with the preview panel open, belongs here.'),
      `<h2>Read the week back</h2>`,
      `<p>Step back and read the board as a follower would experience it: a hook, a value post, a magnet push, a story. If three cards in a row sell, rearrange. The board is the one place you can see the whole week before it goes out.</p>`,
      callout('tip', 'Batch the week in one sitting',
        `<p>Fill the board for the whole week in one session, then let it run. A planned week beats seven daily scrambles, and the per-card metrics are cleaner when the week is coherent.</p>`),
    ),
  },
  {
    slug: 'publish-state-system',
    title: 'Publish state: know exactly what is live',
    category: 'Planner & Publishing',
    excerpt: 'The draft, scheduled, and published states on every card, and how to keep the board honest when you post by hand.',
    sortOrder: 2,
    published: true,
    body: html(
      `<p>Each planner card carries an explicit publish state, shown as badges on the card, so the board answers "what is actually live" at a glance instead of making you check each platform. This is a different switch from publishing a page or an article, and it only records reality.</p>`,
      introBox([
        ['What this is', 'The per-card live state'],
        ['The three states', 'Draft, Scheduled, Published'],
        ['Shown as', 'Badges on the card'],
        ['It records', 'Reality, it does not publish anything itself'],
      ]),
      `<h2>The three states</h2>`,
      table(['State', 'Means', 'Safe to'], [
        ['Draft', 'Planned but not scheduled.', 'Edit anything'],
        ['Scheduled', 'Has a confirmed slot and is queued to go out.', 'Edit timing, not content'],
        ['Published', 'Confirmed live, either posted through the integration or marked by hand.', 'Read its metrics'],
      ]),
      `<h2>Keep the board honest, step by step</h2>`,
      step(1, 'Let integrated posts mark themselves',
        `<p>When a post goes out through a connected integration, the card moves to published on its own. Nothing to do.</p>`),
      step(2, 'Mark manual posts published by hand',
        `<p>Stories and anything with native audio are usually posted by hand in the app. After you post, mark the card published. This is the step people forget, and it is what keeps the board honest.</p>`),
      step(3, 'Filter the board by state',
        `<p>Use the state filter to answer "show me everything scheduled this week that is not yet published" in one click. Run this check before the weekend.</p>`),
      `<h2>Why the state matters</h2>`,
      `<p>The publish state is what the metrics views use to separate planned reach from actual reach. A board full of cards that were never marked published makes every metric look worse than it is, because the planned posts are counted but the live ones are not confirmed.</p>`,
      media('publish-state-system', 'image', 'A card with its state badges and the board filtered to scheduled belongs here.'),
      callout('warn', 'Marking published does not post',
        `<p>The state only records that a post went live. It never publishes anything to a platform by itself. Post through the integration or by hand, then let the state reflect it.</p>`),
    ),
  },
  {
    slug: 'click-rollups-and-ad-metrics',
    title: 'Per-post metrics: clicks, leads, sales, and the paid block',
    category: 'Planner & Publishing',
    excerpt: 'Read the numbers on a card, drill into who clicked, and keep paid spend separate from organic, plus how to debug a stuck counter.',
    sortOrder: 3,
    published: true,
    body: html(
      `<p>Because every post carries a tracked link whose <code>utm_content</code> matches the piece id, the Planner shows per-post numbers on the card itself: clicks, the people behind them, leads, and sales. Paid spend is tracked separately. This guide is about reading those numbers and fixing them when they stop moving.</p>`,
      introBox([
        ['What this is', 'The per-post measurement on each card'],
        ['Reads from', 'The tracked link on the card'],
        ['Shows', 'Clicks, click people, leads, sales, paid block'],
        ['Debug tool', 'scripts/inspect-tracked-link-clicks.cjs'],
      ]),
      `<h2>What the card shows</h2>`,
      table(['Number', 'What it tells you'], [
        ['Clicks', 'How many times the tracked link was tapped, kept in step with the raw click rows.'],
        ['Click people', 'The drill-down: who clicked, when, from what referrer and device family.'],
        ['Leads and sales', 'Joined through the lead record, so the card answers "this post produced these leads and these sales".'],
      ]),
      `<h2>Read a card, step by step</h2>`,
      step(1, 'Open the card metrics row',
        `<p>The rollup shows clicks, leads, and sales at a glance. Compare cards across the week to find the post doing the work.</p>`),
      step(2, 'Drill into click people',
        `<p>Open the drill-down to see who clicked, when, and from where. A post with many clicks but no leads is a hook that over-promises. A post with few clicks but high lead conversion is a keeper to amplify.</p>`),
      step(3, 'Feed the winner back into the next batch',
        `<p>The card with the best lead-per-click ratio is the angle for your next Generate batch. This is the loop that makes content improve week over week.</p>`),
      `<h2>The paid block</h2>`,
      `<p>Paid spend is tracked separately from organic. A piece promoted as an ad carries a paid block with spend, results, and derived metrics like cost per lead and cost per sale. The medium is derived from the format, and there is a known trap here: a format whose medium resolves to paid can tag an organic thread as paid. If a card shows paid numbers you never bought, check the medium derivation first.</p>`,
      `<h2>When the numbers stop moving</h2>`,
      step(1, 'Run the inspector script',
        `<p>Run <code>scripts/inspect-tracked-link-clicks.cjs</code>. It separates three problems that look identical from the board but have different fixes.</p>`),
      step(2, 'Identify which of the three it is',
        `<p>Clicks not written at all, the counter falling behind the raw rows, or a utm_content that does not join to a piece. Each has a different fix, and the script tells you which one you have.</p>`),
      step(3, 'Fix the right one',
        `<p>A write problem is a routing or integration issue. A counter problem is a rollup issue. A join problem means the link was hand-made and its clicks stay unattributed. Only the last one cannot be fully repaired after the fact.</p>`),
      media('click-rollups-and-ad-metrics', 'image', 'A card with the metrics row and the paid block open belongs here.'),
      callout('info', 'There was a historical "clicks not counting" bug',
        `<p>A class of bug once wrote clicks but did not count them on the card. It is fixed and covered in the changelog. If an old card still shows zero on a link you know got traffic, the inspector script confirms whether it is that or a join problem.</p>`),
    ),
  },
];
