import { html, introBox, media, step, callout, table, chip, type SeedArticle } from './helpers';

export const deliverablesBrand: SeedArticle[] = [
  {
    slug: 'deliverables-and-resources',
    title: 'Deliverables: edit what buyers receive, no deploy',
    category: 'Deliverables & Brand',
    excerpt: 'Step by step: override a deliverable section, understand the built-in default fallback, and publish a kit straight into a buyer resource.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>Deliverables are what the buyer actually receives after purchase. They are editable in the admin with the same drafts-and-publishing model as this Help Center, so improving a resource never requires a deploy. You override the parts you want to change; the built-in default covers the rest.</p>`,
      introBox([
        ['What this is', 'The editor for buyer-facing resources'],
        ['Where it lives', 'Admin / Deliverables'],
        ['Publish model', 'Draft / Published, no deploy'],
        ['Safety net', 'A built-in default always ships if you override nothing'],
      ]),
      `<h2>How a deliverable is composed</h2>`,
      `<p>Each deliverable has a built-in default structure (the brain-dump content builders) that you can override per section: copy, order, and media. If no override exists for a section, the default ships. This means the product is never broken by an empty admin state, and every improvement you make lands exactly where you make it.</p>`,
      `<h2>Edit a deliverable, step by step</h2>`,
      step(1, 'Open the deliverable and read the default first',
        `<p>Read what ships by default before overriding anything. You may only want to change two sections, and there is no reason to touch the rest.</p>`),
      step(2, 'Override only the sections that need it',
        `<p>Override the copy, order, or media of a section that misses. Sections you leave alone keep shipping the default, so your override surface stays small and reviewable.</p>`),
      step(3, 'Save and it goes live, no deploy',
        `<p>Overrides follow the standard publish model. Save and the buyer view updates on its next visit. Unpublish an override to fall back to the default section without deleting your work.</p>`),
      `<h2>Interactive resource workspaces</h2>`,
      `<p>Some resources are interactive: worksheets and planners the buyer fills in. Buyer entries are stored scoped by the buyer's email, so a returning buyer finds their previous work, and one buyer never sees another's entries. You do not manage these entries day to day; they persist on their own.</p>`,
      `<h2>Publish a kit into Deliverables</h2>`,
      `<p>The Lead Gen Kit publishes its styled document straight into Deliverables, which is the fastest way to add a brand-new buyer resource: generate, preview the styled view, publish. The new resource appears at the buyer resource URL with no extra wiring.</p>`,
      media('deliverables-and-resources', 'image', 'The deliverables editor with one section overridden and the buyer view beside it belongs here.'),
      callout('tip', 'Improve deliverables from real support questions',
        `<p>Every time a buyer asks how something works, that is a section to override. Improving the deliverable from real questions compounds: the next buyer never asks it.</p>`),
    ),
  },
  {
    slug: 'brand-bible-and-assets',
    title: 'Brand Bible and the Asset Hub: one brand everywhere',
    category: 'Deliverables & Brand',
    excerpt: 'Step by step: set the voice and visual rules every generator follows, and run the media library everything pulls from.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>Two admin areas keep everything looking and sounding like one brand: the Brand Bible holds the rules, and the Asset Hub holds the media. Set both once, up front, and every generator and every surface stays on-brand without you policing it.</p>`,
      introBox([
        ['What this is', 'The brand control layer'],
        ['Brand Bible', 'Voice, palette, and imagery rules'],
        ['Asset Hub', 'The shared media library'],
        ['Set it', 'Once, up front, before heavy generation'],
      ]),
      `<h2>Brand Bible: the rules every generator follows</h2>`,
      step(1, 'Set the voice rules',
        `<p>The NO-list, the dash rules, and the call-to-action style. Generators read these as authoritative, so this is the highest-leverage copy in the app after the offer. Write the rules you actually want enforced.</p>`),
      step(2, 'Set the palette tokens',
        `<p>The named colors the whole app uses. Change a token here and every surface that references it follows. Never hard-code a color in a one-off place; add it to the palette.</p>`),
      step(3, 'Set the imagery direction',
        `<p>The visual style the image generators aim for: mood, lighting, subject treatment. A clear imagery direction is what makes a week of generated images look like one brand instead of seven stock styles.</p>`),
      `<h2>Asset Hub: the shared media library</h2>`,
      step(1, 'Treat it as the single source for media',
        `<p>Every generated image, overlay burn, and uploaded asset lives here. Funnel media slots, kit image fields, and the Content Hub all pull from the same library, so an asset made once is reusable everywhere.</p>`),
      step(2, 'Use the systems view to check an offer is complete',
        `<p>The offer-systems view answers "is this offer a finished system" by checking which assets and pages exist. Run it before you push traffic to a launch, and fill the gaps it flags.</p>`),
      step(3, 'Reuse rather than regenerate',
        `<p>Before generating a new image, check whether a suitable one already exists in the library. Reusing a good burn keeps the brand consistent and saves a generation.</p>`),
      media('brand-bible-and-assets', 'image', 'The Asset Hub systems view with one offer expanded belongs here.'),
      callout('warn', 'Edit the Brand Bible deliberately',
        `<p>A change to the Brand Bible changes what every future generation sounds and looks like. Do not tune it casually mid-launch. Set it, test it on a small batch, then leave it alone.</p>`),
    ),
  },
];

export const adminSystem: SeedArticle[] = [
  {
    slug: 'email-templates-and-flows',
    title: 'Email templates, flows, and analytics',
    category: 'Admin & System',
    excerpt: 'Step by step: edit the transactional templates, wire triggers to sequences on the flow canvas, and read send, open, and click analytics.',
    sortOrder: 1,
    published: true,
    body: html(
      `<p>Separate from the AI Email Marketing Kit, the app has a transactional email layer: the templates buyers and leads receive (receipts, access, sequence emails) and the flows that decide who gets what. This is the always-on plumbing, not a campaign you write once.</p>`,
      introBox([
        ['What this is', 'The transactional email layer'],
        ['Two halves', 'Templates (the emails) and flows (who gets what)'],
        ['Different from', 'The AI Email Marketing Kit, which writes campaigns'],
        ['Analytics', 'Sends, opens, clicks per template and flow'],
      ]),
      `<h2>Templates: the emails themselves</h2>`,
      step(1, 'Edit a template with tokens',
        `<p>Templates support tokens for the buyer name, product, and links. Edit the copy around the tokens; the tokens fill in per recipient at send time.</p>`),
      step(2, 'Inject images and keep the brand HTML',
        `<p>Templates support image injection and output brand HTML, so receipts and access emails look like your brand, not a default system email. Template changes are live on save, no deploy.</p>`),
      step(3, 'Preview with real tokens before it sends',
        `<p>The testing inbox preview renders any template with real tokens filled in. Always preview a template before letting it send to a real buyer.</p>`),
      `<h2>Flows: who gets what</h2>`,
      step(1, 'Read the flow canvas',
        `<p>The flow canvas is the visual map of automation: triggers (purchase, opt-in, tag) wired to the sequence each person enters. Read it before changing anything so you do not fork a flow that already works.</p>`),
      step(2, 'Assign funnel events to the right flow',
        `<p>Funnel event assignment connects a funnel's events to the correct flow, so a buyer from upsell two does not get the front-end sequence. Check this mapping whenever you add a funnel.</p>`),
      step(3, 'Read the analytics to find dead emails',
        `<p>Email analytics and the flow analytics dashboard show sends, opens, and clicks per template and per flow. A template with sends but no opens is a subject-line problem. A flow with no sends is a wiring problem. Both are visible here instead of silently underperforming.</p>`),
      media('email-templates-and-flows', 'image', 'The flow canvas with one trigger wired to a sequence belongs here.'),
      callout('info', 'Kit writes campaigns, flows deliver the always-on email',
        `<p>Use the Email Marketing Kit to author a launch or nurture campaign. Use templates and flows for the receipts, access, and lifecycle emails that run every day. They are separate systems that happen to both send email.</p>`),
    ),
  },
  {
    slug: 'migrations-and-audit',
    title: 'Migrations and audit: keep the database honest',
    category: 'Admin & System',
    excerpt: 'How schema changes are versioned, and how to use the audit scripts when an admin page shows empty data it should have.',
    sortOrder: 2,
    published: true,
    body: html(
      `<p>Schema changes live as timestamped SQL files in <code>supabase/migrations</code> and apply in order. You rarely think about them until an admin page shows empty data it should have, and then the audit scripts are the first thing to run. This is the operational guide.</p>`,
      introBox([
        ['What this is', 'The database maintenance guide'],
        ['Schema lives in', 'supabase/migrations, applied in order'],
        ['Audit tool', 'scripts/db-table-audit.cjs'],
        ['Run it when', 'An admin page returns empty data it should have'],
      ]),
      `<h2>The three rules</h2>`,
      step(1, 'A new table or column means a new migration file',
        `<p>Never edit an applied migration. Add a new one. Editing history breaks every environment that already applied it.</p>`),
      step(2, 'Keep the standard security posture',
        `<p>Admin-writable tables follow one posture: anonymous reads of published rows only, and all writes through the service role. Do not add a looser policy to make something work; fix the query instead.</p>`),
      step(3, 'Apply pending migrations before reporting a bug',
        `<p>After pulling new code, apply pending migrations first. Most "the page is empty" reports are an unapplied migration, not a code bug.</p>`),
      `<h2>When an admin page shows empty data</h2>`,
      step(1, 'Run the table audit',
        `<p>Run <code>scripts/db-table-audit.cjs</code>. It compares the tables and columns the code expects against what actually exists in the database.</p>`),
      step(2, 'Read the diff, not the error count',
        `<p>The audit lists exactly which table or column is missing. That missing object is almost always a migration you have not applied yet.</p>`),
      step(3, 'Apply the missing migration and re-check',
        `<p>Apply the pending migration, then re-run the audit. A clean audit with still-empty data means the problem is genuinely in the code or the data, and now you know.</p>`),
      media('migrations-and-audit', 'image', 'Terminal output of the table audit on a healthy database belongs here.'),
      callout('tip', 'Audit first, debug second',
        `<p>Nine times out of ten, empty admin data is a missing migration. Run the audit before you touch a single line of code. It turns an hour of debugging into a one-command answer.</p>`),
    ),
  },
  {
    slug: 'integrations-and-keys',
    title: 'Integrations and keys: keep the AI running',
    category: 'Admin & System',
    excerpt: 'Which feature needs which key, and how to switch models at runtime without a redeploy, plus the first thing to check when all AI breaks at once.',
    sortOrder: 3,
    published: true,
    body: html(
      `<p>All AI and third-party access is server-only. Keys are read through the runtime config layer, never in the browser, and most can be overridden from the Integrations admin panel without a redeploy. This is the panel you reach for the moment anything AI stops working.</p>`,
      introBox([
        ['What this is', 'The keys and model control panel'],
        ['Where it lives', 'Admin / Integrations'],
        ['Keys are', 'Server-only, never in the browser'],
        ['Switch models', 'At runtime, no redeploy'],
      ]),
      `<h2>Which feature needs which key</h2>`,
      table(['Key', 'Powers'], [
        ['OpenAI', 'Content generation, all four kits, YouTube kits, sales funnel autofill, compliance fixes'],
        ['Anthropic', 'Optional alternate text provider'],
        ['fal', 'Smart resize and the Seedance video pipeline'],
        ['Supabase (URL, anon, service role)', 'The base app and every DB-backed feature, including this Help Center'],
        ['Google Sheets service account', 'The Sheets export target'],
        ['Stripe', 'Checkout, upsells, subscriptions, the receipt log'],
      ]),
      `<h2>Switch a model at runtime</h2>`,
      step(1, 'Open Integrations and find the provider override',
        `<p>Text provider and model can be switched here without touching environment variables or redeploying. This is how you try a new model the day it comes out.</p>`),
      step(2, 'Change the provider or model and save',
        `<p>The change takes effect on the next generation. Existing content is unaffected; only new generations use the new setting.</p>`),
      step(3, 'Test on one small generation before a big batch',
        `<p>Run a single small generation to confirm the new model behaves before firing a twenty-piece batch through it.</p>`),
      `<h2>When everything AI breaks at once</h2>`,
      step(1, 'Check the OpenAI key first',
        `<p>An invalid or expired OpenAI key presents as "everything AI is broken" across every surface at once. It is almost always the key, not the code.</p>`),
      step(2, 'Paste a valid key and re-test',
        `<p>The fix is a paste, not a deploy. Save the key and run one generation to confirm.</p>`),
      step(3, 'Check the provider override if the key is fine',
        `<p>If the key is valid but generations still fail, check whether a runtime override is pointing at a provider or model that is not configured. A stale override fails exactly like a bad key.</p>`),
      media('integrations-and-keys', 'image', 'The Integrations panel with the provider override visible belongs here.'),
      callout('warn', 'Never paste a key into a client-side place',
        `<p>Keys belong in Integrations or the server environment only. A key that reaches the browser is compromised. The app is built so keys are server-only; keep it that way.</p>`),
    ),
  },
  {
    slug: 'help-center-guide',
    title: 'Run the Help Center: articles, changelog, and media',
    category: 'Admin & System',
    excerpt: 'Step by step: write an article, log a changelog entry, fill a media slot, and keep this knowledge base worth reading.',
    sortOrder: 4,
    published: true,
    body: html(
      `<p>This Help Center is the canonical, searchable explanation of the app. It is only useful if it stays current, and staying current is cheap once you know the three small jobs: writing articles, logging changelog entries, and filling media slots.</p>`,
      introBox([
        ['What this is', 'How to maintain this Help Center'],
        ['Where it lives', 'Admin / Help Center'],
        ['Two content types', 'Articles and changelog entries'],
        ['House rule', 'Update when the feature changes, log when you ship'],
      ]),
      `<h2>Write or update an article, step by step</h2>`,
      step(1, 'One article per feature',
        `<p>Each feature gets one article, updated when the feature changes. Do not start a growing pile of dated notes for the same feature; edit the one article so it is always current.</p>`),
      step(2, 'Pick a stable slug once',
        `<p>The slug is the public URL and is used by internal links. Choose it once and do not rename it, or you break every link that points to it.</p>`),
      step(3, 'Structure it as steps, not prose',
        `<p>Use the step, table, callout, and intro-box blocks so the guide is scannable. A reader should be able to follow the numbered steps and succeed without reading every word.</p>`),
      step(4, 'Publish to make it live',
        `<p>Drafts are admin-only. Flip published and save, and the article is live on the public Help Center with no deploy.</p>`),
      `<h2>Log a changelog entry</h2>`,
      step(1, 'One entry per user-visible change, at ship time',
        `<p>Write the entry the day the change ships, not in a batch at the end of the month. Future-you will not remember what changed.</p>`),
      step(2, 'Pick the right type',
        `<p>Added, improved, fixed, or removed. The type tag tells a reader at a glance what kind of change it was.</p>`),
      step(3, 'Write the body for a person, not a diff',
        `<p>Say what changed and why it matters to the person using the app, in two or three sentences. Link it to the relevant article if one exists.</p>`),
      `<h2>Fill a media slot</h2>`,
      step(1, 'Record the walkthrough or take the screenshot',
        `<p>Each article reserves dashed media slots where a video or screenshot belongs. Record the clip or grab the shot.</p>`),
      step(2, 'Host it at the suggested path',
        `<p>Drop the file under <code>public/help-media/<slug>/</code> using the filename the slot suggests, or use any hosted URL.</p>`),
      step(3, 'Replace the slot in the editor',
        `<p>Edit the article and swap the dashed block for an image tag or a video embed. The admin live preview shows exactly how it will render before you save.</p>`),
      media('help-center-guide', 'video', 'A two-minute tour of editing an article and filling a media slot belongs here.'),
      callout('tip', 'Voice rules apply here too',
        `<p>No em dashes, no en dashes, no NO-list words, periods over exclamation points. The Help Center is part of the brand, so it follows the same rules as every other surface.</p>`),
    ),
  },
];
