/**
 * Prompt bank, round 5: the email ascension round. Four families, merged
 * into PROMPT_RECIPES in promptBank.ts:
 *
 *   email-   8 sophisticated single-send frameworks (letter register,
 *            inbox economics: subject + preheader orders, one-idea
 *            discipline, PS strategy).
 *   emlf-    6 ultra-long-form value essays (the lf- register translated
 *            to the inbox: chaptered, saveable, worth the scroll).
 *   embuy-   8 purchase + OTO nurture frameworks mapped to the email
 *            trigger taxonomy (purchase, upsell_purchase, refund), so
 *            every purchase gets a next-offer nurture and a deep nurture
 *            follow-up, and OTO buyers get their own path.
 *   emgoal-  4 goal-driven frameworks with the custom offer + goal input
 *            fields (book a call, attend event, reply, join).
 *
 * Same contract as the earlier rounds: whyItWorks, a {Slot} template,
 * MotherMode-adapted exemplar subjects/openers, and craft with direct
 * generation orders. Voice rules hold: calibration after bold claims, no
 * NO-list words, no em dashes, soft CTA (honest and direct on the
 * ascension emails, never pressure). All stay organic (no kind): these
 * are transactional and nurture emails, not paid placement.
 */
import type { PromptRecipe } from './promptBank';

const F = (
  r: Omit<PromptRecipe, 'group' | 'builtin'>,
): PromptRecipe => ({ ...r, group: 'framework', builtin: true });

/* ---------------------------------------------------------------------- */
/* email- sophisticated single sends, round 5. Beyond the kit basics and  */
/* the round-1 subject/open-loop pair: the letter register, the FAQ, the  */
/* honest close, the tease, and the postscript play.                      */
/* ---------------------------------------------------------------------- */

export const PROMPT_RECIPES_ROUND5: PromptRecipe[] = [
  F({
    id: 'email-founder-letter',
    label: 'Email: Founder letter',
    hint: 'One idea, plain text, letter register',
    goal: 'replies',
    whyItWorks: [
      'A plain letter from the founder reads as personal mail in an inbox of designed campaigns, and personal mail gets read to the end.',
      'One idea per letter is the discipline that makes each send quotable, and quotable letters get forwarded.',
      'The letter register (me to you, no banner, no buttons) builds the parasocial trust every later offer email spends.',
    ],
    template: [
      'Subject: {TheIdea, as a letter subject: lowercase, 2-6 words}',
      'Preheader: {TheStakesOfTheIdea, one line, never repeats the subject}',
      '',
      'Hi {FirstName},',
      '',
      '{TheScene: the moment that made you write this, 2-3 lines}.',
      '',
      '{TheIdea: stated plainly, one paragraph}.',
      '{WhatItMeans: for her, not for you, one paragraph}.',
      '',
      '{TheOneLine: the sentence she forwards}.',
      '',
      '{Signoff: warm, first name}.',
      '',
      'PS: {SoftInvite: reply with your version of the scene}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: the second calendar',
      'Subject: what I stopped counting',
    ],
    craft: [
      'One idea per letter, no exceptions. If a second idea shows up, it is next week\'s letter.',
      'Plain text register: no banner, no buttons, no design language. The subject line reads like a person wrote it, lowercase is allowed.',
      'The scene opens it, the idea lands mid-letter, and the PS invites a reply. Calibrate any bold claim in the same sentence. No sales CTA; the reply is the goal.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'story',
        label: 'The scene that made you write this (2-3 lines)',
        placeholder: 'Tuesday, 9:47 pm, the school portal announced the form was due at 5.',
        hint: 'the opening scene. Keep it small, true, and specific',
        required: true,
      },
    ],
  }),

  F({
    id: 'email-teach-everything',
    label: 'Email: Teach everything',
    hint: 'The full method in one send',
    goal: 'saves',
    whyItWorks: [
      'Teaching the whole method for free is the strongest trust deposit an email can make, and the deposit is what later offers withdraw against.',
      'A complete how-to email gets saved, starred, and forwarded, which keeps the sender in the inbox long after campaigns fade.',
      'Proving the method works, for free, makes the paid system the obvious shortcut instead of a leap of faith.',
    ],
    template: [
      'Subject: How to {DesiredOutcome} ({TimeCost})',
      'Preheader: {TheWholeMethod, promised in one line}',
      '',
      '{ProblemLine: the one-line cost of doing it the old way}.',
      '',
      'Here is exactly how to {DesiredOutcome}:',
      '',
      '1. {Step: verb first, with the exact how}',
      '2. {Step: the one everyone skips, and why it matters}',
      '3. {Step: the lock-in move}',
      '',
      '{WhatToExpect: the honest timeline and the week-1 reality}.',
      '',
      '{TheShortcut: one line on the system that holds this for her}.',
      'PS: {SaveLine: save this for Sunday}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: How to empty your head in 20 minutes, tonight',
      'Subject: The whole Sunday download, step by step',
    ],
    craft: [
      'Teach the method completely: 3 to 5 steps, each with its exact how, no theory between steps. If a step needs a sales page to complete, the email fails.',
      'Name the step everyone skips as its own beat. That beat is why the save happens.',
      'The shortcut is one line, placed after the full teaching. Calibration mandatory: say what the method does not fix. Soft CTA only.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'email-story-receipt',
    label: 'Email: Story with the receipt',
    hint: 'Narrative arc, proof embedded mid-story',
    goal: 'clicks',
    whyItWorks: [
      'A story earns the read; the receipt embedded mid-arc converts the read into belief, and belief is what clicks.',
      'Proof placed inside the narrative (not bolted on at the end) survives the reader\'s ad filter because it arrives as plot, not pitch.',
      'The arc (scene, turn, receipt, reframe) mirrors how she will tell the story to a friend, which makes the email inherently forwardable.',
    ],
    template: [
      'Subject: {TheStrangeOutcome, in plain words}',
      'Preheader: {HintAtTheReceipt, one line}',
      '',
      '{ColdOpen: the scene, mid-moment, time and place}.',
      '',
      '{WhatHappened: 2-3 short paragraphs, stakes rising}.',
      '',
      '{TheReceipt: the count, the quote, or the before-after, placed as the turning point}.',
      '',
      '{TheReframe: what it means for her, 2 lines}.',
      '{BridgeAndCTA: one honest line to the offer + soft CTA}.',
      '',
      'PS: {EchoReceipt: a second, smaller proof in a different shape}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The form in the trash, signed by nobody',
      'Subject: I counted for 30 days. The number changed our house.',
    ],
    craft: [
      'Open mid-scene and withhold the explanation for at least two paragraphs. The story must stand alone as a good read before any receipt appears.',
      'Place the receipt as the turning point of the story, never in a proof section after it. One receipt in the body; the PS carries the echo in a different shape (quote after number, number after quote).',
      'The bridge to the offer is one honest line. Calibrate: what the receipt does not prove. Soft CTA, link on the words that name the thing.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'story',
        label: 'The story and its receipt (2-3 lines each)',
        placeholder: 'The scene and turn, then the count or quote that proves it.',
        hint: 'the narrative spine and the proof. Keep both true to what you wrote',
        required: true,
      },
    ],
  }),

  F({
    id: 'email-objection-faq',
    label: 'Email: Objection FAQ',
    hint: 'The top 4 objections, answered fairly',
    goal: 'clicks',
    whyItWorks: [
      'Answering the real objections in one email pre-handles the reasons she has not bought, and each answered objection removes a reason to wait.',
      'Fairness is the persuasion: stating each objection so well she nods along makes the answer land as honesty, not spin.',
      'FAQ emails get forwarded to the skeptical partner or friend, which is distribution to exactly the person blocking the yes.',
    ],
    template: [
      'Subject: {TheBiggestObjection, as a question}',
      'Preheader: {AndTheOtherThree, one line}',
      '',
      '{TheFrame: the questions everyone asks before {TheDecision}, stated warmly}.',
      '',
      'Q: {Objection1, in her words}',
      'A: {TheFairAnswer, 2-3 lines, calibration included}',
      '',
      'Q: {Objection2}',
      'A: {TheFairAnswer}',
      '',
      'Q: {Objection3}',
      'A: {TheFairAnswer}',
      '',
      'Q: {Objection4}',
      'A: {TheFairAnswer}',
      '',
      '{TheClose: what is true no matter what she decides}.',
      'PS: {SoftCTA: where to see the answers in full + the link}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: "Will I actually use it?"',
      'Subject: Four questions before the $7 page',
    ],
    craft: [
      'Pick the 4 objections she actually has (time, will I use it, is it physical, will it work for my house), stated in her exact words, never softened into strawmen.',
      'Every answer is 2 to 3 lines and includes the honest limit of the answer. The calibration is what makes the set believable.',
      'Close on what is true either way (the load is real, and it deserves a system), then the PS carries the soft CTA. No pressure anywhere.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'email-honest-last-call',
    label: 'Email: Honest last call',
    hint: 'The deadline email that stays kind',
    goal: 'clicks',
    whyItWorks: [
      'A real deadline, stated once and honestly, converts the fence-sitters that a week of offers could not, because waiting finally has a cost.',
      'Kindness in the close (permission to pass, no shame either way) protects the list relationship that the next launch depends on.',
      'Recapping the exact offer in its simplest form removes the last friction: she decides on one clear page, not a fog of options.',
    ],
    template: [
      'Subject: {TheDeadline, plainly: closes tonight / ends Friday}',
      'Preheader: {WhatEnds, and what it costs, one line}',
      '',
      '{TheReminder: what the offer is and who it is for, 3 short lines}.',
      '',
      '{TheRecap: the 3 things she gets, one line each}.',
      '',
      '{TheHonestDeadline: what changes after the deadline, stated as fact}.',
      '',
      '{ThePermission: it is genuinely okay to pass, and here is who should}.',
      '',
      '{CTA: direct, warm, price included}.',
      'PS: {TheQuestion: the one-question reply invite for the undecided}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The founder price ends tonight',
      'Subject: Last note about the Sunday system (for now)',
    ],
    craft: [
      'The deadline must be real and stated as fact, once. Fake urgency is the one line this brand never crosses.',
      'Recap the offer in 3 lines maximum, then name who should pass and mean it. The disqualifier is what makes the CTA trustworthy.',
      'CTA direct and warm with the price in it. The PS invites the undecided to reply with one question, and answering it fast is part of the play.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'email-quick-win',
    label: 'Email: The quick win',
    hint: 'One 5-minute win, reply-bait close',
    goal: 'saves',
    whyItWorks: [
      'A win she can get in 5 minutes today is the fastest proof that opening these emails pays, which trains the open habit every sender lives on.',
      'Small wins get reported back, and "I did it" replies are both deliverability gold and the warmest audience research there is.',
      'The quick win demonstrates the system\'s logic in miniature, so the paid version reads as more of a good thing, not a risk.',
    ],
    template: [
      'Subject: The {TimeCost} fix for {TheAnnoyance}',
      'Preheader: {TheWin, promised in one line}',
      '',
      '{TheSetup: the tiny annoying thing, named in one line}.',
      '',
      'Do this tonight ({TimeCost}):',
      '1. {MicroStep, verb first}',
      '2. {MicroStep}',
      '3. {MicroStep}',
      '',
      '{WhatChanges: the immediate effect, honestly stated}.',
      '{WhyItWorks: the mechanism, 2 lines}.',
      '',
      '{ReplyBait: try it and tell me what happened, I read every reply}.',
      'PS: {SoftBridge: the system holds 40 of these}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The 5-minute fix for the 3 am remembering',
      'Subject: Do this at 5 pm today, thank me at 7',
    ],
    craft: [
      'One win, 5 minutes or less, tonight. Three micro-steps maximum, each executable with what she already has.',
      'State the effect honestly and immediately (what tonight looks like after), then the mechanism in 2 lines so the win teaches the logic, not just the trick.',
      'The close is the reply invite, and the replies get answered. The PS bridges to the system in one soft line, never harder.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'email-open-loop-tease',
    label: 'Email: Open-loop tease',
    hint: 'Today teases tomorrow',
    goal: 'follows',
    whyItWorks: [
      'An unresolved question at the end of a good email makes tomorrow\'s open nearly automatic, and habitual opens compound into list health.',
      'Teasing works because it respects the reader: give today\'s value in full, then open a loop only tomorrow can close.',
      'Sequence glue emails raise the read rate of the emails around them, including the offers, without spending a sales beat.',
    ],
    template: [
      'Subject: {TodaysValue, plainly}',
      'Preheader: {PlusTheTease: and the thing I found out}',
      '',
      '{TodaysTeaching: the promised value, complete in 3-5 short beats}.',
      '',
      '{TheTurn: the one thing that surprised you while writing this}.',
      '',
      '{TheLoop: the question or result you will open with tomorrow, withheld cleanly}.',
      '',
      '{TomorrowLine: exactly what tomorrow\'s email answers, and when it lands}.',
      'PS: {TheBreadcrumb: one clue, no more}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The 20-minute download, plus what happened on day 4',
      'Subject: Three rules that run our week (and the one that broke)',
    ],
    craft: [
      'Today\'s value must be complete on its own. The tease is the seasoning, never the meal, and never a reason to skip today.',
      'Withhold the loop cleanly: name what tomorrow answers, not the answer. One loop only; two loops is a mess.',
      'Say when tomorrow lands and keep the promise. The PS leaves one breadcrumb, calibrated so it intrigues without spoiling.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'email-ps-close',
    label: 'Email: The P.S. close',
    hint: 'Soft body, the postscript sells',
    goal: 'clicks',
    whyItWorks: [
      'The P.S. is the second most-read element in any email, so placing the offer there catches both skimmers and the sold-on-principle reader.',
      'A body that sells nothing earns the trust that makes the PS land: the reader finishes feeling served, then meets the offer as a bonus, not a bait.',
      'The format lets one email do two jobs (nurture and convert) without either contaminating the other.',
    ],
    template: [
      'Subject: {TheSoftTopic, plainly}',
      'Preheader: {TheWarmLine, never the offer}',
      '',
      '{TheSoftBody: one story, lesson, or validation, complete in 3-5 short paragraphs. No offer, no link}.',
      '',
      '{TheSignoff: warm, first name}.',
      '',
      'PS: {TheOffer: what it is, who it is for, the price, and the link, in 2-3 plain lines}.',
      'PPS: {TheReceipt or the honest disqualifier, one line}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: Nobody claps when the forms get signed',
      'Subject: You carried a whole small economy today',
    ],
    craft: [
      'The body must be complete and valuable with zero selling. If a link appears before the PS, the format collapses into an ordinary pitch.',
      'The PS is 2 to 3 plain lines: what it is, who it is for, price, link. No hype, no countdown.',
      'The PPS carries the calibration: a receipt, or the honest line about who should skip it. That is what keeps the PS trustworthy.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  /* ------------------------------------------------------------------ */
  /* emlf- ultra-long-form value essays, round 5. The lf- register,      */
  /* translated to the inbox: chaptered, saveable, worth the scroll.     */
  /* ------------------------------------------------------------------ */

  F({
    id: 'emlf-ultimate-guide',
    label: 'Email essay: The ultimate guide',
    hint: 'The definitive guide in one send',
    goal: 'saves',
    whyItWorks: [
      'The definitive email on one topic becomes the one she saves, stars, and forwards, and saved emails keep delivering long after the send.',
      'Chaptered structure makes a long email skimmable, and skimmable long emails get read more, not less, because she trusts what she can navigate.',
      'Completeness is the authority play: covering fundamentals, method, and pitfalls in one send positions the sender as the reference desk.',
    ],
    template: [
      'Subject: The complete guide to {Topic} ({Qualifier: this year / one read})',
      'Preheader: {WhatSheCanDoAfter: the one-line outcome}',
      '',
      '{TheAnswer, first: the core question answered completely in 2-3 sentences, written to be quoted}.',
      '',
      'Part 1: The fundamentals - {WhatEveryoneGetsWrong, corrected}.',
      'Part 2: The method - {TheCoreSystem, step by step, each step with its how}.',
      'Part 3: The pitfalls - {The4-6 ways this fails, and the fix for each}.',
      'Part 4: The one that matters most - {TheKeystone, expanded}.',
      '',
      '{TheOneThing: what to do this week}.',
      'PS: {SoftCTA: the system that holds all of this + save this email}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The complete guide to the mental load, in one read',
      'Subject: Everything about the Sunday reset (finally, in one place)',
    ],
    craft: [
      'Answer the core question completely in the first 3 sentences, before any throat-clearing. The open must be quotable on its own.',
      'Four chapters maximum, each with a plain-word header. The method chapter carries the how; the pitfalls chapter is where the authority lives.',
      'Long is allowed, padding is not: every paragraph must teach, correct, or warn. Close with this week\'s one action and the save invite. Soft CTA last.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'emlf-deep-dive',
    label: 'Email essay: The deep dive',
    hint: 'One system, taught start to finish',
    goal: 'saves',
    whyItWorks: [
      'Going all the way down on one system is rarer than a dozen tips, and rarity is what makes an email worth saving and sending.',
      'A start-to-finish teaching proves the system actually works as a system, which tips can never demonstrate.',
      'The reader who runs the dive and gets the result becomes the warmest possible audience for the paid version.',
    ],
    template: [
      'Subject: {TheSystem}, from zero to running, in one email',
      'Preheader: {TheOutcome, with the honest time cost}',
      '',
      '{WhyThisSystem: the one paragraph case, with the receipt}.',
      '',
      'The setup (5 minutes): {TheSetup, exactly}.',
      '',
      'The first run: {StepByStep: the whole first run, 4-6 beats, each with its how}.',
      '',
      'Where it breaks: {The2-3 honest failure points, and the adjustment for each}.',
      '',
      'Week 2 and beyond: {WhatToAdd once the basics hold}.',
      '',
      '{TheInvite: run it this week and tell me how it went}.',
      'PS: {SoftCTA: the done-for-you version, one line}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The one-page house, from zero to running, in one email',
      'Subject: The full weekly download: setup, first run, and the parts that break',
    ],
    craft: [
      'Teach one system start to finish: setup, first run, failure points, what comes next. Nothing held back for a sales page.',
      'The where-it-breaks section is mandatory and honest. A dive without the failure points is an ad, and the reader can tell.',
      'Close with the run-it-and-report invite, then one soft line on the done-for-you version. The teaching is the pitch; let it be.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'emlf-research-report',
    label: 'Email essay: The research report',
    hint: 'We counted, here is what it means',
    goal: 'shares',
    whyItWorks: [
      'Original data is the most forwarded content type in any inbox because sending it makes the forwarder look smart.',
      'A counted truth, even a small one, outperforms a big opinion because it is falsifiable, quotable, and impossible to argue with politely.',
      'Report emails position the sender as the research desk for this conversation, which compounds authority send after send.',
    ],
    template: [
      'Subject: We counted {TheThing} for {Period}. Here is what.',
      'Preheader: {TheSurpriseFinding, one line}',
      '',
      '{TheMethod: what we counted and how, 3 lines, so skeptics have nothing to grab}.',
      '',
      'The findings:',
      '1. {Finding: the number, then what it means}',
      '2. {Finding: the one nobody expected}',
      '3. {Finding}',
      '4. {Finding}',
      '',
      '{TheSoWhat: the structural point, one short paragraph}.',
      '{TheTakeaway: what she can do with this, 2 lines}.',
      '',
      '{ForwardLine: send this to the person who argues about this with you}.',
      'PS: {MethodNote + soft CTA}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: We counted every invisible task in 40 houses for a month',
      'Subject: 30 days of tracking who remembers what. The chart tells a story.',
    ],
    craft: [
      'Open with the act of counting and the window. The methodology is the flex, and 3 lines of it disarms the skeptics.',
      'Every finding is a number plus its meaning. Lead the list with the finding that reframes, not the one that confirms.',
      'The so-what is structural (the system, not her). End with the forward line aimed at the debate already happening in her house. Calibrate what the count cannot prove.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'emlf-masterclass',
    label: 'Email essay: The free masterclass',
    hint: 'A full class in one email',
    goal: 'saves',
    whyItWorks: [
      'Giving a complete class away in one email is the loudest proof of expertise a sender can make, and proof is what converts readers into buyers later.',
      'Class structure (concept, demonstration, common mistakes, your turn) holds attention through a long email because each section has a job.',
      'A reader who finishes a masterclass has self-selected as serious, which is exactly who the ascension offers are for.',
    ],
    template: [
      'Subject: A free masterclass: {TheSkill} ({TimeCost} read)',
      'Preheader: {WhatSheWillBeAbleToDo, one line}',
      '',
      '{TheConcept: the idea that makes the skill make sense, one short section}.',
      '',
      'The demonstration: {WalkTheSkill: 4-6 beats on a concrete example, every beat shown}.',
      '',
      'The 3 mistakes everyone makes first: {MistakeList: each with the fix}.',
      '',
      'Your turn: {TheExercise: the 20-minute rep she can do today, exactly specified}.',
      '',
      '{TheGraduation: what good looks like after one week of reps}.',
      'PS: {SoftCTA: the system that runs the reps with her}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: A free masterclass in the weekly download (12-minute read)',
      'Subject: Class is in session: how to place a whole week on one page',
    ],
    craft: [
      'Structure it like a class: concept, demonstration, mistakes, her turn. Each section must earn its place; cut any paragraph that does not teach.',
      'The demonstration runs on one concrete example from start to finish, not a montage of tips. Specificity is the teaching.',
      'The exercise is fully specified (time, tools, exact steps) so she can do it today. Close on what good looks like after a week, calibrated, then the soft CTA.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'emlf-encyclopedia',
    label: 'Email essay: The encyclopedia entry',
    hint: 'The reference she saves forever',
    goal: 'saves',
    whyItWorks: [
      'A true reference email (the definitions, the list, the table) is the single most saved email shape there is, because its value never expires.',
      'Being the saved reference means being re-opened for months, and every re-open is a free impression for the sender\'s name.',
      'Encyclopedic completeness on one narrow topic beats breadth: the narrow reference is the one that gets forwarded into every related debate.',
    ],
    template: [
      'Subject: {TheTopic}, the complete reference (save this one)',
      'Preheader: {WhatIsInside, in one line}',
      '',
      '{TheDefinition: the term or system defined precisely, 2-3 sentences, written to be quoted}.',
      '',
      'The parts:',
      '- {Part: named, defined in one line, with its role}',
      '- {Part}',
      '- {Part}',
      '- {Part}',
      '',
      'The table everyone asks for:',
      '{TheTable: the comparison, the list, or the cheat sheet, laid out cleanly}.',
      '',
      '{TheEdgeCases: the 2-3 questions everyone asks next, answered in one breath each}.',
      '',
      '{SaveLine: this is the one to keep}.',
      'PS: {SoftCTA: the page that holds all of this}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The mental load, defined: every part, one reference',
      'Subject: The complete cheat sheet for the weekly download (save this)',
    ],
    craft: [
      'Narrow the topic until the entry can be genuinely complete. A complete small reference beats an incomplete big one every time.',
      'The table or cheat sheet is the payload: lay it out so it survives copy-paste into a notes app. Plain text tables, aligned with spaces.',
      'Answer the next 2-3 questions in one breath each, then the save line. The email should never need a follow-up. Soft CTA in the PS only.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'emlf-serial-chapter',
    label: 'Email essay: Serial chapter one',
    hint: 'The story that continues next week',
    goal: 'follows',
    whyItWorks: [
      'A serial turns one good email into a habit: readers who finish chapter one open chapter two at rates no campaign can buy.',
      'Narrative non-fiction in chapters (the experiment, the rebuild, the count) earns the deepest attention the inbox offers, because story outranks advice.',
      'Each chapter ends on a genuine cliffhanger, which makes the next send anticipated mail instead of another newsletter.',
    ],
    template: [
      'Subject: Chapter 1: {TheChapterTitle, intriguing and plain}',
      'Preheader: {ThePremise: what this series follows, one line}',
      '',
      '{ThePremise: what I am doing for {Period} and why, 2 short paragraphs}.',
      '',
      '{ChapterOne: the first scene or the first week, told fully, 4-6 beats}.',
      '',
      '{TheComplication: the thing that already went wrong, honestly}.',
      '',
      '{TheCliffhanger: the question chapter 2 must answer, withheld cleanly}.',
      '',
      '{SeriesNote: when chapter 2 lands, and what to do if you missed the premise}.',
      'PS: {TheBreadcrumb: one detail from next week, no more}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: Chapter 1: Thirty days without the second calendar',
      'Subject: Chapter 1: The week I tracked everything',
    ],
    craft: [
      'Chapter 1 carries the premise and the first full scene. It must satisfy on its own while making chapter 2 necessary.',
      'Include the honest complication early. A serial where nothing goes wrong is a brochure, and readers feel it.',
      'The cliffhanger is a real question, not a tease trick, and chapter 2 must answer it in the open. Say exactly when it lands and keep the date.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  /* ------------------------------------------------------------------ */
  /* embuy- purchase + OTO nurture, round 5. Mapped to the email trigger */
  /* taxonomy (purchase, upsell_purchase, refund): every purchase gets a  */
  /* next-offer nurture and a deep nurture follow-up; OTO buyers get     */
  /* their own welcome and ascension path.                               */
  /* ------------------------------------------------------------------ */

  F({
    id: 'embuy-welcome-receipt',
    label: 'Buyer: The welcome receipt',
    hint: 'Confirmation that activates',
    goal: 'clicks',
    whyItWorks: [
      'The purchase confirmation is the single most-opened email a brand ever sends, so it must do more than receipt: it must start the result.',
      'Affirming the decision in the first three lines kills buyer\'s remorse before it forms, and remorse is what refunds are made of.',
      'One clear first move, given while excitement is high, converts a buyer into a user, and users become the proof every future email cites.',
    ],
    template: [
      'Subject: You are in: {TheProduct} (+ your first move)',
      'Preheader: {AccessLine: where everything lives, one line}',
      '',
      '{TheAffirmation: what she just did and why it was the right call, 2-3 warm lines}.',
      '',
      'Your access:',
      '- {TheThing: what she gets, with the link}',
      '- {TheBonus, if any, with the link}',
      '',
      'Your first move (tonight, {TimeCost}): {TheFirstMove: the single smallest action that produces a win}.',
      '',
      '{WhatHappensNext: the 2-3 emails coming and why each is worth opening}.',
      '',
      '{Signoff, founder name}.',
      'PS: {SupportLine: hit reply if anything is confusing, a human answers}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: You are in: the Sunday system (+ your first move tonight)',
      'Subject: It is official: your page is ready (start here)',
    ],
    craft: [
      'The first 3 lines affirm the purchase warmly and specifically. No upsell, no second offer anywhere in this email.',
      'Access links come next, then exactly one first move sized for tonight. Two moves is a chore; one move is a win.',
      'Set expectations for the next 2-3 emails by name so they get opened. The PS promises a human in the replies, and the replies get answered.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'purchase',
        label: 'What she bought (name + what is inside)',
        placeholder: 'The Sunday reset system: the one-page download, the fridge version, the setup guide.',
        hint: 'the receipt. Name the product and its parts exactly',
        required: true,
      },
    ],
  }),

  F({
    id: 'embuy-first-win',
    label: 'Buyer: The first win',
    hint: 'Day-1 activation in 20 minutes',
    goal: 'clicks',
    whyItWorks: [
      'A buyer who gets a result in the first 24 hours never refunds, because the purchase has already paid for itself in her mind.',
      'Activation emails convert buyers into practitioners, and practitioners produce the receipts and testimonials the whole funnel runs on.',
      'Walking her through the first win (instead of pointing at the member area and waving) is the highest-leverage service email there is.',
    ],
    template: [
      'Subject: Your first win takes {TimeCost} (start here)',
      'Preheader: {TheWin, promised in one line}',
      '',
      '{TheNudge: the warm line about the thing still in the wrapper}.',
      '',
      'Do this today ({TimeCost}):',
      '1. {Step: open {TheThing} to {TheExactPlace}}',
      '2. {Step: the one action that produces the win}',
      '3. {Step: the lock-in move that makes it stick}',
      '',
      '{WhatItFeelsLike: the moment it works, honestly described}.',
      '{IfStuck: the one place everyone hesitates, and the answer}.',
      '',
      '{ReportBack: reply and tell me your win, I read every one}.',
      'PS: {TomorrowLine: what tomorrow\'s email adds}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: Your first win takes 20 minutes (start here)',
      'Subject: Today: the 20-minute download, together',
    ],
    craft: [
      'One win, sized for today, walked through step by step with the exact place to click or page to open. Never "explore the member area".',
      'Name the moment it works so she recognizes it, then pre-answer the one spot everyone hesitates.',
      'The close is the report-back invite, and the replies become tomorrow\'s proof. No new offer anywhere; activation is the whole job.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'embuy-next-offer-seed',
    label: 'Buyer: The next-offer seed',
    hint: 'The nurture bridge to what is next',
    goal: 'clicks',
    whyItWorks: [
      'A buyer who just got a win is the warmest audience a brand has, and the bridge email plants the next offer while the win is still warm.',
      'Seeding (naming the next problem the purchase revealed) makes the next offer feel like her idea, which converts at multiples of a cold pitch.',
      'The bridge keeps the buyer journey coherent: every product answers the question the last one raised, so ascension reads as care, not extraction.',
    ],
    template: [
      'Subject: Now that {TheWin} is handled',
      'Preheader: {TheNextProblem, named in one line}',
      '',
      '{TheCelebration: the win she just got, named specifically}.',
      '',
      '{TheReveal: what the win reveals: the next problem, stated as the natural consequence of the first one being solved}.',
      '',
      '{WhyItIsNext: 2-3 lines on why this is the order that works, with the receipt or the logic}.',
      '',
      '{TheSeed: what exists for exactly this, one calm paragraph}.',
      '',
      '{CTA: soft-direct, see if it fits, price honest}.',
      'PS: {NoPressureLine: it is there when she is ready, and here is what is coming either way}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: Now that Sunday is handled',
      'Subject: The thing the one-page house shows you next',
    ],
    craft: [
      'Celebrate the specific win first, then reveal the next problem as the natural consequence of solving the first. The seed is planted by the logic, not by urgency.',
      'Name the next offer plainly: what it is, who it is for, the honest price. One paragraph, no stack, no bonuses theater.',
      'The CTA is see-if-it-fits, and the PS explicitly removes pressure (it will be there when she is ready) while naming what free value comes next. Calibration over conversion, always.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'offer',
        label: 'The next offer this email points to',
        placeholder: 'The Ascension pack: the full year of weekly systems, $27, for buyers of the Sunday reset.',
        hint: 'the seeded offer. Name it, price it honestly, and bridge from her win',
        required: true,
      },
    ],
  }),

  F({
    id: 'embuy-deep-nurture-arc',
    label: 'Buyer: Deep nurture follow-up',
    hint: 'Value that keeps buyers warm for what is next',
    goal: 'saves',
    whyItWorks: [
      'Buyers who keep receiving real value after the sale stay warm for the next launch, and warm buyers are the cheapest revenue there is.',
      'Deep nurture (teaching the advanced layer of what she bought) increases the value of her purchase retroactively, which compounds loyalty.',
      'The follow-up arc turns one product into an ongoing relationship, so the next offer lands as a chapter, not a cold open.',
    ],
    template: [
      'Subject: {TheAdvancedLayer: the part of {TheProduct} most people never reach}',
      'Preheader: {WhatItUnlocks, one line}',
      '',
      '{TheContext: she is weeks in now; name what is probably true for her}.',
      '',
      'The next layer:',
      '1. {AdvancedMove: beyond the basics, with the how}',
      '2. {AdvancedMove: the one that changes the weekly rhythm}',
      '3. {AdvancedMove: the quiet one that compounds}',
      '',
      '{TheCaseStudy: one buyer who runs the advanced layer, with the receipt}.',
      '',
      '{TheGentleBridge: what this layer points to next, one honest line}.',
      'PS: {SoftCTA or pure value close, whichever fits the moment}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The part of the Sunday system most people never reach',
      'Subject: Week 4: the layer under the download',
    ],
    craft: [
      'Teach the advanced layer of what she already owns: 2 to 3 moves beyond the basics, each with its how. This email is value first; the bridge is one honest line.',
      'Anchor with one real buyer story and its receipt. The case study proves the advanced layer is lived, not theoretical.',
      'The gentle bridge names what this points to next without pitching it. Some sends end pure value, no CTA at all; that restraint is what keeps buyers warm.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'offer',
        label: 'The offer this nurture arc eventually points to',
        placeholder: 'The Ascension pack, mentioned only as the one-line bridge at the end.',
        hint: 'the destination. The email teaches the advanced layer; the offer is the one-line bridge',
        required: true,
      },
    ],
  }),

  F({
    id: 'embuy-oto-welcome',
    label: 'Buyer: The OTO welcome',
    hint: 'The premium receipt, what changed',
    goal: 'clicks',
    whyItWorks: [
      'An upsell purchase is a bigger vote of trust, and the welcome email must honor it with proportionate specificity, or remorse hits harder at the higher price.',
      'Naming exactly what the OTO adds (and what it does not) prevents the confused-about-what-they-bought support spiral before it starts.',
      'A premium welcome that delivers a first premium win fast turns the OTO buyer into the funnel\'s strongest proof source.',
    ],
    template: [
      'Subject: Welcome to {TheOTO}: here is what just changed',
      'Preheader: {ThePremiumWin, promised in one line}',
      '',
      '{TheHonor: what she did and what it says about how serious she is, 2-3 warm lines, no flattery inflation}.',
      '',
      'What you have now:',
      '- {TheCore: the original product, one line}',
      '- {TheOTO: the upgrade, named with its 2-3 specific additions and links}',
      '',
      'Start here ({TimeCost}): {ThePremiumFirstMove: the first thing only the OTO makes possible}.',
      '',
      '{WhatNotToWorryAbout: the 2 things the OTO does not change, honestly}.',
      '',
      '{Signoff, founder name}.',
      'PS: {SupportLine: reply with anything unclear, priority answers}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: Welcome to the Ascension pack: here is what just changed',
      'Subject: You went premium: start with this one thing',
    ],
    craft: [
      'Honor the bigger yes with specifics, not superlatives. List exactly what the OTO adds over the core product, with access links, in 2-3 lines each.',
      'Give one premium first move that only the upgrade makes possible, sized for tonight.',
      'Name what the OTO does not change, honestly. That calibration is what prevents remorse at the higher price. No further offer in this email.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'purchase',
        label: 'What she bought (core + the OTO upgrade)',
        placeholder: 'The Sunday reset (core) plus the Ascension pack (OTO): the year of weekly systems and the monthly audits.',
        hint: 'the receipt. Name core and upgrade exactly, with the additions',
        required: true,
      },
    ],
  }),

  F({
    id: 'embuy-oto-ascend',
    label: 'Buyer: OTO ascension',
    hint: 'From the upgrade to what is next',
    goal: 'clicks',
    whyItWorks: [
      'The OTO buyer has demonstrated she buys solutions to problems she feels, so the ascension email that names the next problem honestly converts at the highest rate in the funnel.',
      'Framing the next step as completing the system she started (not a new purchase) respects the investment she has already made.',
      'Ascension done with full transparency (what she has, what the next adds, the honest price) builds the lifetime buyer, which is the whole point of the chain.',
    ],
    template: [
      'Subject: The last piece of the {TheSystem} puzzle',
      'Preheader: {WhatCompletes, one line}',
      '',
      '{TheRecap: what she has now, core plus OTO, and what it already does for her, 3 lines}.',
      '',
      '{TheGap: the one thing the current stack does not cover, stated precisely, with the moment she will feel it}.',
      '',
      '{TheCompletion: what exists for exactly that gap, one calm paragraph, with the receipt or the case study}.',
      '',
      '{TheMath: the honest price and the value framing, 2 lines}.',
      '',
      '{CTA: direct, warm, see if it completes your set}.',
      'PS: {TheDisqualifier: who should skip this, honestly}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The last piece of the one-page house',
      'Subject: What your Ascension pack does not cover (yet)',
    ],
    craft: [
      'Recap her stack first so the email reads as service, not sales. The gap must be real and precisely named, with the moment she will feel it.',
      'Present the completion with a receipt or a case study, then the honest math. No bonuses theater, no countdown.',
      'The CTA is see-if-it-completes, and the PS names who should skip it. The disqualifier is what keeps the ascension chain trustworthy.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'offer',
        label: 'The offer that completes the stack',
        placeholder: 'The Audit: a quarterly systems review, $47, for Ascension pack members who want eyes on their setup.',
        hint: 'the completion offer. Name the gap it fills and price it honestly',
        required: true,
      },
    ],
  }),

  F({
    id: 'embuy-refund-save',
    label: 'Buyer: The refund save',
    hint: 'Gracious, fix-it, win-back path',
    goal: 'replies',
    whyItWorks: [
      'A refund request handled graciously is the highest-leverage save there is: a fair ask plus a real fix recovers both the sale and the relationship.',
      'Most refunds are friction, not regret: confusion, a missing link, an unmet expectation. Each has a specific fix, and the fix is the save.',
      'Even when the refund stands, the gracious path keeps the door open, and refunded-but-respected buyers return at surprising rates.',
    ],
    template: [
      'Subject: About your refund request (read this first)',
      'Preheader: {TheOpenDoor: one warm line}',
      '',
      '{TheGrace: thank her for saying something, no defensiveness, 2 lines}.',
      '',
      '{TheAsk: what specifically did not work, asked as a genuine question}.',
      '',
      'If it is {CommonIssue1}: {TheFix, exactly, with the link or the step}.',
      'If it is {CommonIssue2}: {TheFix}.',
      'If it is {CommonIssue3}: {TheFix}.',
      '',
      '{TheOut: and if it is just not for you, here is exactly how the refund works, no hoops}.',
      '',
      '{TheDoor: what stays open either way}.',
      'PS: {TheHumanLine: reply and a person handles this today}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: About your refund request (read this first)',
      'Subject: Before I process that refund',
    ],
    craft: [
      'Open with grace and zero defensiveness. Ask what specifically did not work as a genuine question; the reply is the goal and the research.',
      'Offer the 2-3 specific fixes for the common issues, each with its exact step or link. Then make the refund path explicit and hoop-free; the ease of the out is what makes the fix trustworthy.',
      'Close on what stays open either way (the free emails, the community, the door). Never guilt, never stall, never hide the refund button.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  F({
    id: 'embuy-review-ask',
    label: 'Buyer: The review ask',
    hint: 'The testimonial ask after the first win',
    goal: 'replies',
    whyItWorks: [
      'The moment after her first win is the single best time to ask for the testimonial, because the result is fresh and the goodwill is at its peak.',
      'Framing the ask as helping the next mother decide (not as helping the brand) makes replying feel like generosity, not labor.',
      'Specific asks get specific receipts: asking for the one moment it worked produces quotable proof instead of generic praise.',
    ],
    template: [
      'Subject: {HerWin}, one question about it',
      'Preheader: {TheAsk, hinted warmly}',
      '',
      '{TheCallback: name the win she reported or the milestone she likely hit, specifically}.',
      '',
      '{TheAsk: the one question: what was the exact moment it worked for you?}.',
      '',
      '{WhyYouAreAsking: 2 honest lines: the next mother is where you were, and your line might be the one that helps her decide}.',
      '',
      '{HowToAnswer: just hit reply, 2-3 sentences, no polish needed}.',
      '',
      '{TheThankYou: what her words do, and the gratitude, plainly}.',
      'PS: {ThePermission: and if it has not worked yet, tell me that too, it gets fixed}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: Your first calm Sunday, one question about it',
      'Subject: The moment it worked: would you tell me about it?',
    ],
    craft: [
      'Ask exactly one question (the exact moment it worked) and make answering effortless: hit reply, 2-3 sentences, no polish.',
      'Frame the why as helping the next mother decide. Never offer incentives for praise; ask for the honest version, including what was hard.',
      'The PS invites the it-has-not-worked-yet replies too, and those get fixed first. Every reply gets a personal thank-you.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
  }),

  /* ------------------------------------------------------------------ */
  /* emgoal- goal-driven emails, round 5. The custom-goal family: each   */
  /* declares offer + goal inputs so the CTA fills from the real ask     */
  /* (book a call, attend the event, reply, join).                       */
  /* ------------------------------------------------------------------ */

  F({
    id: 'emgoal-book-call',
    label: 'Goal: Book a call',
    hint: 'The call invite with an honest filter',
    goal: 'clicks',
    whyItWorks: [
      'A call invite that says exactly who it is for and what happens on it books better-fit calls, and better-fit calls are what high-ticket ascension runs on.',
      'The honest disqualifier (who should not book) doubles the credibility of the invite, because a filtered ask reads as service, not a funnel trap.',
      'Lowering the perceived cost of the call (what it is, how long, what she leaves with) converts the curious-but-cautious into bookings.',
    ],
    template: [
      'Subject: {TheCallName}: is this your situation?',
      'Preheader: {WhatSheLeavesWith, one line}',
      '',
      '{TheSituation: describe her exact moment so precisely she feels named, 3-4 lines}.',
      '',
      'On {TheCallName} ({Duration}), we:',
      '- {WhatHappens1: map where the load actually sits}',
      '- {WhatHappens2: find the first system move}',
      '- {WhatHappens3: you leave with the plan, whether or not we work together}',
      '',
      'This is for you if: {TheFit, 2 lines}.',
      'Skip it if: {TheDisqualifier, 1-2 honest lines}.',
      '',
      '{CTA: book a time here, direct and warm}.',
      'PS: {TheCalm: no pitch on the call, and here is the proof}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The Systems Call: is this your situation?',
      'Subject: 20 minutes that maps your whole week (free, genuinely)',
    ],
    craft: [
      'Name her situation so precisely the right reader feels spotted. Then demystify the call: what happens, how long, and what she leaves with even if nothing sells.',
      'The fit and the disqualifier get equal space. The honest filter is the booking engine.',
      'The CTA is one link, direct and warm. The PS kills the pitch fear with proof (what past callers say, or the no-strings promise). Calibrate everything; the call itself is the closer.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'offer',
        label: 'The call or program this invite points to',
        placeholder: 'The Systems Call: a free 20-minute audit that maps to the Ascension program.',
        hint: 'the destination. Name what the call leads to, honestly',
        required: true,
      },
      {
        id: 'goal',
        label: 'The exact goal of this email',
        placeholder: 'Book a free 20-minute Systems Call this week.',
        hint: 'the ask. The CTA section fills from this',
        required: true,
      },
    ],
  }),

  F({
    id: 'emgoal-attend-event',
    label: 'Goal: Attend the event',
    hint: 'Transformation-first invite, logistics second',
    goal: 'clicks',
    whyItWorks: [
      'Events are sold on the transformation they deliver, not the logistics, so the invite that leads with what changes outperforms the one that leads with the agenda.',
      'Naming what she will be able to do afterward (not what she will hear) converts attendance from a calendar cost into an obvious yes.',
      'An honest who-this-is-for section fills the room with the right people, and the right room is what makes the event itself convert.',
    ],
    template: [
      'Subject: {TheEventName}: {TheTransformation, in 4-6 words}',
      'Preheader: {TheWhen, plus the one-line reason to come}',
      '',
      '{TheScene: where she is right now, named precisely}.',
      '',
      'In {TheEventLength}, you will:',
      '- {Takeaway1: the skill or system, usable immediately}',
      '- {Takeaway2: the one that surprises}',
      '- {Takeaway3: the one that pays for the time}',
      '',
      'The details: {TheWhen, the where, the cost or free, the replay answer}.',
      'Come if: {TheFit, 1-2 lines}.',
      '',
      '{CTA: save your seat, direct and warm}.',
      'PS: {TheCloser: the question to reply with if she is on the fence}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The Sunday Reset Workshop: run your week in 20 minutes',
      'Subject: Live: build your one-page house with me (free)',
    ],
    craft: [
      'Lead with the transformation: 3 takeaways, each usable immediately, each concrete. The agenda never sells the event; the after-picture does.',
      'Logistics get one tight block (when, where, cost, replay). Answer the replay question in the same breath; it is the top objection.',
      'The fit line names who the room is for. CTA direct and warm, and the PS invites the fence question by reply. Calibrate: say what the event is not.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'offer',
        label: 'The event (name, date, cost)',
        placeholder: 'The Sunday Reset Workshop, live Thursday 7 pm ET, free, replay for registrants.',
        hint: 'the logistics. Date, cost, and the replay answer',
        required: true,
      },
      {
        id: 'goal',
        label: 'The exact goal of this email',
        placeholder: 'Register for the free workshop and show up live.',
        hint: 'the ask. The CTA section fills from this',
        required: true,
      },
    ],
  }),

  F({
    id: 'emgoal-reply-survey',
    label: 'Goal: The reply ask',
    hint: 'One question, answer-first, research dividend',
    goal: 'replies',
    whyItWorks: [
      'A single genuine question with an answer-first example pulls replies from lurkers, and replies are deliverability gold plus free audience research.',
      'Promising (and delivering) the results back turns a survey into a relationship: she answers, then opens the follow-up to see herself in the data.',
      'The reply ask trains the list that this inbox is a conversation, which lifts the open rate of every email that follows.',
    ],
    template: [
      'Subject: One question (2-minute answer)',
      'Preheader: {MyAnswer, teased in one line}',
      '',
      '{TheContext: why you are asking, 2 honest lines}.',
      '',
      'The question: {TheQuestion: specific, concrete, no wrong answers}?',
      '',
      'My answer: {MyAnswer: honest, slightly exposing, 3-4 lines}.',
      '',
      '{YourTurn: hit reply with yours, one line or ten, I read every one}.',
      '',
      '{TheDividend: what happens with the answers: the report-back, named with its date}.',
      'PS: {TheNudge: even a one-word answer counts}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: One question: what is the form that broke you?',
      'Subject: What time did you first think about dinner today?',
    ],
    craft: [
      'One question, specific and concrete, with no wrong answers. Two questions halves the replies; ask one.',
      'Answer it yourself first, honestly and slightly exposed. The answer-first is what makes replying feel safe.',
      'Name the report-back and its date, then actually send it. The follow-up email (here is what you all said) is where the relationship compounds.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'goal',
        label: 'The exact goal of this email',
        placeholder: 'Get replies to the one question, then report the results back Friday.',
        hint: 'the ask and the dividend. The question and report-back fill from this',
        required: true,
      },
    ],
  }),

  F({
    id: 'emgoal-community-join',
    label: 'Goal: Join the community',
    hint: 'Belong-first, one clear first action',
    goal: 'clicks',
    whyItWorks: [
      'Community invites that sell belonging (the room, the rhythm, the people like her) outperform invites that sell content, because she has content; she is lonely.',
      'One clear first action after joining is what turns a new member into a participant, and participants renew.',
      'Showing the existing members\' words does the convincing: the community sells itself when its warmth is visible.',
    ],
    template: [
      'Subject: {TheCommunityName}: the room where {TheSharedThing}',
      'Preheader: {WhatHappensInside, one line}',
      '',
      '{TheLoneliness: name the specific isolation of carrying this alone, 2-3 lines}.',
      '',
      'Inside {TheCommunityName}:',
      '- {TheRhythm: what happens weekly, plainly}',
      '- {ThePeople: who is in the room, described by situation, not demographics}',
      '- {TheMemberWords: one real line from a member, quoted}.',
      '',
      'Your first move after joining: {TheFirstAction: the one post or ritual that makes her a participant}.',
      '',
      '{TheDetails: cost, doors, the honest who-it-is-not-for}.',
      '{CTA: come in, direct and warm}.',
      'PS: {TheWelcome: what happens the day she joins}.',
    ].join('\n'),
    exampleHooks: [
      'Subject: The Sunday Table: the room where the load gets named',
      'Subject: You do not have to hold the map alone (literally)',
    ],
    craft: [
      'Lead with belonging: name the isolation precisely, then show the room (rhythm, people, one real member quote). The room sells itself; the email just opens the door.',
      'Give the exact first action she takes after joining so joining feels like a plan, not a purchase.',
      'Details honest: cost, door dates if any, and who it is not for. CTA direct and warm; the PS previews her first day inside.',
    ].join(' '),
    platforms: ['email'],
    formats: ['email'],
    inputs: [
      {
        id: 'offer',
        label: 'The community (name, cost, rhythm)',
        placeholder: 'The Sunday Table: $12/month, weekly download thread plus monthly live reset.',
        hint: 'the room. Name it, price it, and give its weekly rhythm',
        required: true,
      },
      {
        id: 'goal',
        label: 'The exact goal of this email',
        placeholder: 'Join the community this week, doors close Sunday.',
        hint: 'the ask. The CTA section fills from this',
        required: true,
      },
    ],
  }),
];
