/**
 * Prompt bank, round 2: platform-specific ad copy for Facebook, LinkedIn
 * organic frameworks, and the ultra-long-form value-forward set that works
 * across every long surface. Merged into PROMPT_RECIPES in promptBank.ts.
 *
 * Same contract as the base bank: A-level structures with whyItWorks, a
 * fill-in {Slot} template, MotherMode-adapted exemplar openers, direct craft
 * orders, and per-platform notes. Voice rules hold: calibration after bold
 * claims, permission close, no NO-list words, no em dashes, soft CTA (a
 * direct-but-warm CTA on the ad frameworks, where the click is earned).
 */
import type { PromptRecipe } from './promptBank';

const F = (
  r: Omit<PromptRecipe, 'group' | 'builtin'>,
): PromptRecipe => ({ ...r, group: 'framework', builtin: true });

/* ---------------------------------------------------------------------- */
/* Facebook ad copy, round 2. Direct-response structures for the $7 offer, */
/* each engineered for a different buying psychology.                      */
/* ---------------------------------------------------------------------- */

export const PROMPT_RECIPES_ROUND2: PromptRecipe[] = [
  F({
    id: 'fb-ad-question-hook',
    label: 'FB ad: Question hook',
    hint: 'Her 11pm question, answered by the offer',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'A question she has literally asked herself stops the scroll better than any statement, because the brain auto-completes answers.',
      'Questions screen: the right reader self-selects in the first line, which lifts click quality and lowers cost per sale.',
      'Answering the question with a product feels like help, not advertising, which is the whole game on cold traffic.',
    ],
    template: [
      '{HerQuestion: the exact question she asks at 11pm}?',
      '',
      '{ShortAnswer: the honest one-line answer}.',
      '',
      '{TheHow: 2-4 lines on the mechanism that makes the answer true}.',
      '',
      '{ProofLine: the receipt, one line}.',
      'CTA: {Soft, specific}',
    ].join('\n'),
    exampleHooks: [
      'What if the whole house could run on one page and 20 minutes a week?',
      'Why does the mental load only land on one person? And what actually moves it?',
    ],
    craft: [
      'The question must be one she has genuinely asked herself, worded the way she would say it. Never a rhetorical setup.',
      'Answer in one honest line first, then earn the answer with the mechanism. No bait she cannot cash.',
      'One receipt, one soft CTA. The question does the targeting; the answer does the selling.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-stat-shock',
    label: 'FB ad: Stat first',
    hint: 'The number she cannot unsee',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'A single concrete number out-pulls every adjective, because numbers feel like facts and facts stop thumbs.',
      'Leading with data positions the ad as information, which earns the read before the pitch ever starts.',
      'A well-chosen stat pre-frames the problem size, so the offer reads as proportionate instead of optional.',
    ],
    template: [
      '{TheStat: one number, stated plainly}.',
      '',
      '{WhatItMeans: 2-3 lines translating the number into her day}.',
      '',
      '{TheFix: the mechanism that moves the number}.',
      '',
      '{TheOffer: what it is, one line + price}.',
      'CTA: {Direct, warm}',
    ].join('\n'),
    exampleHooks: [
      '23 invisible tasks a day. That is what the count came to when we tracked 40 households for a month.',
      'She makes 35 more decisions before 9 am than anyone else in the house. All day. Every day.',
    ],
    craft: [
      'One number, first line, no warmup. It must be real and defensible: this ad will get screenshot-checked.',
      'Translate the stat into her Tuesday, not into outrage. The meaning section is where the click is won.',
      'The fix is the mechanism, stated once. Price in the offer line. No hype to walk back.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-myth-buster',
    label: 'FB ad: Myth buster',
    hint: 'Kill the advice that fails her',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'Contrarian ads earn the stop because they pick a fight she has already half-won in her own head.',
      'Busting a myth she tried and failed at validates her experience, and validated readers trust the next thing you say.',
      'The myth structure makes the offer the correction, which is a stronger position than the offer as an option.',
    ],
    template: [
      'Myth: {PopularAdvice she has tried}.',
      '',
      'Why it fails: {TheMechanism: 2-3 lines, structural not snarky}.',
      '',
      'What works instead: {TheCorrection: the method, plainly}.',
      '',
      '{TheOffer: the system that runs the correction}.',
      'CTA: {Soft, specific}',
    ].join('\n'),
    exampleHooks: [
      'Myth: you need a better morning routine. The truth: you need fewer things to remember before it starts.',
      'Myth: share the mental load with your partner. Truth: you cannot share what only one person can see.',
    ],
    craft: [
      'Pick a myth she has personally failed at. She should nod before line 2, never feel attacked.',
      'The failure is mechanical, not moral: explain why the advice cannot work, structurally.',
      'The correction is the hero. The offer is simply the correction with a price tag. One line each.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-checklist',
    label: 'FB ad: The checklist',
    hint: 'Everything inside, tick by tick',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'A visible list of deliverables converts "should I" into arithmetic, and arithmetic closes low-ticket sales.',
      'Checklist ads get saved, and saved ads retarget for free for weeks.',
      'Each line is a micro-reason to buy, so the ad works even when she only reads half of it.',
    ],
    template: [
      '{AnchorLine: the whole thing in one line}.',
      '',
      'Inside:',
      '✓ {Deliverable1: named, concrete}',
      '✓ {Deliverable2}',
      '✓ {Deliverable3}',
      '✓ {Deliverable4}',
      '✓ {Bonus: the unexpected extra}',
      '',
      '{PriceLine: the total, framed against one everyday cost}.',
      'CTA: {Direct}',
    ].join('\n'),
    exampleHooks: [
      'Everything that runs our house now fits on one checklist. Here is every line of it.',
      'The whole Sunday reset system, tick by tick: what is inside and exactly how it works.',
    ],
    craft: [
      'Anchor first, then 4-5 named deliverables, each concrete enough to picture. Never "and more".',
      'The bonus lands last in the stack and slightly changes the value math in her favor.',
      'Frame the price against one everyday cost (a drive-thru lunch, the cold coffee) in a single line. Direct CTA.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-founder-note',
    label: 'FB ad: Founder note',
    hint: 'A letter from the person who built it',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'A signed note reads as a person, not a brand, and people buy from people on social.',
      'Founder honesty (why it exists, what it costs, who it is not for) disarms the ad filter entirely.',
      'The note format permits a direct ask that a normal ad could never get away with.',
    ],
    template: [
      'Hi, {FirstName} here.',
      '',
      '{WhyIBuiltThis: the 2-3 line origin, one specific scene}.',
      '',
      '{WhatItDoes: the one outcome, plainly}.',
      '',
      '{WhoItIsNotFor: the honest disqualifier}.',
      '{TheAsk: the direct, warm ask + price}.',
      '',
      '- {Signoff}',
    ].join('\n'),
    exampleHooks: [
      'Hi, Loni here. I built the Brain Dump the year I kept waking up at 3 am remembering permission slips.',
      'A note from the person who made this: it is $7, it is one page, and it is not for everyone.',
    ],
    craft: [
      'Write as the founder, first person, signed. One origin scene with a time and an object, not a resume.',
      'Include the honest disqualifier: who should not buy. It doubles the credibility of who should.',
      'End with the direct ask and the price. Warm, signed, done. No corporate close.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-objection-flip',
    label: 'FB ad: Objection flip',
    hint: 'Her 3 hesitations, answered',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'Naming the hesitation before she does removes it as a reason not to click.',
      'Objection ads convert fence-sitters, which is the cheapest conversion there is on warm and mixed audiences.',
      'Each answered objection is a small trust deposit, and three of them cashes the click.',
    ],
    template: [
      '{OpenLine: the thing everyone hesitates on, said out loud}.',
      '',
      '"{Objection1}"',
      '{TheFlip: the honest 1-2 line answer}.',
      '',
      '"{Objection2}"',
      '{TheFlip}',
      '',
      '"{Objection3}"',
      '{TheFlip}',
      '',
      '{TheClose: what is left once the doubts are gone}.',
      'CTA: {Direct, warm}',
    ].join('\n'),
    exampleHooks: [
      '"I do not have time to set up a system." Setup is 20 minutes, once, on a Sunday. The system holds it from there.',
      '"Will this just become one more thing to maintain?" It replaces the list in your head. It does not add a list.',
    ],
    craft: [
      'Quote the 3 real objections verbatim, in her words: time, money, will-it-stick. No strawmen.',
      'Flip each with facts and mechanism, never with reassurance. Calibration over confidence theater.',
      'The close names what is left when the doubts are gone (usually: the problem, and a $7 way to stop carrying it).',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-price-anchor',
    label: 'FB ad: Price anchor',
    hint: 'The math that makes $7 trivial',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'Price is never evaluated alone; anchoring it against what the problem already costs flips the comparison.',
      'Concrete cost-of-problem math (hours, sleep, forgotten forms) makes the price feel like rounding error.',
      'Anchor ads are the highest-converting structure for warm traffic that already knows the brand.',
    ],
    template: [
      '{CostOfProblem: what carrying this costs her weekly, priced honestly}.',
      '',
      '{TheComparison: 2-3 lines making the cost visible}.',
      '',
      'The fix costs {Price}. Once.',
      '',
      '{WhatSheGets: the 2-3 line value stack}.',
      'CTA: {Direct}',
    ].join('\n'),
    exampleHooks: [
      'The mental load costs you 6 hours a week. The system that gives them back costs $7. Once.',
      'One forgotten form costs the late fee, the email, and the guilt. This costs less than the late fee.',
    ],
    craft: [
      'Price the problem honestly first: hours, fees, sleep. Believable math only, she can smell inflation.',
      'State the price once, plainly, right after the cost. The juxtaposition is the whole ad.',
      'Stack 2-3 concrete deliverables after the price so the comparison lands as value, not as a trick.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-social-proof',
    label: 'FB ad: Proof wall',
    hint: 'Receipts until doubt runs out',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'One testimonial is a claim; five is a pattern, and patterns close.',
      'Proof walls convert the reader who likes the offer but does not trust offers, which is most of cold traffic.',
      'Varied proof (numbers, quotes, screenshots described) speaks to different buying brains in one ad.',
    ],
    template: [
      '{OpenLine: the pattern, one line}.',
      '',
      '"{Quote1: specific result, first name}"',
      '"{Quote2: different shape of result}"',
      '{NumberReceipt: the count, rating, or download figure}.',
      '"{Quote3: the skeptic who converted}"',
      '',
      '{TheCommonThread: what every receipt points at}.',
      'CTA: {Direct, warm}',
    ].join('\n'),
    exampleHooks: [
      'Dana stopped waking up at 3 am. Priya got 6 hours back. 11,432 mothers downloaded the same page.',
      'The reviews say the same sentence 214 different ways: "I did not know it could be like this."',
    ],
    craft: [
      'Stack 3-4 receipts in different shapes: quote, quote, number, skeptic-quote. Variety reads as volume.',
      'Every receipt is specific (a name, a number, a timeframe). Vague praise is anti-proof.',
      'The common thread names what they all point at, in one line. Then the direct CTA. Earned, so take it.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  F({
    id: 'fb-ad-demo-script',
    label: 'FB ad: Demo script',
    hint: 'Hook, watch it work, CTA',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'Showing the thing working outperforms describing it, especially for a system with a visible artifact.',
      'A tight 3-act video ad (hook, demo, CTA) holds attention because every second has a job.',
      'Demo ads pre-answer "what is it exactly", which is the top objection for a $7 digital product.',
    ],
    template: [
      'Hook (0-3s): {ShowTheArtifact: the page, the tick, the calm table} + {OneLineHook}',
      '',
      'Demo (3-20s):',
      '- {Step1: watch it happen, narrated plainly}',
      '- {Step2: the moment it clicks}',
      '',
      'Proof (20-25s): {TheReceipt, one line}.',
      'CTA (25-30s): {What it is, price, where to get it}.',
    ].join('\n'),
    exampleHooks: [
      'Watch one page replace 40 open tabs in 20 seconds.',
      'This is the 20-minute download, sped up. Stay for the part where Sunday stops hurting.',
    ],
    craft: [
      'Open on the artifact working, never on a face talking about it. The first 3 seconds are the demo, not the intro.',
      'Narrate the demo in plain steps: what you are seeing and why it matters, one idea per beat.',
      'Close 5 seconds on the receipt and the CTA together: what it is, the price, the button. Under 30 seconds total.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed', 'reel'],
    platformNotes: {
      facebook: 'Runs as a video ad: captions on, hook frame readable muted, CTA end card holds 2 seconds.',
    },
  }),

  F({
    id: 'fb-ad-one-big-idea',
    label: 'FB ad: One big idea',
    hint: 'A single contrarian truth, fully argued',
    goal: 'clicks',
    kind: 'ad',
    whyItWorks: [
      'One idea argued well beats ten ideas mentioned, because depth reads as authority and authority converts.',
      'A contrarian frame makes the ad feel like content, which earns the read before the pitch appears.',
      'The single-idea structure makes the offer the inevitable conclusion rather than an interruption.',
    ],
    template: [
      '{TheBigIdea: one contrarian sentence, stated as fact}.',
      '',
      '{TheCase: 3-5 short paragraphs arguing it, with one concrete example}.',
      '',
      '{TheTurn: what this means for how she runs her week}.',
      '',
      '{TheOffer: the system built on this exact idea}.',
      'CTA: {Soft, specific}',
    ].join('\n'),
    exampleHooks: [
      'You do not have a time management problem. You have a memory management problem, and those have different fixes.',
      'The most productive thing in your house is not a planner. It is a single visible page.',
    ],
    craft: [
      'Commit to one idea and argue it fully: the mechanism, one lived example, the implication. No second idea.',
      'The case is calm and structural, never a rant. Bold claim, immediate calibration.',
      'The offer arrives as the conclusion of the argument, not as an ad break. One soft CTA at the end.',
    ].join(' '),
    platforms: ['facebook'],
    formats: ['feed'],
  }),

  /* ------------------------------------------------------------------ */
  /* LinkedIn organic, round 2. Professional-register frameworks that   */
  /* translate the mental-load conversation into authority content.      */
  /* ------------------------------------------------------------------ */

  F({
    id: 'li-case-study',
    label: 'LinkedIn mini case study',
    hint: 'One transformation, with numbers',
    goal: 'follows',
    whyItWorks: [
      'Case studies are the most credible content on LinkedIn because they are evidence, not opinion.',
      'A before-during-after with real numbers lets the reader benchmark, which drives saves and profile visits.',
      'One story told well outperforms ten tips, and it quietly demonstrates expertise instead of declaring it.',
    ],
    template: [
      '{TheSubject: who this is about, one line, no names needed}.',
      '',
      'Before: {TheBefore: the measurable starting point}.',
      '',
      'What changed: {TheIntervention: the 2-3 moves, in order}.',
      '',
      'After: {TheAfter: the measurable result, with the timeframe}.',
      '',
      '{TheLesson: the transferable principle, 2 lines}.',
      '{SoftCTA}',
    ].join('\n'),
    exampleHooks: [
      'A household of 5 cut 6 hours of weekly coordination to 20 minutes. Here is exactly what changed.',
      'She tracked every invisible task for 30 days, then rebuilt the week around the count. The numbers inside.',
    ],
    craft: [
      'Anchor every claim in a number: tasks counted, hours returned, weeks measured. No vague transformations.',
      'The intervention is 2-3 specific moves in order, not a montage. The reader should be able to copy the sequence.',
      'Close on the transferable principle and calibrate: what it cost, what help existed, what still is not solved.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['feed', 'article'],
  }),

  F({
    id: 'li-poll-insight',
    label: 'LinkedIn poll insight',
    hint: 'The result, then the takeaway',
    goal: 'replies',
    whyItWorks: [
      'Polls are the cheapest engagement on LinkedIn, and the results post is a second, free wave of reach.',
      'Reporting your own poll data positions you as the research desk for the conversation.',
      'A surprising split invites debate in the comments, which feeds the ranking loop twice.',
    ],
    template: [
      'I asked {Audience} {TheQuestion}. {N} answered.',
      '',
      'The results:',
      '- {OptionA}: {Pct}%',
      '- {OptionB}: {Pct}%',
      '- {OptionC}: {Pct}%',
      '',
      '{TheSurprise: the split nobody expected, and why it happened}.',
      '',
      '{TheTakeaway: what this means, 2-3 lines}.',
      '{QuestionBack: invite the interpretation}',
    ].join('\n'),
    exampleHooks: [
      'I asked 412 working mothers who owns the school forms. 91% said one person, and it is not who you think.',
      'The poll said 3 in 4 households run on one person\'s memory. The comments said the rest.',
    ],
    craft: [
      'Report the poll honestly: question, sample, percentages. Do not round into a story the data did not tell.',
      'The surprise is the hook: lead the takeaway with the split that reframes, not the majority everyone predicted.',
      'End with a question back that professionals can answer in public. The comments are the second post.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['feed'],
  }),

  F({
    id: 'li-doc-teach',
    label: 'LinkedIn document teach',
    hint: 'The swipe-file worth uploading',
    goal: 'saves',
    whyItWorks: [
      'Document posts (PDF carousels) earn the longest dwell time on LinkedIn, and dwell time is the ranking currency.',
      'A teaching arc slide by slide proves expertise structurally, which outperforms any "I am an expert" claim.',
      'Uploads get downloaded, and downloads are the strongest save signal on the platform.',
    ],
    template: [
      'Page 1 (cover): {NumberedPromise: the thing they will learn, plainly}',
      '',
      'Pages 2 to {N-2}: {OneIdeaPerPage: headline + 2-3 lines}',
      '',
      'Page {N-1}: {TheFramework: the whole thing on one page}',
      'Page {N}: {SoftCTA: who made this and where the full version lives}',
      '',
      'Caption: {HookLine} + {WhyThisMatters in 2 lines} + {QuestionBack}',
    ].join('\n'),
    exampleHooks: [
      'The Household Operating System, in 9 pages: the whole framework we use to run a 5-person week.',
      'I turned the 20-minute Sunday download into a 7-page guide. Every step, every script, inside.',
    ],
    craft: [
      'Cover promises one numbered payoff in plain words. If the cover does not earn the swipe, nothing else gets seen.',
      'One idea per page, headline plus 2-3 lines. The second-to-last page is the whole framework on one page, the screenshot slide.',
      'Caption re-hooks and adds the why, never repeats the pages. End with a question the comments can answer.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['carousel', 'feed'],
  }),

  F({
    id: 'li-myth-retirement',
    label: 'LinkedIn myth retirement',
    hint: 'Retire bad professional advice',
    goal: 'replies',
    whyItWorks: [
      'Retiring a piece of conventional wisdom is safe controversy: everyone has suspected it, nobody said it first.',
      'It positions the brand as the calm adult in the discourse, which is the strongest LinkedIn positioning there is.',
      'The retirement format (honor the intent, retire the advice) keeps the take credible instead of edgy.',
    ],
    template: [
      'It is time to retire: {TheAdvice}.',
      '',
      'The intent was good: {WhatItWasTryingToDo, one line}.',
      'But in practice: {WhatItActuallyDoes, 2-3 lines, structural}.',
      '',
      'What to do instead: {TheReplacement: the better practice, plainly}.',
      '',
      '{TheLine: the sentence they quote}.',
      '{QuestionBack}',
    ].join('\n'),
    exampleHooks: [
      'It is time to retire "just communicate more." Communication moves information. It does not move the remembering.',
      'It is time to retire "self-care." The load is structural. A bath does not hold a calendar.',
    ],
    craft: [
      'Honor the intent before retiring the advice. The fairness is what makes the take land as wisdom, not snark.',
      'Explain the structural failure in 2-3 lines: what the advice actually produces at scale.',
      'Offer the replacement practice in the same breath. A retirement without an heir is just complaining.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['feed'],
  }),

  F({
    id: 'li-operating-principle',
    label: 'LinkedIn operating principle',
    hint: 'One rule, one story, one application',
    goal: 'follows',
    whyItWorks: [
      'A named principle is quotable and ownable; people cite principles, not posts.',
      'The story proves the principle was earned in practice, which is the only authority LinkedIn fully trusts.',
      'Ending on the application makes it useful, and useful is what converts a read into a follow.',
    ],
    template: [
      'Operating principle: {ThePrinciple, stated as a rule}.',
      '',
      '{TheStory: the 3-4 line moment that taught it, professional register}.',
      '',
      'What it means in practice:',
      '- {Application1: concrete, this week}',
      '- {Application2}',
      '',
      '{TheLine: the principle restated so it sticks}.',
      '{SoftCTA}',
    ].join('\n'),
    exampleHooks: [
      'Operating principle: if it only exists in one person\'s head, it does not exist.',
      'Operating principle: systems beat memory, every single week.',
    ],
    craft: [
      'State the principle as a rule in line 1, quotable on its own. Everything after is the evidence.',
      'The story is 3-4 lines, professional register, one scene. It proves the reps, never the drama.',
      'Give 2 applications she can run this week. Close by restating the principle in its stickiest form.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['feed'],
  }),

  F({
    id: 'li-week-review',
    label: 'LinkedIn week in review',
    hint: 'Numbered lessons from the week',
    goal: 'saves',
    whyItWorks: [
      'Weekly reviews create appointment reading, and appointment reading compounds followers.',
      'The numbered-lessons format is endlessly repeatable, which makes it a series, not a post.',
      'Lessons framed as earned-in-the-week read as honest authority, the best kind on LinkedIn.',
    ],
    template: [
      'This week taught me {N} things about {Domain}:',
      '',
      '1. {Lesson: stated as a law, one or two lines}',
      '2. {Lesson}',
      '3. {Lesson}',
      '',
      '{TheOneThatStuck: expand the strongest, 2-3 lines}.',
      '',
      '{NextWeek: what I am testing next}.',
      '{QuestionBack: what did your week teach you?}',
    ].join('\n'),
    exampleHooks: [
      'This week taught me 4 things about running a house on systems instead of memory. Number 2 stung.',
      '3 lessons from a week of tracking every invisible task in our house.',
    ],
    craft: [
      '3-5 lessons, each a standalone law with the week\'s evidence folded in. Real lessons, with costs named.',
      'Expand the strongest lesson at the end so the post is not only a list.',
      'Name what you are testing next week: it earns the follow and seeds the next post.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['feed'],
  }),

  F({
    id: 'li-hiring-lens',
    label: 'LinkedIn hiring lens',
    hint: 'If I were hiring for this role',
    goal: 'shares',
    whyItWorks: [
      'The hiring frame converts an invisible job into a visible job description, which is instantly shareable language.',
      'It flatters the reader professionally while making the structural point, a rare double win.',
      'Hiring managers and executives recognize the lens, which carries the post into exactly the right rooms.',
    ],
    template: [
      'If I were hiring for {TheRole}, the job description would read:',
      '',
      '- {Duty1: the invisible work, in executive language}',
      '- {Duty2}',
      '- {Duty3}',
      '',
      'Requirements: {TheAbsurdRequirement: 24/7 availability, no budget, no staff}.',
      'Compensation: {TheTruth: none, and a thank-you if you are lucky}.',
      '',
      '{TheReframe: millions hold this role right now. It has a name}.',
      '{QuestionBack}',
    ].join('\n'),
    exampleHooks: [
      'If I were hiring a Director of Household Operations, the job description would be illegal in 9 states.',
      'Hiring now: someone to hold 40 open loops in their head. Unpaid. Forever.',
    ],
    craft: [
      'Write the invisible job as a real job description, executive language throughout. The translation is the joke and the point.',
      'Land the absurd requirements plainly: no budget, no staff, no off switch. Deadpan, never bitter.',
      'Close on the reframe and the name (default parent, household CEO). Invite the professional comment.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['feed'],
  }),

  F({
    id: 'li-translation-table',
    label: 'LinkedIn translation table',
    hint: 'Corporate speak vs home reality',
    goal: 'shares',
    whyItWorks: [
      'Paired-line translations are the most screenshot-able structure on LinkedIn.',
      'It lets working mothers forward the post as their own explanation, which is the strongest share mechanic there is.',
      'The corporate frame makes the labor legible to the people who undervalue it, without a single accusation.',
    ],
    template: [
      'Corporate translation guide, household edition:',
      '',
      'At work we say: {CorporateTerm1}. At home it is: {TheReality1}.',
      'At work we say: {CorporateTerm2}. At home it is: {TheReality2}.',
      'At work we say: {CorporateTerm3}. At home it is: {TheReality3}.',
      '',
      '{ThePoint: what the translation makes undeniable}.',
      '{QuestionBack: add your own translation}',
    ].join('\n'),
    exampleHooks: [
      'At work we say "stakeholder management." At home it is called remembering everyone\'s everything.',
      'At work we say "on-call rotation." At home it is called being the default parent. There is no rotation.',
    ],
    craft: [
      '3-6 pairs, parallel construction, each one exact. Recognition is the mechanic: she should feel spied on.',
      'The corporate term is real workplace language; the home reality is the same labor without the title.',
      'End on the one-line point, then invite translations. The comments write the sequel.',
    ].join(' '),
    platforms: ['linkedin'],
    formats: ['feed', 'carousel'],
  }),

  /* ------------------------------------------------------------------ */
  /* Ultra long-form, value-forward. Deep structures for the long       */
  /* surfaces (blog, articles, YouTube, threads, email) where depth is  */
  /* the ranking signal and 70%+ of the piece is pure value.            */
  /* ------------------------------------------------------------------ */

  F({
    id: 'lf-ultimate-guide',
    label: 'The ultimate guide',
    hint: 'The pillar page that owns the topic',
    goal: 'saves',
    whyItWorks: [
      'The definitive guide on a topic compounds: it ranks, it gets saved, and it becomes the link everyone cites.',
      'Covering a topic completely signals authority better than any credential line ever written.',
      'Pillar structure (question, fundamentals, method, pitfalls, FAQ) matches how both readers and search engines evaluate completeness.',
    ],
    template: [
      'H1: The Ultimate Guide to {Topic} ({YearOrQualifier})',
      '',
      'Intro: {TheDirectAnswer in 2-3 citable sentences + who this is for}.',
      '',
      'Part 1: The fundamentals - {What everyone gets wrong first}.',
      'Part 2: The method - {TheCoreSystem, taught step by step}.',
      'Part 3: The pitfalls - {The4-6 ways this fails, and the fixes}.',
      'Part 4: The advanced moves - {What to add once the basics hold}.',
      'FAQ: {4-6 question/answer pairs}.',
      '',
      '{Close: the one thing to do this week}.',
      '{SoftCTA: the system that holds all of this}',
    ].join('\n'),
    exampleHooks: [
      'The Ultimate Guide to the Mental Load: what it is, why it lands on one person, and the system that actually moves it.',
      'The Ultimate Guide to the Sunday Reset: the 20-minute version that survives Wednesday.',
    ],
    craft: [
      'Answer the core question in the first 3 sentences, completely, before any throat-clearing. The intro is written to be quoted.',
      'Teach the full method in Part 2, every step with its how. The pitfalls section is where authority lives: name the real failure modes.',
      'Close with one action for this week and the soft CTA. The guide must be worth saving with zero clicks out.',
    ].join(' '),
    platforms: ['blog', 'x', 'linkedin'],
    formats: ['blog', 'article'],
    platformNotes: {
      blog: 'Full pillar treatment: H2 per part, FAQ block for the snippet, internal links from every term that has a sibling post.',
      x: 'As an article: the intro and Part 2 carry the piece, FAQ folds into the final section.',
      linkedin: 'As an article: professional frame, the fundamentals tied to capacity and infrastructure.',
    },
  }),

  F({
    id: 'lf-deep-dive-system',
    label: 'Deep dive: one system',
    hint: 'Teach one system end to end',
    goal: 'saves',
    whyItWorks: [
      'One system taught completely beats five systems mentioned, because completeness is what gets saved and implemented.',
      'A working system demonstrated end to end is the strongest possible proof of expertise.',
      'Readers who run the system and get the result become the next wave of proof, which feeds the content loop.',
    ],
    template: [
      '{HookLine: the outcome this system produces, with the timeframe}.',
      '',
      'Why everything else fails first: {TheFailureMode, 2-3 lines}.',
      '',
      'The system:',
      '1. {Step: what to do + exactly how + what it should feel like}',
      '2. {Step}',
      '3. {Step}',
      '4. {Step}',
      '',
      'Week 1 reality check: {What it actually feels like to start}.',
      'Where it breaks: {The2-3 failure points and the fixes}.',
      '',
      '{TheReceipt: what changed when we ran it}.',
      '{SoftCTA: the done-for-you version}',
    ].join('\n'),
    exampleHooks: [
      'The 20-minute Sunday download, taught completely: the exact system that ends the 3 am remembering.',
      'One page runs our whole house. Here is the entire system, every step, nothing held back.',
    ],
    craft: [
      'Teach ONE system, completely. Every step carries its how and what it should feel like when it works.',
      'Include the week-1 reality and the break points. Honesty about friction is what makes the system believable.',
      'Close with the receipt and the soft CTA: the product holds this system so her memory does not have to.',
    ].join(' '),
    platforms: ['blog', 'youtube', 'x', 'linkedin'],
    formats: ['blog', 'article', 'long'],
    platformNotes: {
      youtube: 'Long-form: chapters per step, the week-1 reality as the mid-video retention beat, the receipt as the close.',
    },
  }),

  F({
    id: 'lf-encyclopedia',
    label: 'The encyclopedia entry',
    hint: 'The definitive reference on one thing',
    goal: 'saves',
    whyItWorks: [
      'Reference content gets saved more than any other type, because it is worth returning to forever.',
      'Defining a term completely makes your page the citation, and citations compound into authority and links.',
      'An organized, exhaustive structure (definition, history, mechanics, types, mistakes, FAQ) is infinitely skimmable.',
    ],
    template: [
      'H1: {TheThing}: the complete reference',
      '',
      'Definition: {TheCrispDefinition in 1-2 sentences}.',
      '',
      'Where it comes from: {TheOrigin: 2-3 lines, factual}.',
      'How it actually works: {TheMechanics, plainly}.',
      'The types: {The3-5 varieties, each with a one-line tell}.',
      'The mistakes: {What people get wrong about it}.',
      'FAQ: {4-6 question/answer pairs}.',
      '',
      '{TheReframe: why understanding it changes what she does next}.',
      '{SoftCTA}',
    ].join('\n'),
    exampleHooks: [
      'The mental load: the complete reference. What it is, why it is invisible, and why systems beat memory.',
      'Default parent: the complete reference, including why the role forms and what actually redistributes it.',
    ],
    craft: [
      'Define the thing crisply in the first 2 sentences. The definition is written to be quoted word for word.',
      'Be exhaustive but organized: every section answers one question. Types and mistakes are the save triggers.',
      'End on the reframe: what she does differently now that she can see it. Soft CTA last.',
    ].join(' '),
    platforms: ['blog', 'pinterest'],
    formats: ['blog', 'article', 'pin'],
    platformNotes: {
      pinterest: 'Condense to the definition, the types, and 3 mistakes in the pin copy; the full reference lives at the link.',
    },
  }),

  F({
    id: 'lf-serial-chapter',
    label: 'Serial chapter one',
    hint: 'A named series, with the map',
    goal: 'follows',
    whyItWorks: [
      'A named series with a visible table of contents converts one post into a follow, because she wants the next chapter.',
      'Chapter 1 that fully delivers on its own earns trust for the whole series.',
      'Series create appointment content, and appointment content is the strongest follower-retention mechanic there is.',
    ],
    template: [
      '{SeriesName}, Part 1: {TheChapterTitle}',
      '',
      '{ThePromise: what this series will teach completely, 2 lines}.',
      '',
      'The map:',
      'Part 1: {ThisChapter}',
      'Part 2: {NextChapter}',
      'Part 3: {Chapter3}',
      'Part 4: {Chapter4}',
      '',
      '{ChapterOneContent: the full first teaching, 4-8 substantial paragraphs or beats}.',
      '',
      '{TheHook: why Part 2 is the one she cannot miss}.',
      '{FollowCTA: follow for Part 2}',
    ].join('\n'),
    exampleHooks: [
      'The Invisible Load, Part 1: why the work no one sees runs on one person\'s memory. A 4-part series.',
      'Systems Week, Chapter 1: the download. Tomorrow, the one-page house. A 5-day build in public.',
    ],
    craft: [
      'Name the series and show the full map up front. The map is the follow mechanic; every title in it must be a promise.',
      'Chapter 1 must be complete on its own: full value, no rationing. The series earns follows by over-delivering early.',
      'End on the specific reason Part 2 is unmissable, then the follow CTA. Never a generic "stay tuned".',
    ].join(' '),
    platforms: ['x', 'facebook', 'linkedin', 'email'],
    formats: ['thread', 'feed', 'article', 'email'],
    platformNotes: {
      email: 'As a sequence: the map becomes the week\'s sending schedule, each part one email with the same skeleton.',
    },
  }),

  F({
    id: 'lf-research-report',
    label: 'The research report',
    hint: 'We counted, here is everything',
    goal: 'shares',
    whyItWorks: [
      'Original research is the most linked and shared long-form content there is, because everyone cites the source.',
      'A full report (method, findings, surprises, implications) positions the brand as the research desk for the niche.',
      'Every finding inside is a standalone post, so one report fuels weeks of content.',
    ],
    template: [
      '{Title: the finding-first headline, e.g. We tracked X for Y. Here is what we found}.',
      '',
      'Method: {What we counted, how, and the window, 3-4 honest lines}.',
      '',
      'The headline findings:',
      '1. {Finding: the number + what it means}',
      '2. {Finding}',
      '3. {Finding}',
      '',
      'The surprise: {ThePatternNobodyPredicted, expanded}.',
      'What this means: {TheImplications, 3-4 lines}.',
      'The limits: {What this data cannot tell us, honestly}.',
      '',
      '{SoftCTA: the system built for what the data shows}',
    ].join('\n'),
    exampleHooks: [
      'We tracked every invisible task in 40 households for 30 days. The full report: 23 a day, and one pattern nobody expected.',
      'The Household Labor Report: what 1,200 logged tasks taught us about how weeks actually run.',
    ],
    craft: [
      'Lead with method honesty: sample, window, and what we did not measure. Credibility is the whole asset.',
      'Every finding is a number plus its meaning, ordered by surprise. The limits section is what makes the rest quotable.',
      'Close on implications and the soft CTA. The report itself is the value; the offer is the response to the data.',
    ].join(' '),
    platforms: ['blog', 'linkedin', 'x'],
    formats: ['blog', 'article', 'thread'],
    platformNotes: {
      x: 'As a thread: method in post 2, one finding per post, the surprise in the second-to-last post, CTA last.',
    },
  }),

  F({
    id: 'lf-masterclass',
    label: 'The free masterclass',
    hint: 'The complete course, given away',
    goal: 'saves',
    whyItWorks: [
      'Giving away the whole method is the highest-converting long-form strategy: the free teaching is the ad.',
      'A masterclass structure (concept, demonstration, exercise, recap) teaches so well that the paid system reads as the obvious upgrade.',
      'Complete free courses get saved, shared, and binged, which trains every algorithm toward the brand.',
    ],
    template: [
      '{Title: the masterclass promise, e.g. Learn the whole system in 20 minutes}',
      '',
      'Module 1: The concept - {TheCoreIdea, taught plainly}.',
      'Module 2: The demonstration - {WatchItWork: the method run live, step by step}.',
      'Module 3: The exercise - {HerTurn: the exact reps to run tonight}.',
      'Module 4: The recap + the edge cases - {TheOnePage version + where it breaks}.',
      '',
      '{Graduation: what she can now do that she could not before}.',
      '{SoftCTA: the system that runs the reps for her}',
    ].join('\n'),
    exampleHooks: [
      'The 20-minute masterclass on the Sunday download: concept, live demo, your turn tonight.',
      'Learn the one-page house in one sitting. Full course, free, nothing gated.',
    ],
    craft: [
      'Teach the whole thing. Module by module: concept, demonstration, exercise, recap. No content held back for the paid tier.',
      'The exercise module is the conversion engine: exact reps she can run tonight with a clear expected result.',
      'Graduation names the new capability, then the soft CTA: the product holds the practice so willpower does not have to.',
    ].join(' '),
    platforms: ['youtube', 'blog'],
    formats: ['long', 'blog', 'article'],
    platformNotes: {
      youtube: 'Chapters as modules, the demonstration is the retention core, the exercise on-screen, recap as the final chapter.',
    },
  }),

  F({
    id: 'lf-book-application',
    label: 'One framework, applied',
    hint: 'A big idea mapped onto her life',
    goal: 'saves',
    whyItWorks: [
      'Applying a known framework to a new domain borrows its authority while proving original thinking.',
      'Chapter-by-chapter application turns abstract theory into instructions she can run, which is the most saved content type.',
      'It attracts both audiences: the framework\'s fans and the people living the problem it is mapped onto.',
    ],
    template: [
      '{TheFramework}, applied to {HerDomain}:',
      '',
      'The idea in one paragraph: {TheCorePrinciple, fairly stated}.',
      '',
      'Where it maps:',
      '- {Principle1} -> {What it means in her Tuesday}',
      '- {Principle2} -> {TheTranslation}',
      '- {Principle3} -> {TheTranslation}',
      '',
      'Where it breaks: {Where the framework fails her world, honestly}.',
      'The upgraded version: {TheAdaptation: the framework rebuilt for her reality}.',
      '',
      '{SoftCTA}',
    ].join('\n'),
    exampleHooks: [
      'Getting Things Done, applied to the mental load: why capture-everything fails at home, and the one-page fix.',
      'Atomic Habits, applied to the 5 pm hour: what a habit stack looks like when the stakes are dinner.',
    ],
    craft: [
      'State the source framework fairly in one paragraph. The respect is what licenses the critique.',
      'Translate each principle into her Tuesday with specifics, then name honestly where the framework breaks in her world.',
      'The upgraded adaptation is the original contribution: teach it fully. Soft CTA closes.',
    ].join(' '),
    platforms: ['blog', 'linkedin', 'x'],
    formats: ['blog', 'article', 'thread'],
  }),

  F({
    id: 'lf-exhaustive-list',
    label: 'The exhaustive list',
    hint: 'Everything, organized, with what to skip',
    goal: 'saves',
    whyItWorks: [
      'The complete list on a topic is the most saved format in long-form, because it is a permanent reference.',
      'Organization is the value: 30 items grouped into 5 honest categories beats 100 items in a row.',
      'Telling her what to skip is the trust move: the skip section is what separates a guide from a dump.',
    ],
    template: [
      '{N} {Things} for {Outcome}, organized by {TheGroupingLogic}:',
      '',
      'Category 1: {TheEssential} (start here)',
      '1. {Item: what it is + one line on running it}',
      '2. {Item}',
      '',
      'Category 2: {TheLeverage}',
      '3. {Item}',
      '4. {Item}',
      '',
      'Category 3: {TheOptional}',
      '5. {Item}',
      '',
      'What to skip completely:',
      '- {PopularButUseless: and why}',
      '- {PopularButUseless}',
      '',
      '{TheOneThing: if she only does one, it is this}.',
      '{SoftCTA}',
    ].join('\n'),
    exampleHooks: [
      '27 ways to lighten the mental load, organized by effort. Start with the 3 that take under 20 minutes.',
      '19 systems for running a house, in 4 categories, plus the 5 popular ones to skip completely.',
    ],
    craft: [
      'Group the items by something meaningful (effort, payoff, time). The grouping is the insight; the list is the delivery.',
      'Every item gets a one-line how, never just a name. The list must be runnable, not just readable.',
      'The skip section is mandatory: name the popular advice that fails and why. Close on the single highest-leverage item.',
    ].join(' '),
    platforms: ['blog', 'pinterest', 'x'],
    formats: ['blog', 'article', 'thread', 'pin'],
    platformNotes: {
      pinterest: 'The categories become the pin structure: title carries the number and outcome, description lists the top category fully.',
    },
  }),
];
