/**
 * YouTube organic content: search-and-watch-time driven. Long-form pieces are
 * titled watch pages (16:9) with a chaptered script and a timestamped
 * description; Shorts are fast 9:16 hook-in-2s payoff loops. Audience is broad:
 * overwhelmed mothers and working, career women who arrive via search. Every
 * CTA routes back to the $7 Brain Dump. Voice rules apply: no em dashes, no
 * NO-list words.
 */
import type { ContentPiece } from './types';
import { CORE_HASHTAGS, IMAGE_STYLE } from './constants';

export const youtubeContent: ContentPiece[] = [
  {
    id: 'yt-long-1',
    platform: 'youtube',
    format: 'long',
    kind: 'organic',
    tone: 'system',
    theme: 'The mental load',
    title: 'Long-form: the mental load is an operating system',
    hook: 'The Mental Load Is an Operating System (Here Is How I Empty Mine in 20 Minutes)',
    hooks: [
      'The Mental Load Is an Operating System (Here Is How I Empty Mine in 20 Minutes)',
      'How I Empty My Mental Load in 20 Minutes a Week (The Full System)',
      'Why Your Brain Will Not Quiet Down at Night, and the 20-Minute Fix',
    ],
    media: {
      type: 'video',
      alt: 'Video thumbnail: a calm bone desk with a notebook and a cup of coffee in morning light',
      aspect: 'aspect-video',
      hint: '1280 x 720',
      prompt: `Landscape 16:9 YouTube thumbnail still: a warm bone desk with a single open notebook, a pen, and a cup of coffee in soft morning window light, generous negative space on the right for a bold title overlay, calm and editorial, no people, no text. ${IMAGE_STYLE}`,
    },
    script: [
      {
        at: 'Cold open (0:00)',
        onScreen: 'the night my brain would not shut off',
        voiceover: 'It is 11pm, the house is finally quiet, and my brain is not. Dentist, permission slip, the thing I have to defrost, the text I forgot to send. If that is you every night, you do not have a discipline problem. You are running an operating system in your head with nowhere to set it down. Let me show you how I empty mine in 20 minutes.',
        visual: 'Talk to camera in a lamp-lit room, calm and direct. Title card fades in.',
      },
      {
        at: 'Why your brain will not quiet down (1:12)',
        onScreen: 'open loops never close on their own',
        voiceover: 'Your brain treats every unfinished task as an open loop, and it keeps a low hum of attention running on each one so you do not forget. Hold 40 of them at once and the hum becomes a roar. You are not scattered. You are being asked to be a storage system, and a mind was never built for that job.',
        visual: 'B-roll of a cluttered counter, then back to camera. Simple on-screen list of open loops.',
      },
      {
        at: 'The weekly brain dump (3:40)',
        onScreen: 'rooms, people, time',
        voiceover: 'So once a week I do a brain dump. Do not start with a blank page, that is what makes you freeze. Walk through the rooms of your house, then through each person, then through time, today, this week, and the looming stuff with no date. You are not sorting yet. You are just getting every open loop out of your head and onto one page.',
        visual: 'Screen-record or overhead of a page filling in, then back to camera.',
      },
      {
        at: 'Sorting the dump (6:15)',
        onScreen: 'keep, share, simplify, drop',
        voiceover: 'Only once it is all out do you sort it. Go line by line and mark each item keep, share, simplify, or drop. Most people are stunned by how much is not actually theirs to carry, or is not actually necessary. This is where a list becomes a decision tool, because you cannot hand off or let go of what you could not see.',
        visual: 'Overhead of marking the page with four simple symbols. Close, warm.',
      },
      {
        at: 'Handing the load off (9:30)',
        onScreen: 'hand off areas, not tasks',
        voiceover: 'Here is the part that actually lightens the week. You do not hand off single tasks, because then you are still the manager who notices and reminds. You hand off whole areas, end to end, including the remembering. Owning dinner is not cooking when told what to make. It is knowing what is in the house and running it without you.',
        visual: 'Talk to camera, steady. One clean graphic: task versus area.',
      },
      {
        at: 'The $7 system (12:45)',
        onScreen: 'the 20-minute reset',
        voiceover: 'I turned the exact prompts I use into a 20-minute system so you never face a blank page. It walks you through the rooms, the people, and the time, then the sorting, in one sitting. It is 7 dollars and the link is in the description. But even if you just do this tonight on a scrap of paper, please do it. Your head deserves to go quiet.',
        visual: 'Warm close, gesture to description. End on the notebook.',
      },
    ],
    body: [
      'I used to think I was just bad at relaxing. It turned out I was running an entire household in my head with nowhere to set it down. This is the full 20-minute reset I do every week to empty the mental load, plus why it works and how to hand real weight off for good.',
      'Chapters:\n0:00 The night my brain would not shut off\n1:12 Why your brain will not quiet down\n3:40 The weekly brain dump, step by step\n6:15 Sorting the dump into keep, share, and drop\n9:30 Handing the load off without staying the manager\n12:45 The 20-minute system I turned into a $7 tool',
      'The Brain Dump System is the guided version of everything in this video, built so you never start from a blank page. It is 7 dollars and the link is below.',
    ],
    caption: undefined,
    cta: 'Empty your head in 20 minutes with the $7 Brain Dump System. Link in the description.',
    hashtags: [...CORE_HASHTAGS, 'mentalload', 'braindump'],
    visual: 'Landscape 1280 x 720 thumbnail, editorial desk still life, bold title space on the right.',
  },
  {
    id: 'yt-long-2',
    platform: 'youtube',
    format: 'long',
    kind: 'organic',
    tone: 'authority',
    theme: 'Quiet burnout',
    title: 'Long-form: why high-functioning women burn out quietly',
    hook: 'Why High-Functioning Women Burn Out Quietly (and the 20-Minute Reset That Helped Me)',
    hooks: [
      'Why High-Functioning Women Burn Out Quietly (and the 20-Minute Reset That Helped Me)',
      'The Burnout Nobody Sees: Why Capable Women Crash on the Inside First',
      'You Look Fine and You Are Running on Empty. Here Is the 20-Minute Reset.',
    ],
    media: {
      type: 'video',
      alt: 'Video thumbnail: a quiet window seat with a cold cup of tea in soft overcast daylight',
      aspect: 'aspect-video',
      hint: '1280 x 720',
      prompt: `Landscape 16:9 YouTube thumbnail still: a quiet window seat with a forgotten cup of tea gone cold and a folded blanket in soft overcast daylight, a sense of pause and depletion, generous space on the left for a bold title overlay, no people, no text. ${IMAGE_STYLE}`,
    },
    script: [
      {
        at: 'Cold open (0:00)',
        onScreen: 'the burnout nobody can see',
        voiceover: 'You hit every deadline. You answer every message. From the outside you look completely fine. And on the inside you are flat, short-tempered, and running on nothing. That is quiet burnout, and it hides best in the most capable women. I know, because it hid in me for years.',
        visual: 'Talk to camera in soft daylight, honest and steady. Title card in.',
      },
      {
        at: 'Why it stays invisible (1:20)',
        onScreen: 'high output masks the empty tank',
        voiceover: 'High-functioning burnout is sneaky because the output stays high while the recovery drops to zero. You keep delivering, so no one raises a flag, least of all you. But performance is not the same as capacity. You can be producing at full speed and be completely empty underneath, and the gap between the two is exactly where the crash lives.',
        visual: 'B-roll of a calendar full of blocks, then back to camera.',
      },
      {
        at: 'The real cause (3:30)',
        onScreen: 'it is a load problem, not a willpower problem',
        voiceover: 'The cause is rarely a lack of effort. It is the invisible load of running everything in your head, at work and at home, with no off switch and no handoff. You are not tired because you are weak. You are tired because you are holding two full operating systems at once and calling it normal.',
        visual: 'Direct to camera, calm authority. One clean graphic: performance versus capacity.',
      },
      {
        at: 'The 20-minute reset (5:40)',
        onScreen: 'get it out of your head first',
        voiceover: 'The reset that pulled me out was not a vacation I could never take. It was 20 minutes, once a week, getting every open loop out of my head and onto one page. Work and home, on the same page, because your brain does not file them separately. Seeing the true size of the load is the first honest step, and it is the one most people skip.',
        visual: 'Overhead of a page filling in, then back to camera.',
      },
      {
        at: 'Then lower the baseline (8:10)',
        onScreen: 'sort, then hand whole areas off',
        voiceover: 'Once it is on the page, you sort it: keep, share, simplify, drop. Then you hand off whole areas, end to end, so you stop being the manager who notices and reminds. A lighter baseline is what actually protects your capacity, not another productivity app stacked on top of a full head.',
        visual: 'Talk to camera. Graphic: task versus area.',
      },
      {
        at: 'The $7 system (11:00)',
        onScreen: 'the reset, made repeatable',
        voiceover: 'I built the prompts I use into a 20-minute system so the reset is repeatable and you never face a blank page. It is 7 dollars and the link is in the description. If you are the capable one who is quietly running on empty, start here. You are allowed to want a version of your life that does not cost you yourself.',
        visual: 'Warm close, gesture to description. End on the window seat.',
      },
    ],
    body: [
      'You look like you have it together and you are exhausted in a way sleep does not touch. This is why high-functioning women burn out quietly, what actually causes it, and the exact 20-minute weekly reset that helped me get my capacity back.',
      'Chapters:\n0:00 The burnout nobody can see\n1:20 Why it stays invisible\n3:30 The real cause: load, not willpower\n5:40 The 20-minute reset\n8:10 Lowering the baseline for good\n11:00 The system I turned into a $7 tool',
      'The Brain Dump System is the repeatable, guided version of the reset in this video, built for work and home on one page. It is 7 dollars and the link is below.',
    ],
    caption: undefined,
    cta: 'Reset your capacity in 20 minutes with the $7 Brain Dump System. Link in the description.',
    hashtags: [...CORE_HASHTAGS, 'burnout', 'workingmom'],
    visual: 'Landscape 1280 x 720 thumbnail, quiet window still life, bold title space on the left.',
  },
  {
    id: 'yt-short-1',
    platform: 'youtube',
    format: 'reel',
    kind: 'organic',
    tone: 'wedge',
    theme: 'The mental load',
    title: 'Short: 40 tabs open and none of them close',
    hook: 'POV: 40 tabs open in your head and not one of them will close.',
    hooks: [
      'POV: 40 tabs open in your head and not one of them will close.',
      'POV: it is 9pm and your brain has 40 tabs open, all of them yours.',
      'Nobody warned me my head would run with 40 tabs open at all times.',
    ],
    media: {
      type: 'video',
      alt: 'Video poster: talk to camera in a real kitchen at night, warm lamp light',
      aspect: 'aspect-[9/16]',
      hint: '1080 x 1920',
      prompt: `Vertical 9:16 documentary video still: a woman talking to camera in a real lived-in kitchen at night under warm lamp light, slightly handheld framing, candid and a little tired, everyday clutter soft in the background, authentic and unpolished. ${IMAGE_STYLE}`,
    },
    script: [
      { at: 'Hook (0-2s)', onScreen: 'POV: 40 tabs, none of them close', voiceover: 'POV: your brain has 40 tabs open and not one of them will close.', visual: 'Talk to camera, kitchen, night light. Fast in.' },
      { at: 'Relate (2-8s)', onScreen: 'the dentist. the form. the milk.', voiceover: 'The dentist. The permission slip. The milk. The text you forgot to send. They just keep running.', visual: 'Quick cuts of a counter, a fridge note, a phone.' },
      { at: 'Reframe (8-16s)', onScreen: 'you are not scattered', voiceover: 'And you blame yourself for being scattered. You are not scattered. You are holding a whole operating system in your head with no place to set it down.', visual: 'Back to camera, calmer, direct.' },
      { at: 'Payoff (16-24s)', onScreen: 'I empty mine in 20 min', voiceover: 'So once a week I dump every tab onto one page. 20 minutes, and my head finally goes quiet.', visual: 'Show a notebook page filling up, time-lapse feel.' },
      { at: 'CTA (24-30s)', onScreen: 'the system is $7. link below.', voiceover: 'I made it into a 7 dollar system. It is in the link below if you want your head back too.', visual: 'Point down to the link. End human, no hard sell.' },
    ],
    caption: 'the tabs do not close on their own. 20 minutes, one page, head goes quiet. $7, link below.',
    cta: 'Get your head back. $7. Link below.',
    hashtags: [...CORE_HASHTAGS, 'shorts', 'mentalload'],
    visual: 'Vertical 1080 x 1920. Native, handheld, hook in the first 2 seconds.',
  },
  {
    id: 'yt-short-2',
    platform: 'youtube',
    format: 'reel',
    kind: 'organic',
    tone: 'wedge',
    theme: 'Invisible labor',
    title: 'Short: the invisible list you never agreed to carry',
    hook: 'The invisible list you never agreed to carry.',
    hooks: [
      'The invisible list you never agreed to carry.',
      'Nobody handed you this list. You just became the only one holding it.',
      'There is a list running your whole house, and it lives in one head. Yours.',
    ],
    media: {
      type: 'video',
      alt: 'Video poster: handheld walk through a real home, small shoes and a school form by the door',
      aspect: 'aspect-[9/16]',
      hint: '1080 x 1920',
      prompt: `Vertical 9:16 documentary video still: a handheld point-of-view walking through a real family home in soft daylight, small shoes and a school form by the front door, gentle motion, lived-in and authentic, face unseen, natural light. ${IMAGE_STYLE}`,
    },
    script: [
      { at: 'Hook (0-2s)', onScreen: 'the list you never agreed to carry', voiceover: 'There is an invisible list you never actually agreed to carry.', visual: 'Handheld, walking through the house. Fast in.' },
      { at: 'Name it (2-9s)', onScreen: 'the sizes. the dates. the snacks.', voiceover: 'The shoe sizes. The due dates. The snack that fixes the meltdown. The name of the kid who was mean. You are the family search engine, and nobody thanks the search engine.', visual: 'Quick cuts: a drawer, a calendar, a pantry.' },
      { at: 'Turn (9-17s)', onScreen: 'it all lives in one head', voiceover: 'And every bit of it lives in one place. Your head. That is not devotion. That is a single point of failure, and it is you.', visual: 'Stop walking, talk straight to camera.' },
      { at: 'Payoff (17-24s)', onScreen: 'get it out of your head', voiceover: 'So once a week I get all of it out of my head and onto one page, in about 20 minutes. It stops living rent free up there.', visual: 'Notebook open to one filled page.' },
      { at: 'CTA (24-30s)', onScreen: 'the system is $7. link below.', voiceover: 'The system I use is 7 dollars in the link below. Put the list down.', visual: 'Point to the link. Soft ending.' },
    ],
    caption: 'you never agreed to be the family search engine. put the list down. 20 min, one page, $7 link below.',
    cta: 'Put the list down. $7. Link below.',
    hashtags: [...CORE_HASHTAGS, 'shorts', 'invisiblelabor'],
    visual: 'Vertical 1080 x 1920. Native, handheld, hook in the first 2 seconds.',
  },
  {
    id: 'yt-short-3',
    platform: 'youtube',
    format: 'reel',
    kind: 'organic',
    tone: 'wedge',
    theme: 'The mental load at work',
    title: 'Short: you run projects at work, nobody runs the one in your head',
    hook: 'You run projects at work. Nobody runs the one in your head.',
    hooks: [
      'You run projects at work. Nobody runs the one in your head.',
      'You would never run a project this way at work. So why do you run your life this way?',
      'At work you have a system for everything. At home the system is just your memory.',
    ],
    media: {
      type: 'video',
      alt: 'Video poster: talk to camera at a desk in daytime, calm and direct',
      aspect: 'aspect-[9/16]',
      hint: '1080 x 1920',
      prompt: `Vertical 9:16 documentary video still: a woman talking to camera at a tidy home desk in bright daytime light, composed and credible, a laptop softly out of focus behind her, authentic and unpolished framing, face partly visible. ${IMAGE_STYLE}`,
    },
    script: [
      { at: 'Hook (0-2s)', onScreen: 'you run projects. nobody runs yours.', voiceover: 'You run entire projects at work. Nobody runs the one in your head.', visual: 'Talk to camera at desk, daytime. Direct in.' },
      { at: 'Contrast (2-10s)', onScreen: 'at work: a system. at home: your memory.', voiceover: 'At work you would never keep every deadline, owner, and detail in your memory. You have a system. At home, the system is just you, remembering everything, for everyone, all the time.', visual: 'Gesture between two sides. Confident.' },
      { at: 'Turn (10-18s)', onScreen: 'the load is an ops problem', voiceover: 'The mental load is not a personality trait. It is an operations problem. And you already know that a process beats a good memory every single time.', visual: 'Move closer, direct to camera.' },

      { at: 'Payoff (18-25s)', onScreen: 'give it a system too', voiceover: 'So once a week I run the same move on my own head. 20 minutes, everything on one page, sorted like any other project.', visual: 'Show a page, then back to face.' },
      { at: 'CTA (25-31s)', onScreen: 'the system is $7. link below.', voiceover: 'I built it into a 7 dollar system in the link below. Give your life the system you already give your job.', visual: 'Point to the link. Calm close.' },
    ],
    caption: 'you run projects at work with a system. run the one in your head the same way. 20 min, one page, $7 link below.',
    cta: 'Give your life a system. $7. Link below.',
    hashtags: [...CORE_HASHTAGS, 'shorts', 'workingmom'],
    visual: 'Vertical 1080 x 1920. Native, credible desk framing, hook in the first 2 seconds.',
  },
];
